!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : BESS
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE BESSDyn(DBlk, Pref_pu, Qref_pu, Vref_pu, PFref, Ploc,  &
     &   Qloc, N, Sbase1, Fnom, Vrated_LV, Vdc_nom, Freq_PWM_GSC,       &
     &   L_GSC_pu, R_GSC_pu, C_GSC_pu, Rc_GSC_pu, Sbase, Vrated_HV,     &
     &   Vrated_MV, SCRmax)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PPCDyn        ! Power Plant Controller
!     SUBR    BatteryDyn    ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: DBlk
      REAL,    INTENT(IN)  :: Pref_pu, Qref_pu
      REAL,    INTENT(IN)  :: Vref_pu, PFref
      REAL,    INTENT(IN)  :: Ploc, Qloc, N
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vrated_LV, Vdc_nom
      REAL,    INTENT(IN)  :: Freq_PWM_GSC
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu, Rc_GSC_pu
      REAL,    INTENT(IN)  :: Sbase, Vrated_HV
      REAL,    INTENT(IN)  :: Vrated_MV, SCRmax

! Electrical Node Indices

! Control Signals
      INTEGER  BRK, Enable, APC, RPC, VRT, GTB
      REAL     Qpcc_pu, Vpcc_pu, Ppcc_pu, Pcmd_pu
      REAL     Qcmd_pu, Fpcc_pu, VBRKin_pu(3)
      REAL     VBRKout_pu(3), Vinrms_pu
      REAL     Voutrms_pu, Pblst_pu, Vpcc(3)
      REAL     Ipcc(3)

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 7
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 41
      IPGB      = NPGB
      NPGB      = NPGB + 10
      INODE     = NNODE + 2
      NNODE     = NNODE + 11
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 6
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Qpcc_pu  = STOF(ISTOF + 21)
      Vpcc_pu  = STOF(ISTOF + 22)
      Ppcc_pu  = STOF(ISTOF + 23)
      Pcmd_pu  = STOF(ISTOF + 24)
      Qcmd_pu  = STOF(ISTOF + 25)
      BRK      = STOI(ISTOI + 2)
      Enable   = STOI(ISTOI + 3)
      Fpcc_pu  = STOF(ISTOF + 26)
      APC      = STOI(ISTOI + 4)
      RPC      = STOI(ISTOI + 5)
      VRT      = STOI(ISTOI + 6)
      GTB      = STOI(ISTOI + 7)
      Vinrms_pu = STOF(ISTOF + 33)
      Voutrms_pu = STOF(ISTOF + 34)
      Pblst_pu = STOF(ISTOF + 35)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         VBRKin_pu(IT_0) = STOF(ISTOF + 26 + IT_0)
         VBRKout_pu(IT_0) = STOF(ISTOF + 29 + IT_0)
         Vpcc(IT_0) = STOF(ISTOF + 35 + IT_0)
         Ipcc(IT_0) = STOF(ISTOF + 38 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'BESS.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 240:[PPC] Power Plant Controller 
      CALL PPCDyn(Pref_pu, PFref, Qref_pu, Vref_pu, Qpcc_pu, Vpcc_pu, Pp&
     &cc_pu, Pcmd_pu, Qcmd_pu, BRK, Enable, Fpcc_pu, DBlk, APC, RPC, VRT&
     &, GTB, VBRKin_pu, VBRKout_pu, Vinrms_pu, Voutrms_pu, Pblst_pu, 1.0&
     &, 0.0, 0.6, -0.6, 1.2, 0.8)


! 250:[Battery]  
      CALL BatteryDyn(Pcmd_pu, Qcmd_pu, Enable, VRT, APC, RPC, Fnom, Sba&
     &se1, Vrated_LV, Vdc_nom, L_GSC_pu, R_GSC_pu, C_GSC_pu, Rc_GSC_pu, &
     &Freq_PWM_GSC, Pblst_pu, SCRmax, Ppcc_pu, Qpcc_pu, Vpcc_pu, Fpcc_pu&
     &, Vpcc, Ipcc)


! 260:[pgb] Output Channel 'Ipcc'

      DO IVD1_1 = 1, 3
         PGB(IPGB+1+IVD1_1-1) = Ipcc(IVD1_1)
      ENDDO

! 270:[pgb] Output Channel 'Vpcc'

      DO IVD1_1 = 1, 3
         PGB(IPGB+4+IVD1_1-1) = Vpcc(IVD1_1)
      ENDDO

! 280:[pgb] Output Channel 'Fpcc_pu'

      PGB(IPGB+7) = Fpcc_pu

! 290:[pgb] Output Channel 'Vpcc_pu'

      PGB(IPGB+8) = Vpcc_pu

! 300:[pgb] Output Channel 'Qpcc_pu'

      PGB(IPGB+9) = Qpcc_pu

! 310:[pgb] Output Channel 'Ppcc_pu'

      PGB(IPGB+10) = Ppcc_pu

! 320:[breaker3] 3 Phase Breaker 'BRK'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS, (IBRCH+1),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(BRK)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+2),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(BRK)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+3),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(BRK)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH+1),SS))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH+2),SS))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH+3),SS))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,539755099,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,539755099,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,539755099,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH+1),SS))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH+2),SS))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH+3),SS))

! 330:[breaker3] 3 Phase Breaker 'GTB'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS, (IBRCH+4),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(GTB)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+5),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(GTB)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+6),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(GTB)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH+4),SS))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH+5),SS))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH+6),SS))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,79289047,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,79289047,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,79289047,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH+4),SS))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH+5),SS))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH+6),SS))

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = DBlk
      STOF(ISTOF + 1) = Pref_pu
      STOF(ISTOF + 2) = Qref_pu
      STOF(ISTOF + 3) = Vref_pu
      STOF(ISTOF + 4) = PFref
      STOF(ISTOF + 5) = Ploc
      STOF(ISTOF + 6) = Qloc
      STOF(ISTOF + 7) = N
      STOF(ISTOF + 8) = Sbase1
      STOF(ISTOF + 9) = Fnom
      STOF(ISTOF + 10) = Vrated_LV
      STOF(ISTOF + 11) = Vdc_nom
      STOF(ISTOF + 12) = Freq_PWM_GSC
      STOF(ISTOF + 13) = L_GSC_pu
      STOF(ISTOF + 14) = R_GSC_pu
      STOF(ISTOF + 15) = C_GSC_pu
      STOF(ISTOF + 16) = Rc_GSC_pu
      STOF(ISTOF + 17) = Sbase
      STOF(ISTOF + 18) = Vrated_HV
      STOF(ISTOF + 19) = Vrated_MV
      STOF(ISTOF + 20) = SCRmax
      STOF(ISTOF + 21) = Qpcc_pu
      STOF(ISTOF + 22) = Vpcc_pu
      STOF(ISTOF + 23) = Ppcc_pu
      STOF(ISTOF + 24) = Pcmd_pu
      STOF(ISTOF + 25) = Qcmd_pu
      STOI(ISTOI + 2) = BRK
      STOI(ISTOI + 3) = Enable
      STOF(ISTOF + 26) = Fpcc_pu
      STOI(ISTOI + 4) = APC
      STOI(ISTOI + 5) = RPC
      STOI(ISTOI + 6) = VRT
      STOI(ISTOI + 7) = GTB
      STOF(ISTOF + 33) = Vinrms_pu
      STOF(ISTOF + 34) = Voutrms_pu
      STOF(ISTOF + 35) = Pblst_pu

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 26 + IT_0) = VBRKin_pu(IT_0)
         STOF(ISTOF + 29 + IT_0) = VBRKout_pu(IT_0)
         STOF(ISTOF + 35 + IT_0) = Vpcc(IT_0)
         STOF(ISTOF + 38 + IT_0) = Ipcc(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BESSOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
!     SUBR    DGTL_RMS3     ! '3 Phase Digital RMS Meter'
!     SUBR    PPCOut        ! Power Plant Controller
!     SUBR    BatteryOut    ! 
      REAL    VBRANCH       ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_1(3), NT_2(3)

! Control Signals
      REAL     VBRKin_pu(3), VBRKout_pu(3)
      REAL     Vinrms_pu, Voutrms_pu

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 10
      INODE     = NNODE + 2
      NNODE     = NNODE + 11
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 6
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vinrms_pu = STOF(ISTOF + 33)
      Voutrms_pu = STOF(ISTOF + 34)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         VBRKin_pu(IT_0) = STOF(ISTOF + 26 + IT_0)
         VBRKout_pu(IT_0) = STOF(ISTOF + 29 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_1(IT_0) = NODE(INODE + 3 + IT_0)
         NT_2(IT_0) = NODE(INODE + 6 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'BESS.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 220:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      VBRKout_pu(1) = EMTDC_VVDC(SS, NT_2(1), 0)
      VBRKout_pu(2) = EMTDC_VVDC(SS, NT_2(2), 0)
      VBRKout_pu(3) = EMTDC_VVDC(SS, NT_2(3), 0)
      CALL DGTL_RMS3(256,SS,NT_2(1),NT_2(2),NT_2(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      Voutrms_pu = RVD1_1

! 230:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      VBRKin_pu(1) = EMTDC_VVDC(SS, NT_1(1), 0)
      VBRKin_pu(2) = EMTDC_VVDC(SS, NT_1(2), 0)
      VBRKin_pu(3) = EMTDC_VVDC(SS, NT_1(3), 0)
      CALL DGTL_RMS3(256,SS,NT_1(1),NT_1(2),NT_1(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      Vinrms_pu = RVD1_1

! 240:[PPC] Power Plant Controller 
      CALL PPCOut()


! 250:[Battery]  
      CALL BatteryOut()


! 320:[breaker3] 3 Phase Breaker 'BRK'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3),0,0,0,IVD1_1,0.&
     &02,RVD1_1,RVD1_2)

! 330:[breaker3] 3 Phase Breaker 'GTB'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS, (IBRCH+4), (IBRCH+5), (IBRCH+6),0,0,0,IVD1_1,0.&
     &02,RVD1_1,RVD1_2)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 33) = Vinrms_pu
      STOF(ISTOF + 34) = Voutrms_pu

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 26 + IT_0) = VBRKin_pu(IT_0)
         STOF(ISTOF + 29 + IT_0) = VBRKout_pu(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BESSDyn_Begin(Ploc, Qloc, N, Sbase1, Fnom, Vrated_LV,  &
     &   Vdc_nom, Freq_PWM_GSC, L_GSC_pu, R_GSC_pu, C_GSC_pu, Sbase,    &
     &   Vrated_HV, Vrated_MV)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PPCDyn_Begin  ! Power Plant Controller
!     SUBR    BatteryDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Ploc, Qloc, N
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vrated_LV, Vdc_nom
      REAL,    INTENT(IN)  :: Freq_PWM_GSC
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu, Sbase
      REAL,    INTENT(IN)  :: Vrated_HV
      REAL,    INTENT(IN)  :: Vrated_MV

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 11
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 6
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 240:[PPC] Power Plant Controller 
      CALL PPCDyn_Begin(1.0, 0.0, 0.6, -0.6, 1.2, 0.8)


! 250:[Battery]  
      CALL BatteryDyn_Begin(Fnom, Sbase1, Vrated_LV, Vdc_nom, L_GSC_pu, &
     &R_GSC_pu, C_GSC_pu, Freq_PWM_GSC)


! 260:[pgb] Output Channel 'Ipcc'

! 270:[pgb] Output Channel 'Vpcc'

! 280:[pgb] Output Channel 'Fpcc_pu'

! 290:[pgb] Output Channel 'Vpcc_pu'

! 300:[pgb] Output Channel 'Qpcc_pu'

! 310:[pgb] Output Channel 'Ppcc_pu'

! 320:[breaker3] 3 Phase Breaker 'BRK'
      CALL COMPONENT_ID(ICALL_NO,539755099)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 330:[breaker3] 3 Phase Breaker 'GTB'
      CALL COMPONENT_ID(ICALL_NO,79289047)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

      RETURN
      END

!=======================================================================

      SUBROUTINE BESSOut_Begin(Ploc, Qloc, N, Sbase1, Fnom, Vrated_LV,  &
     &   Vdc_nom, Freq_PWM_GSC, L_GSC_pu, R_GSC_pu, C_GSC_pu, Sbase,    &
     &   Vrated_HV, Vrated_MV)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PPCOut_Begin  ! Power Plant Controller
!     SUBR    BatteryOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Ploc, Qloc, N
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vrated_LV, Vdc_nom
      REAL,    INTENT(IN)  :: Freq_PWM_GSC
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu, Sbase
      REAL,    INTENT(IN)  :: Vrated_HV
      REAL,    INTENT(IN)  :: Vrated_MV

! Electrical Node Indices
      INTEGER  NT_1(3), NT_2(3)

! Control Signals

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 11
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 6
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_1(IT_0) = NODE(INODE + 3 + IT_0)
         NT_2(IT_0) = NODE(INODE + 6 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 220:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(Vrated_MV) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vrated_MV)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+3) = Fnom

! 230:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(Vrated_MV) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vrated_MV)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+3) = Fnom

! 240:[PPC] Power Plant Controller 
      CALL PPCOut_Begin(1.0, 0.0, 0.6, -0.6, 1.2, 0.8)


! 250:[Battery]  
      CALL BatteryOut_Begin(Fnom, Sbase1, Vrated_LV, Vdc_nom, L_GSC_pu, &
     &R_GSC_pu, C_GSC_pu, Freq_PWM_GSC)


      RETURN
      END

