!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : GSC_Current_Controller
! Description   : GSC Current Controller
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE GSC_Current_ControllerDyn(Idq_pu, Idqref_pu,           &
     &   Vdqref_pu_, Enable, Vdq_pu, Frz, Kp_GCC, Ki_GCC, Kff_GCC,      &
     &   ChFreq_GCC, Kdc_GCC)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, Frz(2)
      REAL,    INTENT(IN)  :: Idq_pu(2)
      REAL,    INTENT(IN)  :: Idqref_pu(2)
      REAL,    INTENT(IN)  :: Vdq_pu(2), Kp_GCC
      REAL,    INTENT(IN)  :: Ki_GCC, Kff_GCC
      REAL,    INTENT(IN)  :: ChFreq_GCC, Kdc_GCC
      REAL,    INTENT(OUT) :: Vdqref_pu_(2)! Aliases: Vdqref_pu

! Electrical Node Indices

! Control Signals
      INTEGER  Frz_d, Frz_q
      REAL     RT_1, RT_2, RT_3, RT_4, test3
      REAL     RT_5, test1, RT_6, Ti_GCC, RT_7
      REAL     Vtdref_pu, Vtqref_pu, Idref_pu
      REAL     Id_pu, Iqref_pu, Iq_pu, Vd_pu
      REAL     Vq_pu, True, RT_8, RT_9, RT_10
      REAL     RT_11, RT_12, RT_13

! Internal Variables
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 5
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 38
      IPGB      = NPGB
      NPGB      = NPGB + 10
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 14)
      RT_2     = STOF(ISTOF + 15)
      RT_3     = STOF(ISTOF + 16)
      RT_4     = STOF(ISTOF + 17)
      test3    = STOF(ISTOF + 18)
      RT_5     = STOF(ISTOF + 19)
      test1    = STOF(ISTOF + 20)
      RT_6     = STOF(ISTOF + 21)
      Ti_GCC   = STOF(ISTOF + 22)
      RT_7     = STOF(ISTOF + 23)
      Vtdref_pu = STOF(ISTOF + 24)
      Vtqref_pu = STOF(ISTOF + 25)
      Idref_pu = STOF(ISTOF + 26)
      Id_pu    = STOF(ISTOF + 27)
      Iqref_pu = STOF(ISTOF + 28)
      Iq_pu    = STOF(ISTOF + 29)
      Vd_pu    = STOF(ISTOF + 30)
      Vq_pu    = STOF(ISTOF + 31)
      Frz_d    = STOI(ISTOI + 4)
      Frz_q    = STOI(ISTOI + 5)
      True     = STOF(ISTOF + 32)
      RT_8     = STOF(ISTOF + 33)
      RT_9     = STOF(ISTOF + 34)
      RT_10    = STOF(ISTOF + 35)
      RT_11    = STOF(ISTOF + 36)
      RT_12    = STOF(ISTOF + 37)
      RT_13    = STOF(ISTOF + 38)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         Vdqref_pu_(IT_0) = STOF(ISTOF + 4 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'GSC_Current_Controller.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 
      True = 1.0

! 60:[const] Real Constant 
      RT_7 = 1.0

! 130:[datatap] Scalar/Array Tap 
      Frz_q = Frz(2)

! 140:[pgb] Output Channel 'Frz_q'

      PGB(IPGB+1) = REAL(Frz_q)

! 150:[datatap] Scalar/Array Tap 
      Vd_pu = Vdq_pu(1)

! 160:[datatap] Scalar/Array Tap 
      Vq_pu = Vdq_pu(2)

! 170:[datatap] Scalar/Array Tap 
      Idref_pu = Idqref_pu(1)

! 180:[gain] Gain Block 
!  Gain
      RT_4 = 1.0 * Vd_pu

! 190:[datatap] Scalar/Array Tap 
      Iqref_pu = Idqref_pu(2)

! 200:[datatap] Scalar/Array Tap 
      Id_pu = Idq_pu(1)

! 210:[datatap] Scalar/Array Tap 
      Iq_pu = Idq_pu(2)

! 220:[gain] Gain Block 
!  Gain
      test1 = 1.0 * Vq_pu

! 230:[datatap] Scalar/Array Tap 
      Frz_d = Frz(1)

! 240:[gain] Gain Block 
!  Gain
      RT_2 = 0.1 * Iq_pu

! 250:[sumjct] Summing/Differencing Junctions 
      RT_1 = - Id_pu + Idref_pu

! 260:[gain] Gain Block 
!  Gain
      RT_13 = 0.31831 * RT_1

! 270:[gain] Gain Block 
!  Gain
      test3 = 0.1 * Id_pu

! 280:[sumjct] Summing/Differencing Junctions 
      RT_6 = - Iq_pu + Iqref_pu

! 290:[gain] Gain Block 
!  Gain
      RT_10 = 0.31831 * RT_6

! 300:[gain] Gain Block 
!  Gain
      RT_11 = 25.0 * RT_1

! 310:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_11
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_12 = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -1.0e+308, 1.0e+308,&
     & RVD2_2, RVD2_1)

! 320:[sumjct] Summing/Differencing Junctions 
      RT_3 = + RT_12 + RT_13

! 330:[gain] Gain Block 
!  Gain
      RT_8 = 25.0 * RT_6

! 340:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_8
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_9 = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -1.0e+308, 1.0e+308, &
     &RVD2_2, RVD2_1)

! 350:[sumjct] Summing/Differencing Junctions 
      RT_5 = + RT_9 + RT_10

! 360:[sumjct] Summing/Differencing Junctions 
      Vtdref_pu = - RT_2 + RT_3 + RT_4

! 370:[sumjct] Summing/Differencing Junctions 
      Vtqref_pu = + test3 + RT_5 + test1

! 380:[datamerge] Merges data signals into an array 
      Vdqref_pu_(1) = Vtdref_pu
      Vdqref_pu_(2) = Vtqref_pu

! 400:[pgb] Output Channel 'Frz_d'

      PGB(IPGB+2) = REAL(Frz_d)

! 410:[div] Divider 
      IF (ABS(Ki_GCC) .LT. 1.0E-100) THEN
         IF (Ki_GCC .LT. 0.0)  THEN
            Ti_GCC = -1.0E100 * RT_7
         ELSE
            Ti_GCC =  1.0E100 * RT_7
         ENDIF
      ELSE
         Ti_GCC = RT_7 / Ki_GCC
      ENDIF

! 420:[pgb] Output Channel 'Iq_pu'

      PGB(IPGB+3) = Iq_pu

! 430:[pgb] Output Channel 'Vtqref_pu'

      PGB(IPGB+4) = Vtqref_pu

! 440:[pgb] Output Channel 'Iqref_pu'

      PGB(IPGB+5) = Iqref_pu

! 450:[pgb] Output Channel 'Id_pu'

      PGB(IPGB+6) = Id_pu

! 460:[pgb] Output Channel 'Vtdref_pu'

      PGB(IPGB+7) = Vtdref_pu

! 470:[pgb] Output Channel 'Vq_pu'

      PGB(IPGB+8) = Vq_pu

! 480:[pgb] Output Channel 'Idref_pu'

      PGB(IPGB+9) = Idref_pu

! 490:[pgb] Output Channel 'Vd_pu'

      PGB(IPGB+10) = Vd_pu

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = Enable
      STOF(ISTOF + 9) = Kp_GCC
      STOF(ISTOF + 10) = Ki_GCC
      STOF(ISTOF + 11) = Kff_GCC
      STOF(ISTOF + 12) = ChFreq_GCC
      STOF(ISTOF + 13) = Kdc_GCC
      STOF(ISTOF + 14) = RT_1
      STOF(ISTOF + 15) = RT_2
      STOF(ISTOF + 16) = RT_3
      STOF(ISTOF + 17) = RT_4
      STOF(ISTOF + 18) = test3
      STOF(ISTOF + 19) = RT_5
      STOF(ISTOF + 20) = test1
      STOF(ISTOF + 21) = RT_6
      STOF(ISTOF + 22) = Ti_GCC
      STOF(ISTOF + 23) = RT_7
      STOF(ISTOF + 24) = Vtdref_pu
      STOF(ISTOF + 25) = Vtqref_pu
      STOF(ISTOF + 26) = Idref_pu
      STOF(ISTOF + 27) = Id_pu
      STOF(ISTOF + 28) = Iqref_pu
      STOF(ISTOF + 29) = Iq_pu
      STOF(ISTOF + 30) = Vd_pu
      STOF(ISTOF + 31) = Vq_pu
      STOI(ISTOI + 4) = Frz_d
      STOI(ISTOI + 5) = Frz_q
      STOF(ISTOF + 32) = True
      STOF(ISTOF + 33) = RT_8
      STOF(ISTOF + 34) = RT_9
      STOF(ISTOF + 35) = RT_10
      STOF(ISTOF + 36) = RT_11
      STOF(ISTOF + 37) = RT_12
      STOF(ISTOF + 38) = RT_13

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 0 + IT_0) = Idq_pu(IT_0)
         STOF(ISTOF + 2 + IT_0) = Idqref_pu(IT_0)
         STOF(ISTOF + 4 + IT_0) = Vdqref_pu_(IT_0)
         STOF(ISTOF + 6 + IT_0) = Vdq_pu(IT_0)
         STOI(ISTOI + 1 + IT_0) = Frz(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Vdqref_pu_ is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE GSC_Current_ControllerOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_7, True

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 10
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_7     = STOF(ISTOF + 23)
      True     = STOF(ISTOF + 32)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'GSC_Current_Controller.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 

      True = 1.0

! 60:[const] Real Constant 

      RT_7 = 1.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 23) = RT_7
      STOF(ISTOF + 32) = True


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE GSC_Current_ControllerDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_7, True

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 
      True = 1.0

! 60:[const] Real Constant 
      RT_7 = 1.0

! 130:[datatap] Scalar/Array Tap 

! 140:[pgb] Output Channel 'Frz_q'

! 150:[datatap] Scalar/Array Tap 

! 160:[datatap] Scalar/Array Tap 

! 170:[datatap] Scalar/Array Tap 

! 180:[gain] Gain Block 

! 190:[datatap] Scalar/Array Tap 

! 200:[datatap] Scalar/Array Tap 

! 210:[datatap] Scalar/Array Tap 

! 220:[gain] Gain Block 

! 230:[datatap] Scalar/Array Tap 

! 240:[gain] Gain Block 

! 250:[sumjct] Summing/Differencing Junctions 

! 260:[gain] Gain Block 

! 270:[gain] Gain Block 

! 280:[sumjct] Summing/Differencing Junctions 

! 290:[gain] Gain Block 

! 300:[gain] Gain Block 

! 310:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 320:[sumjct] Summing/Differencing Junctions 

! 330:[gain] Gain Block 

! 340:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 350:[sumjct] Summing/Differencing Junctions 

! 360:[sumjct] Summing/Differencing Junctions 

! 370:[sumjct] Summing/Differencing Junctions 

! 380:[datamerge] Merges data signals into an array 

! 400:[pgb] Output Channel 'Frz_d'

! 410:[div] Divider 

! 420:[pgb] Output Channel 'Iq_pu'

! 430:[pgb] Output Channel 'Vtqref_pu'

! 440:[pgb] Output Channel 'Iqref_pu'

! 450:[pgb] Output Channel 'Id_pu'

! 460:[pgb] Output Channel 'Vtdref_pu'

! 470:[pgb] Output Channel 'Vq_pu'

! 480:[pgb] Output Channel 'Idref_pu'

! 490:[pgb] Output Channel 'Vd_pu'

      RETURN
      END

!=======================================================================

      SUBROUTINE GSC_Current_ControllerOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_7, True

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 
      True = 1.0

! 60:[const] Real Constant 
      RT_7 = 1.0

      RETURN
      END

