!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Parameters_Filters
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Parameters_FiltersDyn(L_GSC_pu, R_GSC_pu, C_GSC_pu,    &
     &   Rc_GSC_pu, Sbase1, Fnom, Vac_nom, L_GSC_, R_GSC_, C_GSC_,      &
     &   Rc_GSC_)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu, Rc_GSC_pu
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vac_nom
      REAL,    INTENT(OUT) :: L_GSC_! Aliases: L_GSC
      REAL,    INTENT(OUT) :: R_GSC_! Aliases: R_GSC
      REAL,    INTENT(OUT) :: C_GSC_! Aliases: C_GSC
      REAL,    INTENT(OUT) :: Rc_GSC_! Aliases: Rc_GSC

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, Lb, RT_4, RT_5
      REAL     Cb, RT_6, RT_7, Zb

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF                               ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 21
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      L_GSC_   = STOF(ISTOF + 8)
      R_GSC_   = STOF(ISTOF + 9)
      C_GSC_   = STOF(ISTOF + 10)
      Rc_GSC_  = STOF(ISTOF + 11)
      RT_1     = STOF(ISTOF + 12)
      RT_2     = STOF(ISTOF + 13)
      RT_3     = STOF(ISTOF + 14)
      Lb       = STOF(ISTOF + 15)
      RT_4     = STOF(ISTOF + 16)
      RT_5     = STOF(ISTOF + 17)
      Cb       = STOF(ISTOF + 18)
      RT_6     = STOF(ISTOF + 19)
      RT_7     = STOF(ISTOF + 20)
      Zb       = STOF(ISTOF + 21)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Parameters_Filters.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[square] Square 
      RT_1 = Vac_nom * Vac_nom

! 90:[div] Divider 
      IF (ABS(Sbase1) .LT. 1.0E-100) THEN
         IF (Sbase1 .LT. 0.0)  THEN
            Zb = -1.0E100 * RT_1
         ELSE
            Zb =  1.0E100 * RT_1
         ENDIF
      ELSE
         Zb = RT_1 / Sbase1
      ENDIF

! 100:[const] Real Constant 
      RT_6 = 1000000.0

! 110:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = TWO_PI

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_4 = TWO_PI

! 130:[gain] Gain Block 
!  Gain
      Rc_GSC_ = Zb * Rc_GSC_pu

! 140:[mult] Multiplier 
      RT_5 = Fnom * RT_4

! 150:[mult] Multiplier 
      RT_7 = RT_5 * Zb

! 160:[mult] Multiplier 
      RT_3 = RT_2 * Fnom

! 170:[div] Divider 
      IF (ABS(RT_7) .LT. 1.0E-100) THEN
         IF (RT_7 .LT. 0.0)  THEN
            Cb = -1.0E100 * RT_6
         ELSE
            Cb =  1.0E100 * RT_6
         ENDIF
      ELSE
         Cb = RT_6 / RT_7
      ENDIF

! 180:[div] Divider 
      IF (ABS(RT_3) .LT. 1.0E-100) THEN
         IF (RT_3 .LT. 0.0)  THEN
            Lb = -1.0E100 * Zb
         ELSE
            Lb =  1.0E100 * Zb
         ENDIF
      ELSE
         Lb = Zb / RT_3
      ENDIF

! 190:[gain] Gain Block 
!  Gain
      C_GSC_ = Cb * C_GSC_pu

! 200:[gain] Gain Block 
!  Gain
      R_GSC_ = Zb * R_GSC_pu

! 210:[gain] Gain Block 
!  Gain
      L_GSC_ = Lb * L_GSC_pu

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = L_GSC_pu
      STOF(ISTOF + 2) = R_GSC_pu
      STOF(ISTOF + 3) = C_GSC_pu
      STOF(ISTOF + 4) = Rc_GSC_pu
      STOF(ISTOF + 5) = Sbase1
      STOF(ISTOF + 6) = Fnom
      STOF(ISTOF + 7) = Vac_nom
      STOF(ISTOF + 8) = L_GSC_
      STOF(ISTOF + 9) = R_GSC_
      STOF(ISTOF + 10) = C_GSC_
      STOF(ISTOF + 11) = Rc_GSC_
      STOF(ISTOF + 12) = RT_1
      STOF(ISTOF + 13) = RT_2
      STOF(ISTOF + 14) = RT_3
      STOF(ISTOF + 15) = Lb
      STOF(ISTOF + 16) = RT_4
      STOF(ISTOF + 17) = RT_5
      STOF(ISTOF + 18) = Cb
      STOF(ISTOF + 19) = RT_6
      STOF(ISTOF + 20) = RT_7
      STOF(ISTOF + 21) = Zb


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !L_GSC_   is output
      !R_GSC_   is output
      !C_GSC_   is output
      !Rc_GSC_  is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Parameters_FiltersOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_2, RT_4, RT_6

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_2     = STOF(ISTOF + 13)
      RT_4     = STOF(ISTOF + 16)
      RT_6     = STOF(ISTOF + 19)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Parameters_Filters.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 100:[const] Real Constant 

      RT_6 = 1000000.0

! 110:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = TWO_PI

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_4 = TWO_PI

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 13) = RT_2
      STOF(ISTOF + 16) = RT_4
      STOF(ISTOF + 19) = RT_6


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Parameters_FiltersDyn_Begin(Sbase1, Fnom, Vac_nom)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vac_nom

! Electrical Node Indices

! Control Signals
      REAL     RT_2, RT_4, RT_6

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[square] Square 

! 90:[div] Divider 

! 100:[const] Real Constant 
      RT_6 = 1000000.0

! 110:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = TWO_PI

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_4 = TWO_PI

! 130:[gain] Gain Block 

! 140:[mult] Multiplier 

! 150:[mult] Multiplier 

! 160:[mult] Multiplier 

! 170:[div] Divider 

! 180:[div] Divider 

! 190:[gain] Gain Block 

! 200:[gain] Gain Block 

! 210:[gain] Gain Block 

      RETURN
      END

!=======================================================================

      SUBROUTINE Parameters_FiltersOut_Begin(Sbase1, Fnom, Vac_nom)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vac_nom

! Electrical Node Indices

! Control Signals
      REAL     RT_2, RT_4, RT_6

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 100:[const] Real Constant 
      RT_6 = 1000000.0

! 110:[emtconst] Commonly Used Constants (pi...) 
      RT_2 = TWO_PI

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_4 = TWO_PI

      RETURN
      END

