!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : PI_AntiWindUp
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE PI_AntiWindUpDyn(In, Out, frz, Rst, Kp, Ti, Kaw,       &
     &   MaxOut, MinOut)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: frz, Rst
      REAL,    INTENT(IN)  :: In, Kp, Ti, Kaw
      REAL,    INTENT(IN)  :: MaxOut, MinOut
      REAL,    INTENT(OUT) :: Out

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9

! Internal Variables
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 3
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 16
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Out      = STOF(ISTOF + 2)
      RT_1     = STOF(ISTOF + 8)
      RT_2     = STOF(ISTOF + 9)
      RT_3     = STOF(ISTOF + 10)
      RT_4     = STOF(ISTOF + 11)
      IT_1     = STOI(ISTOI + 3)
      RT_5     = STOF(ISTOF + 12)
      RT_6     = STOF(ISTOF + 13)
      RT_7     = STOF(ISTOF + 14)
      RT_8     = STOF(ISTOF + 15)
      RT_9     = STOF(ISTOF + 16)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PI_AntiWindUp.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[const] Real Constant 
      RT_9 = 0.0

! 90:[sumjct] Summing/Differencing Junctions 
      RT_8 = + RT_6 + In

! 100:[select] Two Input Selector 
      IF (frz .EQ. RTCI(NRTCI)) THEN
         RT_4 = RT_9
      ELSE
         RT_4 = RT_8
      ENDIF
      NRTCI = NRTCI + 1
!

! 110:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_4
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      RT_1 = EMTDC_XINT(0, 0, 0, RVD1_1, Ti, 0.0, MinOut, MaxOut, RVD2_2&
     &, RVD2_1)

! 130:[inv] Interpolated Logic Inverter 
      IF (Rst .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 140:[mult] Multiplier 
      RT_3 = In * REAL(IT_1)

! 150:[gain] Gain Block 
!  Gain
      RT_2 = Kp * RT_3

! 160:[sumjct] Summing/Differencing Junctions 
      Out = + RT_1 + RT_2

! 170:[sumjct] Summing/Differencing Junctions 
      RT_5 = - Out + Out

! 180:[gain] Gain Block 
!  Gain
      RT_7 = Kaw * RT_5

! 200:[zminusone] Feedback Loop Selector 'Feedback Loop XYZ'
! Feedback Loop XYZ
      RT_6 = RT_7

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = In
      STOF(ISTOF + 2) = Out
      STOI(ISTOI + 1) = frz
      STOI(ISTOI + 2) = Rst
      STOF(ISTOF + 3) = Kp
      STOF(ISTOF + 4) = Ti
      STOF(ISTOF + 5) = Kaw
      STOF(ISTOF + 6) = MaxOut
      STOF(ISTOF + 7) = MinOut
      STOF(ISTOF + 8) = RT_1
      STOF(ISTOF + 9) = RT_2
      STOF(ISTOF + 10) = RT_3
      STOF(ISTOF + 11) = RT_4
      STOI(ISTOI + 3) = IT_1
      STOF(ISTOF + 12) = RT_5
      STOF(ISTOF + 13) = RT_6
      STOF(ISTOF + 14) = RT_7
      STOF(ISTOF + 15) = RT_8
      STOF(ISTOF + 16) = RT_9


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Out      is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PI_AntiWindUpOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_9

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_9     = STOF(ISTOF + 16)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'PI_AntiWindUp.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[const] Real Constant 

      RT_9 = 0.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 16) = RT_9


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE PI_AntiWindUpDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_9

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[const] Real Constant 
      RT_9 = 0.0

! 90:[sumjct] Summing/Differencing Junctions 

! 100:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 110:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

! 130:[inv] Interpolated Logic Inverter 

! 140:[mult] Multiplier 

! 150:[gain] Gain Block 

! 160:[sumjct] Summing/Differencing Junctions 

! 170:[sumjct] Summing/Differencing Junctions 

! 180:[gain] Gain Block 

! 200:[zminusone] Feedback Loop Selector 'Feedback Loop XYZ'

      RETURN
      END

!=======================================================================

      SUBROUTINE PI_AntiWindUpOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_9

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[const] Real Constant 
      RT_9 = 0.0

      RETURN
      END

