!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Primary_Controller
! Description   : Primary Controller
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Primary_ControllerDyn(Q_pu, P_pu, Qref_pu, wt_,        &
     &   Enable, Pref_pu, Vdqref_pu_, VRT, Frz, Fnom, APC_Type,         &
     &   RPC_Type, SCRmax, Kp, H_VSG, tau, D, D_VSG, wp, Kq, wq,        &
     &   Ki_psi, Kp_psi, Ki_rpc, Kp_rpc, f_pu_)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    APC_DroopDyn  ! APC (Droop)
!     SUBR    RPC_DroopDyn  ! RPC (Droop)
!     SUBR    RPC_PIDyn     ! RPC (PI)
!     SUBR    APC_VSGDyn    ! APC (VSG)
!     SUBR    APC_GCVSGDyn  ! APC (GCVSG)
!     SUBR    RPC_RotorFluxModelDyn  ! RPC (Rotor Flux Model)
      REAL    DERIV1        ! Derivative Function

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, VRT, Frz(2)
      INTEGER, INTENT(IN)  :: APC_Type, RPC_Type
      REAL,    INTENT(IN)  :: Q_pu, P_pu, Qref_pu
      REAL,    INTENT(IN)  :: Pref_pu, Fnom
      REAL,    INTENT(IN)  :: SCRmax, Kp, H_VSG
      REAL,    INTENT(IN)  :: tau, D, D_VSG, wp
      REAL,    INTENT(IN)  :: Kq, wq, Ki_psi
      REAL,    INTENT(IN)  :: Kp_psi, Ki_rpc
      REAL,    INTENT(IN)  :: Kp_rpc
      REAL,    INTENT(OUT) :: wt_! Aliases: wt
      REAL,    INTENT(OUT) :: Vdqref_pu_(2)! Aliases: Vdqref_pu
      REAL,    INTENT(OUT) :: f_pu_! Aliases: f_pu

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4, IT_5, IT_6
      INTEGER  IT_7, IT_8, IT_9, IT_10, IT_11
      INTEGER  IT_12, Freeze, Frz_q, Frz_d
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, Vdref_pu, Vqref_pu
      REAL     RT_9, RT_10, RT_11, RT_12(3)
      REAL     RT_13(3)

! Internal Variables
      LOGICAL  LVD1_1
      REAL     RVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 21
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 41
      IPGB      = NPGB
      NPGB      = NPGB + 7
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      wt_      = STOF(ISTOF + 4)
      f_pu_    = STOF(ISTOF + 22)
      RT_1     = STOF(ISTOF + 23)
      IT_1     = STOI(ISTOI + 7)
      RT_2     = STOF(ISTOF + 24)
      IT_2     = STOI(ISTOI + 8)
      RT_3     = STOF(ISTOF + 25)
      IT_3     = STOI(ISTOI + 9)
      RT_4     = STOF(ISTOF + 26)
      IT_4     = STOI(ISTOI + 10)
      RT_5     = STOF(ISTOF + 27)
      IT_5     = STOI(ISTOI + 11)
      RT_6     = STOF(ISTOF + 28)
      IT_6     = STOI(ISTOI + 12)
      RT_7     = STOF(ISTOF + 29)
      RT_8     = STOF(ISTOF + 30)
      Vdref_pu = STOF(ISTOF + 31)
      IT_7     = STOI(ISTOI + 13)
      Vqref_pu = STOF(ISTOF + 32)
      RT_9     = STOF(ISTOF + 33)
      RT_10    = STOF(ISTOF + 34)
      RT_11    = STOF(ISTOF + 35)
      IT_8     = STOI(ISTOI + 14)
      IT_9     = STOI(ISTOI + 15)
      IT_10    = STOI(ISTOI + 16)
      IT_11    = STOI(ISTOI + 17)
      IT_12    = STOI(ISTOI + 18)
      Freeze   = STOI(ISTOI + 19)
      Frz_q    = STOI(ISTOI + 20)
      Frz_d    = STOI(ISTOI + 21)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         Vdqref_pu_(IT_0) = STOF(ISTOF + 5 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_12(IT_0) = STOF(ISTOF + 35 + IT_0)
         RT_13(IT_0) = STOF(ISTOF + 38 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Primary_Controller.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[consti] Integer Constant 
      IT_7 = 0

! 120:[const] Real Constant 
      RT_7 = 1.0

! 160:[consti] Integer Constant 
      IT_11 = 0

! 170:[select] Two Input Selector 
      IF (RPC_Type .EQ. RTCI(NRTCI)) THEN
         IT_6 = Enable
      ELSE
         IT_6 = IT_11
      ENDIF
      NRTCI = NRTCI + 1
!

! 260:[const] Real Constant 
      Vqref_pu = 0.0

! 270:[pgb] Output Channel 'Vqref_pu'

      PGB(IPGB+1) = Vqref_pu

! 290:[datatap] Scalar/Array Tap 
      Frz_d = Frz(1)

! 300:[datatap] Scalar/Array Tap 
      Frz_q = Frz(2)

! 320:[consti] Integer Constant 
      IT_12 = 0

! 330:[select] Two Input Selector 
      IF (RPC_Type .EQ. RTCI(NRTCI)) THEN
         IT_5 = Enable
      ELSE
         IT_5 = IT_12
      ENDIF
      NRTCI = NRTCI + 1
!

! 340:[pgb] Output Channel 'VRT'

      PGB(IPGB+2) = REAL(VRT)

! 350:[consti] Integer Constant 
      IT_8 = 0

! 360:[select] Two Input Selector 
      IF (APC_Type .EQ. RTCI(NRTCI)) THEN
         IT_2 = Enable
      ELSE
         IT_2 = IT_8
      ENDIF
      NRTCI = NRTCI + 1
!

! 370:[APC_Droop] APC (Droop) 
      CALL APC_DroopDyn(P_pu, Pref_pu, RT_2, IT_2, Kp, wp, Fnom)


! 380:[consti] Integer Constant 
      IT_9 = 0

! 390:[select] Two Input Selector 
      IF (APC_Type .EQ. RTCI(NRTCI)) THEN
         IT_3 = Enable
      ELSE
         IT_3 = IT_9
      ENDIF
      NRTCI = NRTCI + 1
!

! 400:[consti] Integer Constant 
      IT_10 = 0

! 410:[select] Two Input Selector 
      IF (APC_Type .EQ. RTCI(NRTCI)) THEN
         IT_4 = Enable
      ELSE
         IT_4 = IT_10
      ENDIF
      NRTCI = NRTCI + 1
!

! 420:[emtconst] Commonly Used Constants (pi...) 
      RT_10 = TWO_PI

! 430:[mult] Multiplier 
      RT_11 = RT_10 * Fnom

! 440:[select] Two Input Selector 
      IF (RPC_Type .EQ. RTCI(NRTCI)) THEN
         IT_1 = Enable
      ELSE
         IT_1 = IT_7
      ENDIF
      NRTCI = NRTCI + 1
!

! 450:[RPC_Droop] RPC (Droop) 
      CALL RPC_DroopDyn(Q_pu, Qref_pu, RT_1, IT_1, Kq, wq)


! 460:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (Frz_d .NE. 0) .OR. (Frz_q .NE. 0) .OR. (VRT .NE. 0) ) THEN
        Freeze = 1
      ELSE
        Freeze = 0
      ENDIF

! 470:[RPC_PI] RPC (PI) 
      CALL RPC_PIDyn(Q_pu, Qref_pu, RT_5, IT_5, Freeze, Ki_rpc, Kp_rpc)


! 480:[APC_VSG] APC (VSG) 
      CALL APC_VSGDyn(P_pu, Pref_pu, RT_3, IT_3, Freeze, H_VSG, D_VSG, F&
     &nom)


! 490:[APC_GCVSG] APC (GCVSG) 
      CALL APC_GCVSGDyn(P_pu, Pref_pu, RT_4, IT_4, Freeze, tau, D, Fnom,&
     & SCRmax)


! 500:[RPC_RotorFluxModel] RPC (Rotor Flux Model) 
      CALL RPC_RotorFluxModelDyn(Q_pu, Qref_pu, RT_6, IT_6, Freeze, Ki_p&
     &si, Kp_psi, Fnom)


! 510:[datamerge] Merges data signals into an array 
      RT_12(1) = RT_2
      RT_12(2) = RT_3
      RT_12(3) = RT_4

! 520:[dynamic_datatap] Dynamic datatap 
      LVD1_1 = STORL(NSTORL)
      wt_ = 0.0
      IF ((APC_Type .GT. 0).AND.(APC_Type .LE. 3)) THEN
        wt_ = RT_12(APC_Type)
      ELSE
        IF (.NOT. LVD1_1) THEN   ! warn only once
          CALL EMTDC_MESSAGE(ICALL_NO,1897441946,1,1,"Dynamic datatap tr&
     &ying to access elements outside bounds")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1

! 530:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_9 = DERIV1(RVD1_1,wt_)
!

! 540:[datamerge] Merges data signals into an array 
      RT_13(1) = RT_1
      RT_13(2) = RT_6
      RT_13(3) = RT_5

! 550:[dynamic_datatap] Dynamic datatap 
      LVD1_1 = STORL(NSTORL)
      RT_8 = 0.0
      IF ((RPC_Type .GT. 0).AND.(RPC_Type .LE. 3)) THEN
        RT_8 = RT_13(RPC_Type)
      ELSE
        IF (.NOT. LVD1_1) THEN   ! warn only once
          CALL EMTDC_MESSAGE(ICALL_NO,874016334,1,1,"Dynamic datatap try&
     &ing to access elements outside bounds")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1

! 560:[div] Divider 
      IF (ABS(RT_11) .LT. 1.0E-100) THEN
         IF (RT_11 .LT. 0.0)  THEN
            f_pu_ = -1.0E100 * RT_9
         ELSE
            f_pu_ =  1.0E100 * RT_9
         ENDIF
      ELSE
         f_pu_ = RT_9 / RT_11
      ENDIF

! 570:[sumjct] Summing/Differencing Junctions 
      Vdref_pu = + RT_7 + RT_8

! 580:[pgb] Output Channel 'f_pu_'

      PGB(IPGB+3) = f_pu_

! 590:[pgb] Output Channel 'wt_'

      PGB(IPGB+4) = wt_

! 600:[datamerge] Merges data signals into an array 
      Vdqref_pu_(1) = Vdref_pu
      Vdqref_pu_(2) = Vqref_pu

! 610:[pgb] Output Channel 'Frz_q'

      PGB(IPGB+5) = REAL(Frz_q)

! 620:[pgb] Output Channel 'Frz_d'

      PGB(IPGB+6) = REAL(Frz_d)

! 630:[pgb] Output Channel 'Vdref_pu'

      PGB(IPGB+7) = Vdref_pu

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Q_pu
      STOF(ISTOF + 2) = P_pu
      STOF(ISTOF + 3) = Qref_pu
      STOF(ISTOF + 4) = wt_
      STOI(ISTOI + 1) = Enable
      STOF(ISTOF + 5) = Pref_pu
      STOI(ISTOI + 2) = VRT
      STOF(ISTOF + 8) = Fnom
      STOI(ISTOI + 5) = APC_Type
      STOI(ISTOI + 6) = RPC_Type
      STOF(ISTOF + 9) = SCRmax
      STOF(ISTOF + 10) = Kp
      STOF(ISTOF + 11) = H_VSG
      STOF(ISTOF + 12) = tau
      STOF(ISTOF + 13) = D
      STOF(ISTOF + 14) = D_VSG
      STOF(ISTOF + 15) = wp
      STOF(ISTOF + 16) = Kq
      STOF(ISTOF + 17) = wq
      STOF(ISTOF + 18) = Ki_psi
      STOF(ISTOF + 19) = Kp_psi
      STOF(ISTOF + 20) = Ki_rpc
      STOF(ISTOF + 21) = Kp_rpc
      STOF(ISTOF + 22) = f_pu_
      STOF(ISTOF + 23) = RT_1
      STOI(ISTOI + 7) = IT_1
      STOF(ISTOF + 24) = RT_2
      STOI(ISTOI + 8) = IT_2
      STOF(ISTOF + 25) = RT_3
      STOI(ISTOI + 9) = IT_3
      STOF(ISTOF + 26) = RT_4
      STOI(ISTOI + 10) = IT_4
      STOF(ISTOF + 27) = RT_5
      STOI(ISTOI + 11) = IT_5
      STOF(ISTOF + 28) = RT_6
      STOI(ISTOI + 12) = IT_6
      STOF(ISTOF + 29) = RT_7
      STOF(ISTOF + 30) = RT_8
      STOF(ISTOF + 31) = Vdref_pu
      STOI(ISTOI + 13) = IT_7
      STOF(ISTOF + 32) = Vqref_pu
      STOF(ISTOF + 33) = RT_9
      STOF(ISTOF + 34) = RT_10
      STOF(ISTOF + 35) = RT_11
      STOI(ISTOI + 14) = IT_8
      STOI(ISTOI + 15) = IT_9
      STOI(ISTOI + 16) = IT_10
      STOI(ISTOI + 17) = IT_11
      STOI(ISTOI + 18) = IT_12
      STOI(ISTOI + 19) = Freeze
      STOI(ISTOI + 20) = Frz_q
      STOI(ISTOI + 21) = Frz_d

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 5 + IT_0) = Vdqref_pu_(IT_0)
         STOI(ISTOI + 2 + IT_0) = Frz(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 35 + IT_0) = RT_12(IT_0)
         STOF(ISTOF + 38 + IT_0) = RT_13(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !wt_      is output
      !Vdqref_pu_ is output
      !f_pu_    is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Primary_ControllerOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    APC_DroopOut  ! APC (Droop)
!     SUBR    RPC_DroopOut  ! RPC (Droop)
!     SUBR    RPC_PIOut     ! RPC (PI)
!     SUBR    APC_VSGOut    ! APC (VSG)
!     SUBR    APC_GCVSGOut  ! APC (GCVSG)
!     SUBR    RPC_RotorFluxModelOut  ! RPC (Rotor Flux Model)

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  IT_7, IT_8, IT_9, IT_10, IT_11
      INTEGER  IT_12
      REAL     RT_7, Vqref_pu, RT_10

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 7
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_7     = STOF(ISTOF + 29)
      IT_7     = STOI(ISTOI + 13)
      Vqref_pu = STOF(ISTOF + 32)
      RT_10    = STOF(ISTOF + 34)
      IT_8     = STOI(ISTOI + 14)
      IT_9     = STOI(ISTOI + 15)
      IT_10    = STOI(ISTOI + 16)
      IT_11    = STOI(ISTOI + 17)
      IT_12    = STOI(ISTOI + 18)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Primary_Controller.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[consti] Integer Constant 

      IT_7 = 0

! 120:[const] Real Constant 

      RT_7 = 1.0

! 160:[consti] Integer Constant 

      IT_11 = 0

! 260:[const] Real Constant 

      Vqref_pu = 0.0

! 320:[consti] Integer Constant 

      IT_12 = 0

! 350:[consti] Integer Constant 

      IT_8 = 0

! 370:[APC_Droop] APC (Droop) 
      CALL APC_DroopOut()


! 380:[consti] Integer Constant 

      IT_9 = 0

! 400:[consti] Integer Constant 

      IT_10 = 0

! 420:[emtconst] Commonly Used Constants (pi...) 
      RT_10 = TWO_PI

! 450:[RPC_Droop] RPC (Droop) 
      CALL RPC_DroopOut()


! 470:[RPC_PI] RPC (PI) 
      CALL RPC_PIOut()


! 480:[APC_VSG] APC (VSG) 
      CALL APC_VSGOut()


! 490:[APC_GCVSG] APC (GCVSG) 
      CALL APC_GCVSGOut()


! 500:[RPC_RotorFluxModel] RPC (Rotor Flux Model) 
      CALL RPC_RotorFluxModelOut()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 29) = RT_7
      STOI(ISTOI + 13) = IT_7
      STOF(ISTOF + 32) = Vqref_pu
      STOF(ISTOF + 34) = RT_10
      STOI(ISTOI + 14) = IT_8
      STOI(ISTOI + 15) = IT_9
      STOI(ISTOI + 16) = IT_10
      STOI(ISTOI + 17) = IT_11
      STOI(ISTOI + 18) = IT_12


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Primary_ControllerDyn_Begin(Fnom, tau, D)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    APC_DroopDyn_Begin  ! APC (Droop)
!     SUBR    RPC_DroopDyn_Begin  ! RPC (Droop)
!     SUBR    RPC_PIDyn_Begin  ! RPC (PI)
!     SUBR    APC_VSGDyn_Begin  ! APC (VSG)
!     SUBR    APC_GCVSGDyn_Begin  ! APC (GCVSG)
!     SUBR    RPC_RotorFluxModelDyn_Begin  ! RPC (Rotor Flux Model)

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Fnom, tau, D

! Electrical Node Indices

! Control Signals
      INTEGER  IT_7, IT_8, IT_9, IT_10, IT_11
      INTEGER  IT_12
      REAL     RT_7, Vqref_pu, RT_10

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[consti] Integer Constant 
      IT_7 = 0

! 120:[const] Real Constant 
      RT_7 = 1.0

! 160:[consti] Integer Constant 
      IT_11 = 0

! 170:[select] Two Input Selector 
      RTCI(NRTCI) = 2
      NRTCI = NRTCI + 1

! 260:[const] Real Constant 
      Vqref_pu = 0.0

! 270:[pgb] Output Channel 'Vqref_pu'

! 290:[datatap] Scalar/Array Tap 

! 300:[datatap] Scalar/Array Tap 

! 320:[consti] Integer Constant 
      IT_12 = 0

! 330:[select] Two Input Selector 
      RTCI(NRTCI) = 3
      NRTCI = NRTCI + 1

! 340:[pgb] Output Channel 'VRT'

! 350:[consti] Integer Constant 
      IT_8 = 0

! 360:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 370:[APC_Droop] APC (Droop) 
      CALL APC_DroopDyn_Begin()


! 380:[consti] Integer Constant 
      IT_9 = 0

! 390:[select] Two Input Selector 
      RTCI(NRTCI) = 2
      NRTCI = NRTCI + 1

! 400:[consti] Integer Constant 
      IT_10 = 0

! 410:[select] Two Input Selector 
      RTCI(NRTCI) = 3
      NRTCI = NRTCI + 1

! 420:[emtconst] Commonly Used Constants (pi...) 
      RT_10 = TWO_PI

! 430:[mult] Multiplier 

! 440:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 450:[RPC_Droop] RPC (Droop) 
      CALL RPC_DroopDyn_Begin()


! 470:[RPC_PI] RPC (PI) 
      CALL RPC_PIDyn_Begin()


! 480:[APC_VSG] APC (VSG) 
      CALL APC_VSGDyn_Begin()


! 490:[APC_GCVSG] APC (GCVSG) 
      CALL APC_GCVSGDyn_Begin(tau, D)


! 500:[RPC_RotorFluxModel] RPC (Rotor Flux Model) 
      CALL RPC_RotorFluxModelDyn_Begin()


! 510:[datamerge] Merges data signals into an array 

! 520:[dynamic_datatap] Dynamic datatap 

! 530:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 540:[datamerge] Merges data signals into an array 

! 550:[dynamic_datatap] Dynamic datatap 

! 560:[div] Divider 

! 570:[sumjct] Summing/Differencing Junctions 

! 580:[pgb] Output Channel 'f_pu_'

! 590:[pgb] Output Channel 'wt_'

! 600:[datamerge] Merges data signals into an array 

! 610:[pgb] Output Channel 'Frz_q'

! 620:[pgb] Output Channel 'Frz_d'

! 630:[pgb] Output Channel 'Vdref_pu'

      RETURN
      END

!=======================================================================

      SUBROUTINE Primary_ControllerOut_Begin(Fnom, tau, D)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    APC_DroopOut_Begin  ! APC (Droop)
!     SUBR    RPC_DroopOut_Begin  ! RPC (Droop)
!     SUBR    RPC_PIOut_Begin  ! RPC (PI)
!     SUBR    APC_VSGOut_Begin  ! APC (VSG)
!     SUBR    APC_GCVSGOut_Begin  ! APC (GCVSG)
!     SUBR    RPC_RotorFluxModelOut_Begin  ! RPC (Rotor Flux Model)

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Fnom, tau, D

! Electrical Node Indices

! Control Signals
      INTEGER  IT_7, IT_8, IT_9, IT_10, IT_11
      INTEGER  IT_12
      REAL     RT_7, Vqref_pu, RT_10

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[consti] Integer Constant 
      IT_7 = 0

! 120:[const] Real Constant 
      RT_7 = 1.0

! 160:[consti] Integer Constant 
      IT_11 = 0

! 260:[const] Real Constant 
      Vqref_pu = 0.0

! 320:[consti] Integer Constant 
      IT_12 = 0

! 350:[consti] Integer Constant 
      IT_8 = 0

! 370:[APC_Droop] APC (Droop) 
      CALL APC_DroopOut_Begin()


! 380:[consti] Integer Constant 
      IT_9 = 0

! 400:[consti] Integer Constant 
      IT_10 = 0

! 420:[emtconst] Commonly Used Constants (pi...) 
      RT_10 = TWO_PI

! 450:[RPC_Droop] RPC (Droop) 
      CALL RPC_DroopOut_Begin()


! 470:[RPC_PI] RPC (PI) 
      CALL RPC_PIOut_Begin()


! 480:[APC_VSG] APC (VSG) 
      CALL APC_VSGOut_Begin()


! 490:[APC_GCVSG] APC (GCVSG) 
      CALL APC_GCVSGOut_Begin(tau, D)


! 500:[RPC_RotorFluxModel] RPC (Rotor Flux Model) 
      CALL RPC_RotorFluxModelOut_Begin()


      RETURN
      END

