!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Virtual_Impedance
! Description   : Virtual Impedance
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Virtual_ImpedanceDyn(Idq_pu, Vdqref_pu_, Vdqref_pu__,  &
     &   Enable, R_VI_pu, L_VI_pu)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable
      REAL,    INTENT(IN)  :: Idq_pu(2)
      REAL,    INTENT(IN)  :: Vdqref_pu_(2)
      REAL,    INTENT(IN)  :: R_VI_pu, L_VI_pu
      REAL,    INTENT(OUT) :: Vdqref_pu__(2)! Aliases: Vdqref_pu

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, Id_pu
      REAL     Iq_pu, Vdrefpu, Vqrefpu
      REAL     Vdref_pu_VI, Vdref_pu, Vqref_pu_VI
      REAL     Vqref_pu

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 1
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 20
      IPGB      = NPGB
      NPGB      = NPGB + 6
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 9)
      RT_2     = STOF(ISTOF + 10)
      RT_3     = STOF(ISTOF + 11)
      RT_4     = STOF(ISTOF + 12)
      Id_pu    = STOF(ISTOF + 13)
      Iq_pu    = STOF(ISTOF + 14)
      Vdrefpu  = STOF(ISTOF + 15)
      Vqrefpu  = STOF(ISTOF + 16)
      Vdref_pu_VI = STOF(ISTOF + 17)
      Vdref_pu = STOF(ISTOF + 18)
      Vqref_pu_VI = STOF(ISTOF + 19)
      Vqref_pu = STOF(ISTOF + 20)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         Vdqref_pu__(IT_0) = STOF(ISTOF + 4 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Virtual_Impedance.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 60:[datatap] Scalar/Array Tap 
      Vdref_pu = Vdqref_pu_(1)

! 70:[datatap] Scalar/Array Tap 
      Vqref_pu = Vdqref_pu_(2)

! 80:[datatap] Scalar/Array Tap 
      Id_pu = Idq_pu(1)

! 90:[datatap] Scalar/Array Tap 
      Iq_pu = Idq_pu(2)

! 100:[gain] Gain Block 
!  Gain
      RT_3 = R_VI_pu * Iq_pu

! 110:[gain] Gain Block 
!  Gain
      RT_2 = R_VI_pu * Id_pu

! 120:[gain] Gain Block 
!  Gain
      RT_1 = L_VI_pu * Iq_pu

! 130:[gain] Gain Block 
!  Gain
      RT_4 = L_VI_pu * Id_pu

! 140:[sumjct] Summing/Differencing Junctions 
      Vqref_pu_VI = - RT_3 + Vqref_pu - RT_4

! 150:[sumjct] Summing/Differencing Junctions 
      Vdref_pu_VI = + RT_1 + Vdref_pu - RT_2

! 160:[select] Two Input Selector 
      IF (Enable .EQ. RTCI(NRTCI)) THEN
         Vqrefpu = Vqref_pu_VI
      ELSE
         Vqrefpu = Vqref_pu
      ENDIF
      NRTCI = NRTCI + 1
!

! 170:[select] Two Input Selector 
      IF (Enable .EQ. RTCI(NRTCI)) THEN
         Vdrefpu = Vdref_pu_VI
      ELSE
         Vdrefpu = Vdref_pu
      ENDIF
      NRTCI = NRTCI + 1
!

! 180:[datamerge] Merges data signals into an array 
      Vdqref_pu__(1) = Vdrefpu
      Vdqref_pu__(2) = Vqrefpu

! 200:[pgb] Output Channel 'Vqrefpu'

      PGB(IPGB+1) = Vqrefpu

! 210:[pgb] Output Channel 'Iq_pu'

      PGB(IPGB+2) = Iq_pu

! 220:[pgb] Output Channel 'Id_pu'

      PGB(IPGB+3) = Id_pu

! 230:[pgb] Output Channel 'Vqref_pu'

      PGB(IPGB+4) = Vqref_pu

! 240:[pgb] Output Channel 'Vdrefpu'

      PGB(IPGB+5) = Vdrefpu

! 250:[pgb] Output Channel 'Vdref_pu'

      PGB(IPGB+6) = Vdref_pu

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = Enable
      STOF(ISTOF + 7) = R_VI_pu
      STOF(ISTOF + 8) = L_VI_pu
      STOF(ISTOF + 9) = RT_1
      STOF(ISTOF + 10) = RT_2
      STOF(ISTOF + 11) = RT_3
      STOF(ISTOF + 12) = RT_4
      STOF(ISTOF + 13) = Id_pu
      STOF(ISTOF + 14) = Iq_pu
      STOF(ISTOF + 15) = Vdrefpu
      STOF(ISTOF + 16) = Vqrefpu
      STOF(ISTOF + 17) = Vdref_pu_VI
      STOF(ISTOF + 18) = Vdref_pu
      STOF(ISTOF + 19) = Vqref_pu_VI
      STOF(ISTOF + 20) = Vqref_pu

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 0 + IT_0) = Idq_pu(IT_0)
         STOF(ISTOF + 2 + IT_0) = Vdqref_pu_(IT_0)
         STOF(ISTOF + 4 + IT_0) = Vdqref_pu__(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Vdqref_pu__ is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Virtual_ImpedanceOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 6
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------



!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Virtual_Impedance.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------



!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Virtual_ImpedanceDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 60:[datatap] Scalar/Array Tap 

! 70:[datatap] Scalar/Array Tap 

! 80:[datatap] Scalar/Array Tap 

! 90:[datatap] Scalar/Array Tap 

! 100:[gain] Gain Block 

! 110:[gain] Gain Block 

! 120:[gain] Gain Block 

! 130:[gain] Gain Block 

! 140:[sumjct] Summing/Differencing Junctions 

! 150:[sumjct] Summing/Differencing Junctions 

! 160:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 170:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 180:[datamerge] Merges data signals into an array 

! 200:[pgb] Output Channel 'Vqrefpu'

! 210:[pgb] Output Channel 'Iq_pu'

! 220:[pgb] Output Channel 'Id_pu'

! 230:[pgb] Output Channel 'Vqref_pu'

! 240:[pgb] Output Channel 'Vdrefpu'

! 250:[pgb] Output Channel 'Vdref_pu'

      RETURN
      END

!=======================================================================

      SUBROUTINE Virtual_ImpedanceOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


      RETURN
      END

