!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : APC_GCVSG
! Description   : APC (GCVSG)
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE APC_GCVSGDyn(P_pu, Pref_pu, wt_, Enable, Frz, tau, D,  &
     &   Fnom, SCRmax)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    DERIV1        ! Derivative Function
!     SUBR    PI_AntiWindUpDyn  ! 
      REAL    LDLGPOLE      ! Lead-Lag Function
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, Frz
      REAL,    INTENT(IN)  :: P_pu, Pref_pu, tau
      REAL,    INTENT(IN)  :: D, Fnom, SCRmax
      REAL,    INTENT(OUT) :: wt_! Aliases: wt

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, RT_11
      REAL     RT_12, RT_13, RT_14, RT_15, a, b
      REAL     c, DeFrz

! Internal Variables
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 6
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 26
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      wt_      = STOF(ISTOF + 3)
      RT_1     = STOF(ISTOF + 8)
      RT_2     = STOF(ISTOF + 9)
      IT_1     = STOI(ISTOI + 3)
      RT_3     = STOF(ISTOF + 10)
      RT_4     = STOF(ISTOF + 11)
      RT_5     = STOF(ISTOF + 12)
      RT_6     = STOF(ISTOF + 13)
      RT_7     = STOF(ISTOF + 14)
      RT_8     = STOF(ISTOF + 15)
      IT_2     = STOI(ISTOI + 4)
      RT_9     = STOF(ISTOF + 16)
      RT_10    = STOF(ISTOF + 17)
      RT_11    = STOF(ISTOF + 18)
      RT_12    = STOF(ISTOF + 19)
      RT_13    = STOF(ISTOF + 20)
      RT_14    = STOF(ISTOF + 21)
      RT_15    = STOF(ISTOF + 22)
      a        = STOF(ISTOF + 23)
      b        = STOF(ISTOF + 24)
      c        = STOF(ISTOF + 25)
      IT_3     = STOI(ISTOI + 5)
      IT_4     = STOI(ISTOI + 6)
      DeFrz    = STOF(ISTOF + 26)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'APC_GCVSG.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[consti] Integer Constant 
      IT_2 = 1

! 70:[inv] Interpolated Logic Inverter 
      IF (IT_2 .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 80:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = TWO_PI

! 120:[consti] Integer Constant 
      IT_3 = 1

! 130:[sumjct] Summing/Differencing Junctions 
      IT_4 = - Frz + IT_3

! 140:[unity] Type/Shape conversion block 
! integer -> real
      DeFrz = REAL(IT_4)

! 150:[GVSG_CGVSC_Gains] GVSG/CGVSG Gains 
!!!! GVSG/CGVSG Gains
!!!! Scripted by MHRavanji
!!!! moh.ravanji@gmail.com
!!!! Date Modified: 2022-06-09

        beta = tau**2 * ((SCRmax**2)/(D**2 * tau) - 1)**0.333333333
        gamma = ((SCRmax**2)/(D**2 * tau) - 1)**(-0.333333333)

        a = tau
        b = (beta*gamma)/(beta + gamma - tau)
        c = (beta + gamma - tau)*D

! 160:[mult] Multiplier 
      RT_8 = RT_7 * Fnom

! 170:[gain] Gain Block 
!  Gain
      RT_13 = a * P_pu

! 180:[derivative] Derivative with a time constant 
!  Derivative
      RVD1_1 = RTCF(NRTCF) ! Time Constant
      NRTCF = NRTCF + 1
      RT_14 = DERIV1(RVD1_1,RT_13)
!

! 190:[ratelimit] Rate Limiter 
!  Rate_Limiter
      CALL RATE_LIMITER(100.0,100.0,RT_14,RT_15)

! 200:[sumjct] Summing/Differencing Junctions 
      RT_5 = + RT_15 + P_pu

! 210:[sumjct] Summing/Differencing Junctions 
      RT_6 = + Pref_pu - RT_5

! 220:[gain] Gain Block 
!  Gain
      RT_10 = D * RT_11

! 230:[sumjct] Summing/Differencing Junctions 
      RT_9 = - RT_10 + RT_6

! 240:[gain] Gain Block 
!  Gain
      RT_1 = REAL(Enable) * RT_9

! 250:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn(RT_1, RT_2, Frz, IT_1, 0.0, c, 1.0, 10000000&
     &000.0, -10000000000.0)


! 260:[leadlag] Lead-Lag 
!  Lead_Lag
      RT_11 = LDLGPOLE(0,1,0,a,b,1.0,RT_2,0.0,-1.0E20,1.0E20)

! 270:[gain] Gain Block 
!  Gain
      RT_12 = DeFrz * RT_11

! 280:[sumjct] Summing/Differencing Junctions 
      RT_4 = + RT_8 + RT_12

! 290:[gain] Gain Block 
!  Gain
      RT_3 = REAL(Enable) * RT_4

! 300:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_3
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      wt_ = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -10000000000.0, 100000&
     &00000.0, RVD2_2, RVD2_1)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = P_pu
      STOF(ISTOF + 2) = Pref_pu
      STOF(ISTOF + 3) = wt_
      STOI(ISTOI + 1) = Enable
      STOI(ISTOI + 2) = Frz
      STOF(ISTOF + 4) = tau
      STOF(ISTOF + 5) = D
      STOF(ISTOF + 6) = Fnom
      STOF(ISTOF + 7) = SCRmax
      STOF(ISTOF + 8) = RT_1
      STOF(ISTOF + 9) = RT_2
      STOI(ISTOI + 3) = IT_1
      STOF(ISTOF + 10) = RT_3
      STOF(ISTOF + 11) = RT_4
      STOF(ISTOF + 12) = RT_5
      STOF(ISTOF + 13) = RT_6
      STOF(ISTOF + 14) = RT_7
      STOF(ISTOF + 15) = RT_8
      STOI(ISTOI + 4) = IT_2
      STOF(ISTOF + 16) = RT_9
      STOF(ISTOF + 17) = RT_10
      STOF(ISTOF + 18) = RT_11
      STOF(ISTOF + 19) = RT_12
      STOF(ISTOF + 20) = RT_13
      STOF(ISTOF + 21) = RT_14
      STOF(ISTOF + 22) = RT_15
      STOF(ISTOF + 23) = a
      STOF(ISTOF + 24) = b
      STOF(ISTOF + 25) = c
      STOI(ISTOI + 5) = IT_3
      STOI(ISTOI + 6) = IT_4
      STOF(ISTOF + 26) = DeFrz


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !wt_      is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE APC_GCVSGOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  IT_2, IT_3
      REAL     RT_7

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_7     = STOF(ISTOF + 14)
      IT_2     = STOI(ISTOI + 4)
      IT_3     = STOI(ISTOI + 5)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'APC_GCVSG.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[consti] Integer Constant 

      IT_2 = 1

! 80:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = TWO_PI

! 120:[consti] Integer Constant 

      IT_3 = 1

! 250:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 14) = RT_7
      STOI(ISTOI + 4) = IT_2
      STOI(ISTOI + 5) = IT_3


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE APC_GCVSGDyn_Begin(tau, D)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: tau, D

! Electrical Node Indices

! Control Signals
      INTEGER  IT_2, IT_3
      REAL     RT_7

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[consti] Integer Constant 
      IT_2 = 1

! 70:[inv] Interpolated Logic Inverter 

! 80:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = TWO_PI

! 120:[consti] Integer Constant 
      IT_3 = 1

! 130:[sumjct] Summing/Differencing Junctions 

! 140:[unity] Type/Shape conversion block 

! 150:[GVSG_CGVSC_Gains] GVSG/CGVSG Gains 

! 160:[mult] Multiplier 

! 170:[gain] Gain Block 

! 180:[derivative] Derivative with a time constant 
      RTCF(NRTCF) = 1.0
      NRTCF = NRTCF + 1

! 190:[ratelimit] Rate Limiter 

! 200:[sumjct] Summing/Differencing Junctions 

! 210:[sumjct] Summing/Differencing Junctions 

! 220:[gain] Gain Block 

! 230:[sumjct] Summing/Differencing Junctions 

! 240:[gain] Gain Block 

! 250:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn_Begin()


! 260:[leadlag] Lead-Lag 

! 270:[gain] Gain Block 

! 280:[sumjct] Summing/Differencing Junctions 

! 290:[gain] Gain Block 

! 300:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

      RETURN
      END

!=======================================================================

      SUBROUTINE APC_GCVSGOut_Begin(tau, D)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: tau, D

! Electrical Node Indices

! Control Signals
      INTEGER  IT_2, IT_3
      REAL     RT_7

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[consti] Integer Constant 
      IT_2 = 1

! 80:[emtconst] Commonly Used Constants (pi...) 
      RT_7 = TWO_PI

! 120:[consti] Integer Constant 
      IT_3 = 1

! 250:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut_Begin()


      RETURN
      END

