!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : APC_VSG
! Description   : APC (VSG)
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE APC_VSGDyn(P_pu, Pref_pu, wt_, Enable, Frz, H_VSG,     &
     &   D_VSG, Fnom)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpDyn  ! 
      REAL    EMTDC_XINT    ! 'Integrator /w Interpolation'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, Frz
      REAL,    INTENT(IN)  :: P_pu, Pref_pu
      REAL,    INTENT(IN)  :: H_VSG, D_VSG, Fnom
      REAL,    INTENT(OUT) :: wt_! Aliases: wt

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, T_VSG, RT_9, RT_10
      REAL     RT_11, RT_12, RT_13, DeFrz

! Internal Variables
      REAL     RVD1_1, RVD2_1(2), RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 6
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 21
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      wt_      = STOF(ISTOF + 3)
      RT_1     = STOF(ISTOF + 7)
      RT_2     = STOF(ISTOF + 8)
      IT_1     = STOI(ISTOI + 3)
      RT_3     = STOF(ISTOF + 9)
      RT_4     = STOF(ISTOF + 10)
      RT_5     = STOF(ISTOF + 11)
      RT_6     = STOF(ISTOF + 12)
      RT_7     = STOF(ISTOF + 13)
      IT_2     = STOI(ISTOI + 4)
      RT_8     = STOF(ISTOF + 14)
      T_VSG    = STOF(ISTOF + 15)
      RT_9     = STOF(ISTOF + 16)
      RT_10    = STOF(ISTOF + 17)
      RT_11    = STOF(ISTOF + 18)
      RT_12    = STOF(ISTOF + 19)
      RT_13    = STOF(ISTOF + 20)
      IT_3     = STOI(ISTOI + 5)
      IT_4     = STOI(ISTOI + 6)
      DeFrz    = STOF(ISTOF + 21)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'APC_VSG.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 
      RT_6 = TWO_PI

! 60:[consti] Integer Constant 
      IT_2 = 1

! 70:[inv] Interpolated Logic Inverter 
      IF (IT_2 .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 80:[sumjct] Summing/Differencing Junctions 
      RT_5 = + Pref_pu - P_pu

! 100:[gain] Gain Block 
!  Gain
      T_VSG = 2.0 * H_VSG

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_13 = TWO_PI

! 140:[consti] Integer Constant 
      IT_3 = 1

! 150:[sumjct] Summing/Differencing Junctions 
      IT_4 = - Frz + IT_3

! 160:[unity] Type/Shape conversion block 
! integer -> real
      DeFrz = REAL(IT_4)

! 170:[mult] Multiplier 
      RT_7 = RT_6 * Fnom

! 180:[mult] Multiplier 
      RT_12 = RT_13 * Fnom

! 190:[gain] Gain Block 
!  Gain
      RT_9 = D_VSG * RT_10

! 200:[sumjct] Summing/Differencing Junctions 
      RT_8 = - RT_9 + RT_5

! 210:[gain] Gain Block 
!  Gain
      RT_1 = REAL(Enable) * RT_8

! 220:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn(RT_1, RT_2, Frz, IT_1, 0.0, T_VSG, 1.0, 1000&
     &0000000.0, -10000000000.0)


! 230:[mult] Multiplier 
      RT_10 = RT_2 * RT_12

! 240:[gain] Gain Block 
!  Gain
      RT_11 = DeFrz * RT_10

! 250:[sumjct] Summing/Differencing Junctions 
      RT_4 = + RT_7 + RT_11

! 260:[gain] Gain Block 
!  Gain
      RT_3 = REAL(Enable) * RT_4

! 270:[integral] Interpolated Integrator 
      RVD1_1 = RTCF(NRTCF) ! Initial Output
      NRTCF = NRTCF + 1
      RVD2_1(1) = RT_3
      RVD2_1(2) = 0.0
      RVD2_2(1) = 0.0
      RVD2_2(2) = 0.0
      wt_ = EMTDC_XINT(0, 0, 0, RVD1_1, 1.0, 0.0, -10000000000.0, 100000&
     &00000.0, RVD2_2, RVD2_1)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = P_pu
      STOF(ISTOF + 2) = Pref_pu
      STOF(ISTOF + 3) = wt_
      STOI(ISTOI + 1) = Enable
      STOI(ISTOI + 2) = Frz
      STOF(ISTOF + 4) = H_VSG
      STOF(ISTOF + 5) = D_VSG
      STOF(ISTOF + 6) = Fnom
      STOF(ISTOF + 7) = RT_1
      STOF(ISTOF + 8) = RT_2
      STOI(ISTOI + 3) = IT_1
      STOF(ISTOF + 9) = RT_3
      STOF(ISTOF + 10) = RT_4
      STOF(ISTOF + 11) = RT_5
      STOF(ISTOF + 12) = RT_6
      STOF(ISTOF + 13) = RT_7
      STOI(ISTOI + 4) = IT_2
      STOF(ISTOF + 14) = RT_8
      STOF(ISTOF + 15) = T_VSG
      STOF(ISTOF + 16) = RT_9
      STOF(ISTOF + 17) = RT_10
      STOF(ISTOF + 18) = RT_11
      STOF(ISTOF + 19) = RT_12
      STOF(ISTOF + 20) = RT_13
      STOI(ISTOI + 5) = IT_3
      STOI(ISTOI + 6) = IT_4
      STOF(ISTOF + 21) = DeFrz


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !wt_      is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE APC_VSGOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  IT_2, IT_3
      REAL     RT_6, RT_13

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_6     = STOF(ISTOF + 12)
      IT_2     = STOI(ISTOI + 4)
      RT_13    = STOF(ISTOF + 20)
      IT_3     = STOI(ISTOI + 5)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'APC_VSG.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 
      RT_6 = TWO_PI

! 60:[consti] Integer Constant 

      IT_2 = 1

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_13 = TWO_PI

! 140:[consti] Integer Constant 

      IT_3 = 1

! 220:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 12) = RT_6
      STOI(ISTOI + 4) = IT_2
      STOF(ISTOF + 20) = RT_13
      STOI(ISTOI + 5) = IT_3


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE APC_VSGDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_2, IT_3
      REAL     RT_6, RT_13

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 
      RT_6 = TWO_PI

! 60:[consti] Integer Constant 
      IT_2 = 1

! 70:[inv] Interpolated Logic Inverter 

! 80:[sumjct] Summing/Differencing Junctions 

! 100:[gain] Gain Block 

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_13 = TWO_PI

! 140:[consti] Integer Constant 
      IT_3 = 1

! 150:[sumjct] Summing/Differencing Junctions 

! 160:[unity] Type/Shape conversion block 

! 170:[mult] Multiplier 

! 180:[mult] Multiplier 

! 190:[gain] Gain Block 

! 200:[sumjct] Summing/Differencing Junctions 

! 210:[gain] Gain Block 

! 220:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn_Begin()


! 230:[mult] Multiplier 

! 240:[gain] Gain Block 

! 250:[sumjct] Summing/Differencing Junctions 

! 260:[gain] Gain Block 

! 270:[integral] Interpolated Integrator 
      RTCF(NRTCF) = 0.0
      NRTCF = NRTCF + 1

      RETURN
      END

!=======================================================================

      SUBROUTINE APC_VSGOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_2, IT_3
      REAL     RT_6, RT_13

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[emtconst] Commonly Used Constants (pi...) 
      RT_6 = TWO_PI

! 60:[consti] Integer Constant 
      IT_2 = 1

! 120:[emtconst] Commonly Used Constants (pi...) 
      RT_13 = TWO_PI

! 140:[consti] Integer Constant 
      IT_3 = 1

! 220:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut_Begin()


      RETURN
      END

