!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : AVR
! Description   : AVR
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE AVRDyn(Vref_pu, Vpcc_pu, Qref_pu_, Enable, Q_pu,       &
     &   Freeze, Kp_AVR, Ki_AVR, n_AVR, Qmax_pu, Qmin_pu)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpDyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, Freeze
      REAL,    INTENT(IN)  :: Vref_pu, Vpcc_pu
      REAL,    INTENT(IN)  :: Q_pu, Kp_AVR
      REAL,    INTENT(IN)  :: Ki_AVR, n_AVR
      REAL,    INTENT(IN)  :: Qmax_pu, Qmin_pu
      REAL,    INTENT(OUT) :: Qref_pu_! Aliases: Qref_pu

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2
      REAL     RT_1, RT_2, Ti_AVR, RT_3, RT_4
      REAL     RT_5, RT_6, Kaw_AVR

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF                        ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 4
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 17
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Qref_pu_ = STOF(ISTOF + 3)
      RT_1     = STOF(ISTOF + 10)
      IT_1     = STOI(ISTOI + 3)
      RT_2     = STOF(ISTOF + 11)
      IT_2     = STOI(ISTOI + 4)
      Ti_AVR   = STOF(ISTOF + 12)
      RT_3     = STOF(ISTOF + 13)
      RT_4     = STOF(ISTOF + 14)
      RT_5     = STOF(ISTOF + 15)
      RT_6     = STOF(ISTOF + 16)
      Kaw_AVR  = STOF(ISTOF + 17)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'AVR.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[consti] Integer Constant 
      IT_2 = 1

! 60:[inv] Interpolated Logic Inverter 
      IF (IT_2 .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 70:[sumjct] Summing/Differencing Junctions 
      RT_4 = + Vref_pu - Vpcc_pu

! 110:[const] Real Constant 
      RT_3 = 1.0

! 150:[gain] Gain Block 
!  Gain
      RT_5 = n_AVR * Q_pu

! 160:[div] Divider 
      IF (ABS(Ki_AVR) .LT. 1.0E-100) THEN
         IF (Ki_AVR .LT. 0.0)  THEN
            Ti_AVR = -1.0E100 * RT_3
         ELSE
            Ti_AVR =  1.0E100 * RT_3
         ENDIF
      ELSE
         Ti_AVR = RT_3 / Ki_AVR
      ENDIF

! 170:[div] Divider 
      IF (ABS(Kp_AVR) .LT. 1.0E-100) THEN
         IF (Kp_AVR .LT. 0.0)  THEN
            RT_6 = -1.0E100 * Ki_AVR
         ELSE
            RT_6 =  1.0E100 * Ki_AVR
         ENDIF
      ELSE
         RT_6 = Ki_AVR / Kp_AVR
      ENDIF

! 180:[gain] Gain Block 
!  Gain
      Kaw_AVR = 2.0 * RT_6

! 190:[sumjct] Summing/Differencing Junctions 
      RT_2 = + RT_4 - RT_5

! 200:[gain] Gain Block 
!  Gain
      RT_1 = REAL(Enable) * RT_2

! 210:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn(RT_1, Qref_pu_, Freeze, IT_1, Kp_AVR, Ti_AVR&
     &, Kaw_AVR, Qmax_pu, Qmin_pu)


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Vref_pu
      STOF(ISTOF + 2) = Vpcc_pu
      STOF(ISTOF + 3) = Qref_pu_
      STOI(ISTOI + 1) = Enable
      STOF(ISTOF + 4) = Q_pu
      STOI(ISTOI + 2) = Freeze
      STOF(ISTOF + 5) = Kp_AVR
      STOF(ISTOF + 6) = Ki_AVR
      STOF(ISTOF + 7) = n_AVR
      STOF(ISTOF + 8) = Qmax_pu
      STOF(ISTOF + 9) = Qmin_pu
      STOF(ISTOF + 10) = RT_1
      STOI(ISTOI + 3) = IT_1
      STOF(ISTOF + 11) = RT_2
      STOI(ISTOI + 4) = IT_2
      STOF(ISTOF + 12) = Ti_AVR
      STOF(ISTOF + 13) = RT_3
      STOF(ISTOF + 14) = RT_4
      STOF(ISTOF + 15) = RT_5
      STOF(ISTOF + 16) = RT_6
      STOF(ISTOF + 17) = Kaw_AVR


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Qref_pu_ is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE AVROut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  IT_2
      REAL     RT_3

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      IT_2     = STOI(ISTOI + 4)
      RT_3     = STOF(ISTOF + 13)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'AVR.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[consti] Integer Constant 

      IT_2 = 1

! 110:[const] Real Constant 

      RT_3 = 1.0

! 210:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 4) = IT_2
      STOF(ISTOF + 13) = RT_3


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE AVRDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_2
      REAL     RT_3

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[consti] Integer Constant 
      IT_2 = 1

! 60:[inv] Interpolated Logic Inverter 

! 70:[sumjct] Summing/Differencing Junctions 

! 110:[const] Real Constant 
      RT_3 = 1.0

! 150:[gain] Gain Block 

! 160:[div] Divider 

! 170:[div] Divider 

! 180:[gain] Gain Block 

! 190:[sumjct] Summing/Differencing Junctions 

! 200:[gain] Gain Block 

! 210:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn_Begin()


      RETURN
      END

!=======================================================================

      SUBROUTINE AVROut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_2
      REAL     RT_3

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[consti] Integer Constant 
      IT_2 = 1

! 110:[const] Real Constant 
      RT_3 = 1.0

! 210:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut_Begin()


      RETURN
      END

