!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Battery
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE BatteryDyn(Pcmd_pu, Qcmd_pu, Enable, VRT, APC, RPC,    &
     &   Fnom, Sbase1, Vac_nom, Vdc_nom, L_GSC_pu, R_GSC_pu, C_GSC_pu,  &
     &   Rc_GSC_pu, Freq_PWM_GSC, Pblst_pu, SCRmax, Ppcc_pu_, Qpcc_pu_, &
     &   Vpcc_pu_, Fpcc_pu_, Vpcc_, Ipcc_)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    UCDyn         ! Unit Controller
!     SUBR    Parameters_FiltersDyn  ! 
!     SUBR    ConvBridge_IGBTDyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, VRT, APC
      INTEGER, INTENT(IN)  :: RPC
      REAL,    INTENT(IN)  :: Pcmd_pu, Qcmd_pu
      REAL,    INTENT(IN)  :: Fnom, Sbase1
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu, Rc_GSC_pu
      REAL,    INTENT(IN)  :: Freq_PWM_GSC
      REAL,    INTENT(IN)  :: Pblst_pu, SCRmax
      REAL,    INTENT(OUT) :: Ppcc_pu_! Aliases: Ppcc_pu
      REAL,    INTENT(OUT) :: Qpcc_pu_! Aliases: Qpcc_pu
      REAL,    INTENT(OUT) :: Vpcc_pu_! Aliases: Vpcc_pu
      REAL,    INTENT(OUT) :: Fpcc_pu_! Aliases: Fpcc_pu
      REAL,    INTENT(OUT) :: Vpcc_(3)! Aliases: Vpcc
      REAL,    INTENT(OUT) :: Ipcc_(3)! Aliases: Ipcc

! Electrical Node Indices

! Control Signals
      REAL     L_GSC, R_GSC, C_GSC, Rc_GSC
      REAL     Iabc_B0(3), Vabc_B0(3), Sig_GSC(5)
      REAL     Iabc_B1(3), RT_1, Fpcc, RT_2
      REAL     Vdc_kV, Igabc_pu(3), Vgabc_pu(3)
      REAL     RT_3, RT_4, Vabc_B1(3)
      REAL     Vabc_B0_rms, Iabc_B0_rms

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 4
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 58
      IPGB      = NPGB
      NPGB      = NPGB + 10
      INODE     = NNODE + 2
      NNODE     = NNODE + 32
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 32
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Ppcc_pu_ = STOF(ISTOF + 14)
      Qpcc_pu_ = STOF(ISTOF + 15)
      Vpcc_pu_ = STOF(ISTOF + 16)
      Fpcc_pu_ = STOF(ISTOF + 17)
      L_GSC    = STOF(ISTOF + 24)
      R_GSC    = STOF(ISTOF + 25)
      C_GSC    = STOF(ISTOF + 26)
      Rc_GSC   = STOF(ISTOF + 27)
      RT_1     = STOF(ISTOF + 42)
      Fpcc     = STOF(ISTOF + 43)
      RT_2     = STOF(ISTOF + 44)
      Vdc_kV   = STOF(ISTOF + 45)
      RT_3     = STOF(ISTOF + 52)
      RT_4     = STOF(ISTOF + 53)
      Vabc_B0_rms = STOF(ISTOF + 57)
      Iabc_B0_rms = STOF(ISTOF + 58)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vpcc_(IT_0) = STOF(ISTOF + 17 + IT_0)
         Ipcc_(IT_0) = STOF(ISTOF + 20 + IT_0)
         Iabc_B0(IT_0) = STOF(ISTOF + 27 + IT_0)
         Vabc_B0(IT_0) = STOF(ISTOF + 30 + IT_0)
         Iabc_B1(IT_0) = STOF(ISTOF + 38 + IT_0)
         Igabc_pu(IT_0) = STOF(ISTOF + 45 + IT_0)
         Vgabc_pu(IT_0) = STOF(ISTOF + 48 + IT_0)
         Vabc_B1(IT_0) = STOF(ISTOF + 53 + IT_0)
      END DO

! Array (1:5) quantities...
      DO IT_0 = 1,5
         Sig_GSC(IT_0) = STOF(ISTOF + 33 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Battery.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 190:[const] Real Constant 
      RT_4 = 1.0

! 230:[div] Divider 
      IF (ABS(Fnom) .LT. 1.0E-100) THEN
         IF (Fnom .LT. 0.0)  THEN
            Fpcc_pu_ = -1.0E100 * Fpcc
         ELSE
            Fpcc_pu_ =  1.0E100 * Fpcc
         ENDIF
      ELSE
         Fpcc_pu_ = Fpcc / Fnom
      ENDIF

! 350:[UC] Unit Controller 
      CALL UCDyn(Iabc_B0, Vdc_kV, Vabc_B0, Qpcc_pu_, Vpcc_pu_, Ppcc_pu_,&
     & Sig_GSC, Pcmd_pu, Qcmd_pu, Enable, APC, RPC, VRT, Iabc_B1, Sbase1&
     &, Fnom, Vac_nom, Vdc_nom, L_GSC_pu, R_GSC_pu, C_GSC_pu, Freq_PWM_G&
     &SC, SCRmax, Pblst_pu, Vgabc_pu, Igabc_pu)


! 360:[Parameters_Filters]  
      CALL Parameters_FiltersDyn(L_GSC_pu, R_GSC_pu, C_GSC_pu, Rc_GSC_pu&
     &, Sbase1, Fnom, Vac_nom, L_GSC, R_GSC, C_GSC, Rc_GSC)


! 370:[pgb] Output Channel 'Igabc_pu'

      DO IVD1_1 = 1, 3
         PGB(IPGB+5+IVD1_1-1) = Igabc_pu(IVD1_1)
      ENDDO

! 380:[pgb] Output Channel 'Vgabc_pu'

      DO IVD1_1 = 1, 3
         PGB(IPGB+8+IVD1_1-1) = Vgabc_pu(IVD1_1)
      ENDDO

! 390:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,1205570004)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+22), 0, Rc_GSC, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+23), 0, Rc_GSC, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+24), 0, Rc_GSC, 0.0)

! 400:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,982130316)
      CALL E_VARRLC1_EXE(2 ,SS ,  (IBRCH+1), 0, C_GSC, 0.0)
      CALL E_VARRLC1_EXE(2 ,SS ,  (IBRCH+2), 0, C_GSC, 0.0)
      CALL E_VARRLC1_EXE(2 ,SS ,  (IBRCH+3), 0, C_GSC, 0.0)

! 410:[mult] Multiplier 
      RT_3 = Vdc_nom * RT_4

! 420:[source_1] Single Phase Voltage Source Model 2 'Vdc'
! Externally controlled DC source: Type: Ideal
      RVD1_1 = RT_3
      RVD1_2 = 0.0
      RVD1_3 = RTCF(NRTCF)
      RVD1_4 = RTCF(NRTCF+1)
      NRTCF  = NRTCF + 2
      CALL EMTDC_1PVSRC(SS, (IBRCH+32),RVD1_4,0,RVD1_1,RVD1_2,RVD1_3)

! 430:[ConvBridge_IGBT]  
      CALL ConvBridge_IGBTDyn(Sig_GSC)


! 440:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,934256403)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+4), 0, R_GSC, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+5), 0, R_GSC, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+6), 0, R_GSC, 0.0)

! 450:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,1450533639)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+13), 0, L_GSC, 0.0)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+14), 0, L_GSC, 0.0)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+15), 0, L_GSC, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Pcmd_pu
      STOF(ISTOF + 2) = Qcmd_pu
      STOI(ISTOI + 1) = Enable
      STOI(ISTOI + 2) = VRT
      STOI(ISTOI + 3) = APC
      STOI(ISTOI + 4) = RPC
      STOF(ISTOF + 3) = Fnom
      STOF(ISTOF + 4) = Sbase1
      STOF(ISTOF + 5) = Vac_nom
      STOF(ISTOF + 6) = Vdc_nom
      STOF(ISTOF + 7) = L_GSC_pu
      STOF(ISTOF + 8) = R_GSC_pu
      STOF(ISTOF + 9) = C_GSC_pu
      STOF(ISTOF + 10) = Rc_GSC_pu
      STOF(ISTOF + 11) = Freq_PWM_GSC
      STOF(ISTOF + 12) = Pblst_pu
      STOF(ISTOF + 13) = SCRmax
      STOF(ISTOF + 14) = Ppcc_pu_
      STOF(ISTOF + 15) = Qpcc_pu_
      STOF(ISTOF + 16) = Vpcc_pu_
      STOF(ISTOF + 17) = Fpcc_pu_
      STOF(ISTOF + 24) = L_GSC
      STOF(ISTOF + 25) = R_GSC
      STOF(ISTOF + 26) = C_GSC
      STOF(ISTOF + 27) = Rc_GSC
      STOF(ISTOF + 42) = RT_1
      STOF(ISTOF + 43) = Fpcc
      STOF(ISTOF + 44) = RT_2
      STOF(ISTOF + 45) = Vdc_kV
      STOF(ISTOF + 52) = RT_3
      STOF(ISTOF + 53) = RT_4
      STOF(ISTOF + 57) = Vabc_B0_rms
      STOF(ISTOF + 58) = Iabc_B0_rms

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 17 + IT_0) = Vpcc_(IT_0)
         STOF(ISTOF + 20 + IT_0) = Ipcc_(IT_0)
         STOF(ISTOF + 27 + IT_0) = Iabc_B0(IT_0)
         STOF(ISTOF + 30 + IT_0) = Vabc_B0(IT_0)
         STOF(ISTOF + 38 + IT_0) = Iabc_B1(IT_0)
         STOF(ISTOF + 45 + IT_0) = Igabc_pu(IT_0)
         STOF(ISTOF + 48 + IT_0) = Vgabc_pu(IT_0)
         STOF(ISTOF + 53 + IT_0) = Vabc_B1(IT_0)
      END DO

! Array (1:5) quantities...
      DO IT_0 = 1,5
         STOF(ISTOF + 33 + IT_0) = Sig_GSC(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Ppcc_pu_ is output
      !Qpcc_pu_ is output
      !Vpcc_pu_ is output
      !Fpcc_pu_ is output
      !Vpcc_    is output
      !Ipcc_    is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BatteryOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    P3PH3         ! 
      REAL    Q3PH3         ! 
!     SUBR    DGTL_RMS3     ! '3 Phase Digital RMS Meter'
!     SUBR    DGTL_RMS3A    ! '3 Phase Digital RMS Meter'
!     SUBR    UCOut         ! Unit Controller
!     SUBR    Parameters_FiltersOut  ! 
!     SUBR    ConvBridge_IGBTOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  PCC(3), NT_2, NT_3, NT_7(3)
      INTEGER  NT_8(3), NT_12(3)

! Control Signals
      REAL     Ppcc_pu_       ! Aliases: Ppcc_pu
      REAL     Qpcc_pu_       ! Aliases: Qpcc_pu
      REAL     Vpcc_pu_       ! Aliases: Vpcc_pu
      REAL     Vpcc_(3)       ! Aliases: Vpcc
      REAL     Ipcc_(3)       ! Aliases: Ipcc
      REAL     Iabc_B0(3), Vabc_B0(3), Iabc_B1(3)
      REAL     RT_1, Fpcc, RT_2, Vdc_kV, RT_4
      REAL     Vabc_B1(3), Vabc_B0_rms
      REAL     Iabc_B0_rms

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD3_1(3)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 10
      INODE     = NNODE + 2
      NNODE     = NNODE + 32
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 32
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Ppcc_pu_ = STOF(ISTOF + 14)
      Qpcc_pu_ = STOF(ISTOF + 15)
      Vpcc_pu_ = STOF(ISTOF + 16)
      RT_1     = STOF(ISTOF + 42)
      Fpcc     = STOF(ISTOF + 43)
      RT_2     = STOF(ISTOF + 44)
      Vdc_kV   = STOF(ISTOF + 45)
      RT_4     = STOF(ISTOF + 53)
      Vabc_B0_rms = STOF(ISTOF + 57)
      Iabc_B0_rms = STOF(ISTOF + 58)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vpcc_(IT_0) = STOF(ISTOF + 17 + IT_0)
         Ipcc_(IT_0) = STOF(ISTOF + 20 + IT_0)
         Iabc_B0(IT_0) = STOF(ISTOF + 27 + IT_0)
         Vabc_B0(IT_0) = STOF(ISTOF + 30 + IT_0)
         Iabc_B1(IT_0) = STOF(ISTOF + 38 + IT_0)
         Vabc_B1(IT_0) = STOF(ISTOF + 53 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------

      NT_2  = NODE(INODE + 7)
      NT_3  = NODE(INODE + 8)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         PCC(IT_0) = NODE(INODE + 0 + IT_0)
         NT_7(IT_0) = NODE(INODE + 17 + IT_0)
         NT_8(IT_0) = NODE(INODE + 20 + IT_0)
         NT_12(IT_0) = NODE(INODE + 27 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Battery.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Ipcc_(1) = ( CBR((IBRCH+19), SS))
      Ipcc_(2) = ( CBR((IBRCH+20), SS))
      Ipcc_(3) = ( CBR((IBRCH+21), SS))
      Vpcc_(1) = EMTDC_VVDC(SS, NT_8(1), 0)
      Vpcc_(2) = EMTDC_VVDC(SS, NT_8(2), 0)
      Vpcc_(3) = EMTDC_VVDC(SS, NT_8(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+19), (IBRCH+20), (IBRCH+2&
     &1),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,886202023,RVD1_1,"Pd")
      Ppcc_pu_ = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+19), (IBRCH+20), (IBRCH+2&
     &1),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,886202023,RVD1_1,"Qd")
      Qpcc_pu_ = RVD1_1
      CALL DGTL_RMS3(256,SS,NT_8(1),NT_8(2),NT_8(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,886202023,RVD1_1,"Vd")
      Vpcc_pu_ = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,886202023,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,886202023,1,"hide2")
      ENDIF

! 90:[voltmeter] Voltmeter (Line - Line) 'Vdc_kV'
      Vdc_kV = EMTDC_VVDC(SS, NT_2, NT_3)

! 110:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Iabc_B0(1) = ( CBR((IBRCH+10), SS))
      Iabc_B0(2) = ( CBR((IBRCH+11), SS))
      Iabc_B0(3) = ( CBR((IBRCH+12), SS))
      Vabc_B0(1) = EMTDC_VVDC(SS, NT_12(1), 0)
      Vabc_B0(2) = EMTDC_VVDC(SS, NT_12(2), 0)
      Vabc_B0(3) = EMTDC_VVDC(SS, NT_12(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+10), (IBRCH+11), (IBRCH+1&
     &2),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1397285180,RVD1_1,"Pd")
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+10), (IBRCH+11), (IBRCH+1&
     &2),RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1397285180,RVD1_1,"Qd")
      CALL DGTL_RMS3(256,SS,NT_12(1),NT_12(2),NT_12(3),RTCF(IVD1_1+3),1.&
     &0,0.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,1397285180,RVD1_1,"Vd")
      Vabc_B0_rms = RVD1_1
      CALL DGTL_RMS3A(256,( CBR((IBRCH+10), SS)),( CBR((IBRCH+11), SS)),&
     &( CBR((IBRCH+12), SS)),RTCF(IVD1_1+3),RTCF(IVD1_1+4),0.0,RVD1_1)
      Iabc_B0_rms = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,1397285180,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,1397285180,1,"hide2")
      ENDIF

! 120:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Iabc_B1(1) = ( CBR((IBRCH+7), SS))
      Iabc_B1(2) = ( CBR((IBRCH+8), SS))
      Iabc_B1(3) = ( CBR((IBRCH+9), SS))
      Vabc_B1(1) = EMTDC_VVDC(SS, NT_7(1), 0)
      Vabc_B1(2) = EMTDC_VVDC(SS, NT_7(2), 0)
      Vabc_B1(3) = EMTDC_VVDC(SS, NT_7(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+7), (IBRCH+8), (IBRCH+9),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,2008365027,RVD1_1,"Pd")
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+7), (IBRCH+8), (IBRCH+9),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,2008365027,RVD1_1,"Qd")
      CALL DGTL_RMS3(256,SS,NT_7(1),NT_7(2),NT_7(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,2008365027,RVD1_1,"Vd")
      CALL DGTL_RMS3A(256,( CBR((IBRCH+7), SS)),( CBR((IBRCH+8), SS)),( &
     &CBR((IBRCH+9), SS)),RTCF(IVD1_1+3),RTCF(IVD1_1+4),0.0,RVD1_1)
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,2008365027,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,2008365027,1,"hide2")
      ENDIF

! 170:[freq-meas] Frequency/Incremental Phase/RMS Meter 
      RVD3_1(1) = VDC(PCC(1),SS)
      RVD3_1(2) = VDC(PCC(2),SS)
      RVD3_1(3) = VDC(PCC(3),SS)
      CALL E_FWAV1_EXE ( RVD3_1 ,  Fpcc , RT_2 , RT_1 )
      Fpcc = BY_2PI * Fpcc
!

! 190:[const] Real Constant 

      RT_4 = 1.0

! 310:[pgb] Output Channel 'Vdc_kV'

      PGB(IPGB+1) = Vdc_kV

! 320:[pgb] Output Channel 'Ppcc_pu_'

      PGB(IPGB+2) = Ppcc_pu_

! 330:[pgb] Output Channel 'Qpcc_pu_'

      PGB(IPGB+3) = Qpcc_pu_

! 340:[pgb] Output Channel 'Vpcc_pu_'

      PGB(IPGB+4) = Vpcc_pu_

! 350:[UC] Unit Controller 
      CALL UCOut()


! 360:[Parameters_Filters]  
      CALL Parameters_FiltersOut()


! 430:[ConvBridge_IGBT]  
      CALL ConvBridge_IGBTOut()


! 1:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+16), (IBRCH+17), (IBRCH+1&
     &8),RTCF(IVD1_1+2),0)
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+16), (IBRCH+17), (IBRCH+1&
     &8),RTCF(IVD1_1+2),0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 14) = Ppcc_pu_
      STOF(ISTOF + 15) = Qpcc_pu_
      STOF(ISTOF + 16) = Vpcc_pu_
      STOF(ISTOF + 42) = RT_1
      STOF(ISTOF + 43) = Fpcc
      STOF(ISTOF + 44) = RT_2
      STOF(ISTOF + 45) = Vdc_kV
      STOF(ISTOF + 53) = RT_4
      STOF(ISTOF + 57) = Vabc_B0_rms
      STOF(ISTOF + 58) = Iabc_B0_rms

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 17 + IT_0) = Vpcc_(IT_0)
         STOF(ISTOF + 20 + IT_0) = Ipcc_(IT_0)
         STOF(ISTOF + 27 + IT_0) = Iabc_B0(IT_0)
         STOF(ISTOF + 30 + IT_0) = Vabc_B0(IT_0)
         STOF(ISTOF + 38 + IT_0) = Iabc_B1(IT_0)
         STOF(ISTOF + 53 + IT_0) = Vabc_B1(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BatteryDyn_Begin(Fnom, Sbase1, Vac_nom, Vdc_nom,       &
     &   L_GSC_pu, R_GSC_pu, C_GSC_pu, Freq_PWM_GSC)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    UCDyn_Begin   ! Unit Controller
!     SUBR    Parameters_FiltersDyn_Begin  ! 
!     SUBR    ConvBridge_IGBTDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Fnom, Sbase1
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu
      REAL,    INTENT(IN)  :: Freq_PWM_GSC

! Electrical Node Indices

! Control Signals
      REAL     RT_4

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 32
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 32
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 190:[const] Real Constant 
      RT_4 = 1.0

! 230:[div] Divider 

! 350:[UC] Unit Controller 
      CALL UCDyn_Begin(Sbase1, Fnom, Vac_nom, Vdc_nom, Freq_PWM_GSC)


! 360:[Parameters_Filters]  
      CALL Parameters_FiltersDyn_Begin(Sbase1, Fnom, Vac_nom)


! 370:[pgb] Output Channel 'Igabc_pu'

! 380:[pgb] Output Channel 'Vgabc_pu'

! 390:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+22), 0)
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+23), 0)
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+24), 0)

! 400:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(2 ,SS ,  (IBRCH+1), 0)
      CALL E_VARRLC1_CFG(2 ,SS ,  (IBRCH+2), 0)
      CALL E_VARRLC1_CFG(2 ,SS ,  (IBRCH+3), 0)

! 410:[mult] Multiplier 

! 420:[source_1] Single Phase Voltage Source Model 2 'Vdc'
      RTCF(NRTCF) = 0.0
      RTCF(NRTCF+1) = 0.001
      NRTCF = NRTCF + 2

! 430:[ConvBridge_IGBT]  
      CALL ConvBridge_IGBTDyn_Begin()


! 440:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+4), 0)
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+5), 0)
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+6), 0)

! 450:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+13), 0)
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+14), 0)
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+15), 0)

      RETURN
      END

!=======================================================================

      SUBROUTINE BatteryOut_Begin(Fnom, Sbase1, Vac_nom, Vdc_nom,       &
     &   L_GSC_pu, R_GSC_pu, C_GSC_pu, Freq_PWM_GSC)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    UCOut_Begin   ! Unit Controller
!     SUBR    Parameters_FiltersOut_Begin  ! 
!     SUBR    ConvBridge_IGBTOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Fnom, Sbase1
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu
      REAL,    INTENT(IN)  :: Freq_PWM_GSC

! Electrical Node Indices
      INTEGER  NT_2, NT_3, NT_7(3), NT_8(3)
      INTEGER  NT_12(3)

! Control Signals
      REAL     RT_4

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 32
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 32
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------

      NT_2  = NODE(INODE + 7)
      NT_3  = NODE(INODE + 8)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_7(IT_0) = NODE(INODE + 17 + IT_0)
         NT_8(IT_0) = NODE(INODE + 20 + IT_0)
         NT_12(IT_0) = NODE(INODE + 27 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(Sbase1) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(Sbase1)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(Vac_nom) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vac_nom)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fnom

! 110:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fnom
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 120:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fnom
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 170:[freq-meas] Frequency/Incremental Phase/RMS Meter 
      CALL COMPONENT_ID(ICALL_NO,1735732357)
      CALL E_FWAV1_CFG(Vac_nom , Fnom , 0.002)

! 190:[const] Real Constant 
      RT_4 = 1.0

! 310:[pgb] Output Channel 'Vdc_kV'

! 320:[pgb] Output Channel 'Ppcc_pu_'

! 330:[pgb] Output Channel 'Qpcc_pu_'

! 340:[pgb] Output Channel 'Vpcc_pu_'

! 350:[UC] Unit Controller 
      CALL UCOut_Begin(Sbase1, Fnom, Vac_nom, Vdc_nom, Freq_PWM_GSC)


! 360:[Parameters_Filters]  
      CALL Parameters_FiltersOut_Begin(Sbase1, Fnom, Vac_nom)


! 430:[ConvBridge_IGBT]  
      CALL ConvBridge_IGBTOut_Begin()


! 1:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02

      RETURN
      END

