!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : BESS
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE BESSDyn(DBlk, Pref_pu, Qref_pu, Vref_pu, PFref, Ploc,  &
     &   Qloc, N, Sbase1, Fnom, Vrated_LV, Vdc_nom, Freq_PWM_GSC,       &
     &   L_GSC_pu, R_GSC_pu, C_GSC_pu, Rc_GSC_pu, Sbase, Vrated_HV,     &
     &   Vrated_MV, SCRmax)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PPCDyn        ! Power Plant Controller
!     SUBR    BatteryDyn    ! 
!     SUBR    Harmonic_FilterDyn  ! Harmonic Filter

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: DBlk
      REAL,    INTENT(IN)  :: Pref_pu, Qref_pu
      REAL,    INTENT(IN)  :: Vref_pu, PFref
      REAL,    INTENT(IN)  :: Ploc, Qloc, N
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vrated_LV, Vdc_nom
      REAL,    INTENT(IN)  :: Freq_PWM_GSC
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu, Rc_GSC_pu
      REAL,    INTENT(IN)  :: Sbase, Vrated_HV
      REAL,    INTENT(IN)  :: Vrated_MV, SCRmax

! Electrical Node Indices
      INTEGER  NT_3(3), NT_6(3)

! Control Signals
      INTEGER  BRK, Enable, APC, RPC, VRT, GTB
      REAL     Qpcc_pu, Vpcc_pu, Ppcc_pu, Pcmd_pu
      REAL     Qcmd_pu, Fpcc_pu, VBRKin_pu(3)
      REAL     VBRKout_pu(3), Vinrms_pu
      REAL     Voutrms_pu, Pblst_pu, Vpcc(3)
      REAL     Ipcc(3)

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      REAL     Hma_n_1, Hmb_n_1, Hmc_n_1, Hka_n_1
      REAL     Hkb_n_1, Hkc_n_1, Hma_n, Hmb_n
      REAL     Hmc_n, Hka_n, Hkb_n, Hkc_n, Yc
      REAL     Ycm

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 7
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 41
      IPGB      = NPGB
      NPGB      = NPGB + 10
      INODE     = NNODE + 2
      NNODE     = NNODE + 27
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 55
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 7
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Qpcc_pu  = STOF(ISTOF + 21)
      Vpcc_pu  = STOF(ISTOF + 22)
      Ppcc_pu  = STOF(ISTOF + 23)
      Pcmd_pu  = STOF(ISTOF + 24)
      Qcmd_pu  = STOF(ISTOF + 25)
      BRK      = STOI(ISTOI + 2)
      Enable   = STOI(ISTOI + 3)
      Fpcc_pu  = STOF(ISTOF + 26)
      APC      = STOI(ISTOI + 4)
      RPC      = STOI(ISTOI + 5)
      VRT      = STOI(ISTOI + 6)
      GTB      = STOI(ISTOI + 7)
      Vinrms_pu = STOF(ISTOF + 33)
      Voutrms_pu = STOF(ISTOF + 34)
      Pblst_pu = STOF(ISTOF + 35)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         VBRKin_pu(IT_0) = STOF(ISTOF + 26 + IT_0)
         VBRKout_pu(IT_0) = STOF(ISTOF + 29 + IT_0)
         Vpcc(IT_0) = STOF(ISTOF + 35 + IT_0)
         Ipcc(IT_0) = STOF(ISTOF + 38 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_3(IT_0) = NODE(INODE + 9 + IT_0)
         NT_6(IT_0) = NODE(INODE + 16 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'BESS.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 80:[LLTX_SCALER_pu]  
!
!
!

      IF(TIMEZERO) THEN
        STORF(NSTORF)=DELT/(0.001*(Vrated_MV*Vrated_MV/Sbase1)/(TWO_PI*F&
     &nom))
      ENDIF
      Yc  = STORF(NSTORF)
      Ycm = N*Yc

      Hka_n_1 =  STORF(NSTORF+1)
      Hkb_n_1 =  STORF(NSTORF+2)
      Hkc_n_1 =  STORF(NSTORF+3)
      !
      Hma_n_1 =  STORF(NSTORF+4)
      Hmb_n_1 =  STORF(NSTORF+5)
      Hmc_n_1 =  STORF(NSTORF+6)
      !
      ! History current calclulation is done for one loss loss line segment
      Hma_n = 2*VDC(NT_6(1),SS)*Yc - Hka_n_1
      Hmb_n = 2*VDC(NT_6(2),SS)*Yc - Hkb_n_1
      Hmc_n = 2*VDC(NT_6(3),SS)*Yc - Hkc_n_1
      !
      Hka_n = 2*VDC(NT_3(1),SS)*Yc - Hma_n_1
      Hkb_n = 2*VDC(NT_3(2),SS)*Yc - Hmb_n_1
      Hkc_n = 2*VDC(NT_3(3),SS)*Yc - Hmc_n_1
      ! History current is saved for the next time step
      STORF(NSTORF+1)= Hka_n
      STORF(NSTORF+2)= Hkb_n
      STORF(NSTORF+3)= Hkc_n
      !
      STORF(NSTORF+4)= Hma_n
      STORF(NSTORF+5)= Hmb_n
      STORF(NSTORF+6)= Hmc_n

! Ensure main program records CCIN current injections at these nodes
      IF ( TIMEZERO ) THEN
         ENABCCIN(NT_6(1), SS) = .TRUE.
         ENABCCIN(NT_6(2), SS) = .TRUE.
         ENABCCIN(NT_6(3), SS) = .TRUE.
!
         ENABCCIN(NT_3(1), SS) = .TRUE.
         ENABCCIN(NT_3(2), SS) = .TRUE.
         ENABCCIN(NT_3(3), SS) = .TRUE.
      ENDIF

! If 'SCL' number of parallel loss less lines are assumed. To save computation time only one unit (e.g. wind turbine) is simulated at k th side.
!If side m has 'SCL' number of parallel lossless lines connected together. Total impedance is Zc/SCL and total current injection is Hm*SCAL
      CCIN(NT_6(1),SS) = CCIN(NT_6(1),SS) + Hka_n
      CCIN(NT_6(2),SS) = CCIN(NT_6(2),SS) + Hkb_n
      CCIN(NT_6(3),SS) = CCIN(NT_6(3),SS) + Hkc_n
!
      GGIN(NT_6(1),SS) = GGIN(NT_6(1),SS) + Yc
      GGIN(NT_6(2),SS) = GGIN(NT_6(2),SS) + Yc
      GGIN(NT_6(3),SS) = GGIN(NT_6(3),SS) + Yc
!
!m Side current injection Scaled up by SCL
      CCIN(NT_3(1),SS) = CCIN(NT_3(1),SS) + N*Hma_n
      CCIN(NT_3(2),SS) = CCIN(NT_3(2),SS) + N*Hmb_n
      CCIN(NT_3(3),SS) = CCIN(NT_3(3),SS) + N*Hmc_n
!
!m Side Condutance Scaled down by SCL
      GGIN(NT_3(1),SS) = GGIN(NT_3(1),SS) + Ycm
      GGIN(NT_3(2),SS) = GGIN(NT_3(2),SS) + Ycm
      GGIN(NT_3(3),SS) = GGIN(NT_3(3),SS) + Ycm

      NSTORF = NSTORF + 7

! 90:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT2_EXE((IXFMR + 2),(IXFMR + 3),(IXFMR + 4), (IBRCH+10), (I&
     &BRCH+11), (IBRCH+12), (IBRCH+13), (IBRCH+14), (IBRCH+15),0,0,0,0,0&
     &,0,SS,0,1.0,0)

! 270:[PPC] Power Plant Controller 
      CALL PPCDyn(Pref_pu, PFref, Qref_pu, Vref_pu, Qpcc_pu, Vpcc_pu, Pp&
     &cc_pu, Pcmd_pu, Qcmd_pu, BRK, Enable, Fpcc_pu, DBlk, APC, RPC, VRT&
     &, GTB, VBRKin_pu, VBRKout_pu, Vinrms_pu, Voutrms_pu, Pblst_pu, 1.0&
     &, 0.0, 0.6, -0.6, 1.2, 0.8)


! 280:[Battery]  
      CALL BatteryDyn(Pcmd_pu, Qcmd_pu, Enable, VRT, APC, RPC, Fnom, Sba&
     &se1, Vrated_LV, Vdc_nom, L_GSC_pu, R_GSC_pu, C_GSC_pu, Rc_GSC_pu, &
     &Freq_PWM_GSC, Pblst_pu, SCRmax, Ppcc_pu, Qpcc_pu, Vpcc_pu, Fpcc_pu&
     &, Vpcc, Ipcc)


! 290:[pgb] Output Channel 'Ipcc'

      DO IVD1_1 = 1, 3
         PGB(IPGB+1+IVD1_1-1) = Ipcc(IVD1_1)
      ENDDO

! 300:[pgb] Output Channel 'Vpcc'

      DO IVD1_1 = 1, 3
         PGB(IPGB+4+IVD1_1-1) = Vpcc(IVD1_1)
      ENDDO

! 310:[pgb] Output Channel 'Fpcc_pu'

      PGB(IPGB+7) = Fpcc_pu

! 320:[pgb] Output Channel 'Vpcc_pu'

      PGB(IPGB+8) = Vpcc_pu

! 330:[pgb] Output Channel 'Qpcc_pu'

      PGB(IPGB+9) = Qpcc_pu

! 340:[pgb] Output Channel 'Ppcc_pu'

      PGB(IPGB+10) = Ppcc_pu

! 350:[Harmonic_Filter] Harmonic Filter 
      CALL Harmonic_FilterDyn(Fnom, Sbase, Vrated_MV, 900.0, L_GSC_pu)


! 380:[breaker3] 3 Phase Breaker 'BRK'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS, (IBRCH+1),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(BRK)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+2),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(BRK)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+3),1.0e-06,1000000000.0,RTCF(NRTCF)&
     &,0,NINT(1.0-REAL(BRK)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH+1),SS))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH+2),SS))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH+3),SS))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,539755099,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,539755099,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,539755099,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH+1),SS))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH+2),SS))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH+3),SS))

! 390:[breaker3] 3 Phase Breaker 'GTB'
      IVD1_4 = NSTORI
      NSTORI = NSTORI + 3
! Three Phase Breaker
      CALL EMTDC_BREAKER1(SS, (IBRCH+35),1.0e-06,1000000000.0,RTCF(NRTCF&
     &),0,NINT(1.0-REAL(GTB)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+36),1.0e-06,1000000000.0,RTCF(NRTCF&
     &),0,NINT(1.0-REAL(GTB)))
      CALL EMTDC_BREAKER1(SS, (IBRCH+37),1.0e-06,1000000000.0,RTCF(NRTCF&
     &),0,NINT(1.0-REAL(GTB)))
!
      IVD1_1 = 2*E_BtoI(OPENBR( (IBRCH+35),SS))
      IVD1_2 = 2*E_BtoI(OPENBR( (IBRCH+36),SS))
      IVD1_3 = 2*E_BtoI(OPENBR( (IBRCH+37),SS))
      NRTCF = NRTCF + 1
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+0) .NE. IVD1_1)) THEN
         CALL PSCAD_AGI2(ICALL_NO,79289047,IVD1_1,"BOpen1")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+1) .NE. IVD1_2)) THEN
         CALL PSCAD_AGI2(ICALL_NO,79289047,IVD1_2,"BOpen2")
      ENDIF
      IF (FIRSTSTEP .OR. (STORI(IVD1_4+2) .NE. IVD1_3)) THEN
         CALL PSCAD_AGI2(ICALL_NO,79289047,IVD1_3,"BOpen3")
      ENDIF
      STORI(IVD1_4+0) = 2*E_BtoI(OPENBR( (IBRCH+35),SS))
      STORI(IVD1_4+1) = 2*E_BtoI(OPENBR( (IBRCH+36),SS))
      STORI(IVD1_4+2) = 2*E_BtoI(OPENBR( (IBRCH+37),SS))

! 400:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
!  TRANSFORMER SATURATION SUBROUTINE
      IVD1_1 = NEXC
      CALL TSAT2_EXE((IXFMR + 5),(IXFMR + 6),(IXFMR + 7), (IBRCH+22), (I&
     &BRCH+23), (IBRCH+24), (IBRCH+25), (IBRCH+26), (IBRCH+27),0,0,0,0,0&
     &,0,SS,0,1.0,0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = DBlk
      STOF(ISTOF + 1) = Pref_pu
      STOF(ISTOF + 2) = Qref_pu
      STOF(ISTOF + 3) = Vref_pu
      STOF(ISTOF + 4) = PFref
      STOF(ISTOF + 5) = Ploc
      STOF(ISTOF + 6) = Qloc
      STOF(ISTOF + 7) = N
      STOF(ISTOF + 8) = Sbase1
      STOF(ISTOF + 9) = Fnom
      STOF(ISTOF + 10) = Vrated_LV
      STOF(ISTOF + 11) = Vdc_nom
      STOF(ISTOF + 12) = Freq_PWM_GSC
      STOF(ISTOF + 13) = L_GSC_pu
      STOF(ISTOF + 14) = R_GSC_pu
      STOF(ISTOF + 15) = C_GSC_pu
      STOF(ISTOF + 16) = Rc_GSC_pu
      STOF(ISTOF + 17) = Sbase
      STOF(ISTOF + 18) = Vrated_HV
      STOF(ISTOF + 19) = Vrated_MV
      STOF(ISTOF + 20) = SCRmax
      STOF(ISTOF + 21) = Qpcc_pu
      STOF(ISTOF + 22) = Vpcc_pu
      STOF(ISTOF + 23) = Ppcc_pu
      STOF(ISTOF + 24) = Pcmd_pu
      STOF(ISTOF + 25) = Qcmd_pu
      STOI(ISTOI + 2) = BRK
      STOI(ISTOI + 3) = Enable
      STOF(ISTOF + 26) = Fpcc_pu
      STOI(ISTOI + 4) = APC
      STOI(ISTOI + 5) = RPC
      STOI(ISTOI + 6) = VRT
      STOI(ISTOI + 7) = GTB
      STOF(ISTOF + 33) = Vinrms_pu
      STOF(ISTOF + 34) = Voutrms_pu
      STOF(ISTOF + 35) = Pblst_pu

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 26 + IT_0) = VBRKin_pu(IT_0)
         STOF(ISTOF + 29 + IT_0) = VBRKout_pu(IT_0)
         STOF(ISTOF + 35 + IT_0) = Vpcc(IT_0)
         STOF(ISTOF + 38 + IT_0) = Ipcc(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BESSOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
!     SUBR    DGTL_RMS3     ! '3 Phase Digital RMS Meter'
!     SUBR    PPCOut        ! Power Plant Controller
!     SUBR    BatteryOut    ! 
!     SUBR    Harmonic_FilterOut  ! Harmonic Filter
      REAL    VBRANCH       ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_3(3), NT_4(3)

! Control Signals
      REAL     VBRKin_pu(3), VBRKout_pu(3)
      REAL     Vinrms_pu, Voutrms_pu

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1, RVD1_2

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 10
      INODE     = NNODE + 2
      NNODE     = NNODE + 27
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 55
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 7
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Vinrms_pu = STOF(ISTOF + 33)
      Voutrms_pu = STOF(ISTOF + 34)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         VBRKin_pu(IT_0) = STOF(ISTOF + 26 + IT_0)
         VBRKout_pu(IT_0) = STOF(ISTOF + 29 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_3(IT_0) = NODE(INODE + 9 + IT_0)
         NT_4(IT_0) = NODE(INODE + 12 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'BESS.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 250:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      VBRKout_pu(1) = EMTDC_VVDC(SS, NT_4(1), 0)
      VBRKout_pu(2) = EMTDC_VVDC(SS, NT_4(2), 0)
      VBRKout_pu(3) = EMTDC_VVDC(SS, NT_4(3), 0)
      CALL DGTL_RMS3(256,SS,NT_4(1),NT_4(2),NT_4(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      Voutrms_pu = RVD1_1

! 260:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      VBRKin_pu(1) = EMTDC_VVDC(SS, NT_3(1), 0)
      VBRKin_pu(2) = EMTDC_VVDC(SS, NT_3(2), 0)
      VBRKin_pu(3) = EMTDC_VVDC(SS, NT_3(3), 0)
      CALL DGTL_RMS3(256,SS,NT_3(1),NT_3(2),NT_3(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      Vinrms_pu = RVD1_1

! 270:[PPC] Power Plant Controller 
      CALL PPCOut()


! 280:[Battery]  
      CALL BatteryOut()


! 350:[Harmonic_Filter] Harmonic Filter 
      CALL Harmonic_FilterOut()


! 380:[breaker3] 3 Phase Breaker 'BRK'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3),0,0,0,IVD1_1,0.&
     &02,RVD1_1,RVD1_2)

! 390:[breaker3] 3 Phase Breaker 'GTB'
! Three Phase Breaker Currents
      CALL BRK_POWER(SS, (IBRCH+35), (IBRCH+36), (IBRCH+37),0,0,0,IVD1_1&
     &,0.02,RVD1_1,RVD1_2)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 33) = Vinrms_pu
      STOF(ISTOF + 34) = Voutrms_pu

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 26 + IT_0) = VBRKin_pu(IT_0)
         STOF(ISTOF + 29 + IT_0) = VBRKout_pu(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE BESSDyn_Begin(Ploc, Qloc, N, Sbase1, Fnom, Vrated_LV,  &
     &   Vdc_nom, Freq_PWM_GSC, L_GSC_pu, R_GSC_pu, C_GSC_pu, Sbase,    &
     &   Vrated_HV, Vrated_MV)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PPCDyn_Begin  ! Power Plant Controller
!     SUBR    BatteryDyn_Begin  ! 
!     SUBR    Harmonic_FilterDyn_Begin  ! Harmonic Filter

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Ploc, Qloc, N
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vrated_LV, Vdc_nom
      REAL,    INTENT(IN)  :: Freq_PWM_GSC
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu, Sbase
      REAL,    INTENT(IN)  :: Vrated_HV
      REAL,    INTENT(IN)  :: Vrated_MV

! Electrical Node Indices

! Control Signals

! Internal Variables
      INTEGER  IVD1_1, IVD1_2, IVD1_3, IVD1_4
      REAL     RVD1_1, RVD1_2, RVD1_3, RVD1_4
      REAL     RVD1_5, RVD1_6

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 27
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 55
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 7
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 50:[newpi] Coupled Pi Section Transmission Line 'Line1'
      CALL COMPONENT_ID(ICALL_NO,1918798359)
      CALL PI3_SECTION_CFG(1,1,0, 0.0,0.0,Fnom,100.0,2.0e-05,4.0e-05,300&
     &.0,5.0e-05,0.001,500.0,RVD1_1,RVD1_2,RVD1_3,RVD1_4,RVD1_5,RVD1_6,I&
     &VD1_1,IVD1_2,IVD1_3,IVD1_4)
      CALL E_BRANCH_CFG( (IBRCH+38),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+39),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+40),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+41),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+42),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+43),SS,0,0,IVD1_3,0.0,0.0,RVD1_6)
      CALL E_BRANCH_CFG( (IBRCH+44),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+45),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+46),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+47),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+48),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL E_BRANCH_CFG( (IBRCH+34),SS,0,0,IVD1_4,0.0,0.0,RVD1_3)
      CALL COUPLED_PI3_TF_CFG((IXFMR + 1),2,RVD1_1,RVD1_2,RVD1_4,RVD1_5)

! 80:[LLTX_SCALER_pu]  

! 90:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
      CALL COMPONENT_ID(ICALL_NO,1669765560)
      RVD1_1 = ONE_3RD*Sbase1
      RVD1_2 = Vrated_MV
      RVD1_3 = Vrated_LV*SQRT_1BY3
      CALL E_TF2W_CFG((IXFMR + 2),1,RVD1_1,Fnom,0.05,0.006,RVD1_2,RVD1_3&
     &,0.4)
      CALL E_TF2W_CFG((IXFMR + 3),1,RVD1_1,Fnom,0.05,0.006,RVD1_2,RVD1_3&
     &,0.4)
      CALL E_TF2W_CFG((IXFMR + 4),1,RVD1_1,Fnom,0.05,0.006,RVD1_2,RVD1_3&
     &,0.4)
      IF (0.004 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.004
        RVD1_4 = 6.0/(Sbase1*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG( (IBRCH+4),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+5),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+6),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+7),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+8),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+9),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT2_CFG(2, (IBRCH+10), (IBRCH+11), (IBRCH+12), (IBRCH+13), &
     &(IBRCH+14), (IBRCH+15),0,0,0,0,0,0,SS,RVD1_1,0.2,1.17,Fnom,0.0,0.4&
     &,0.0,0.05,0.0,0.0,0.0,0.0,0.0,RVD1_2,RVD1_3,0.0,0.0)

! 270:[PPC] Power Plant Controller 
      CALL PPCDyn_Begin(1.0, 0.0, 0.6, -0.6, 1.2, 0.8)


! 280:[Battery]  
      CALL BatteryDyn_Begin(Fnom, Sbase1, Vrated_LV, Vdc_nom, L_GSC_pu, &
     &R_GSC_pu, C_GSC_pu, Freq_PWM_GSC)


! 290:[pgb] Output Channel 'Ipcc'

! 300:[pgb] Output Channel 'Vpcc'

! 310:[pgb] Output Channel 'Fpcc_pu'

! 320:[pgb] Output Channel 'Vpcc_pu'

! 330:[pgb] Output Channel 'Qpcc_pu'

! 340:[pgb] Output Channel 'Ppcc_pu'

! 350:[Harmonic_Filter] Harmonic Filter 
      CALL Harmonic_FilterDyn_Begin(Fnom, Sbase, Vrated_MV, 900.0)


! 360:[resistive_load] Three phase resistive load 
      CALL COMPONENT_ID(ICALL_NO,1890291113)
      CALL RESLOAD_CFG(SS, (IBRCH+31), (IBRCH+32), (IBRCH+33),0,Ploc,Vra&
     &ted_MV)

! 370:[reactive_load] Three phase inductive load 
      CALL COMPONENT_ID(ICALL_NO,293825461)
      CALL INDLOAD_CFG(SS, (IBRCH+28), (IBRCH+29), (IBRCH+30),0,Qloc,Vra&
     &ted_MV,Fnom)

! 380:[breaker3] 3 Phase Breaker 'BRK'
      CALL COMPONENT_ID(ICALL_NO,539755099)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 390:[breaker3] 3 Phase Breaker 'GTB'
      CALL COMPONENT_ID(ICALL_NO,79289047)
      RTCF(NRTCF) = ABS(0.0)
      NRTCF = NRTCF + 1

! 400:[xfmr-3p2w] 3 Phase 2 Winding Transformer 
      CALL COMPONENT_ID(ICALL_NO,574837668)
      RVD1_1 = ONE_3RD*Sbase
      RVD1_2 = Vrated_HV*SQRT_1BY3
      RVD1_3 = Vrated_MV
      CALL E_TF2W_CFG((IXFMR + 5),1,RVD1_1,Fnom,0.1,0.001,RVD1_2,RVD1_3,&
     &2.0)
      CALL E_TF2W_CFG((IXFMR + 6),1,RVD1_1,Fnom,0.1,0.001,RVD1_2,RVD1_3,&
     &2.0)
      CALL E_TF2W_CFG((IXFMR + 7),1,RVD1_1,Fnom,0.1,0.001,RVD1_2,RVD1_3,&
     &2.0)
      IF (0.001 .LT. 1.0E-6) THEN
        RVD1_5 = 0.0
        RVD1_6 = 0.0
        IVD1_1 = 0
      ELSE
        RVD1_6 = 0.001
        RVD1_4 = 6.0/(Sbase*RVD1_6)
        RVD1_5 = RVD1_4*RVD1_2*RVD1_2
        RVD1_6 = RVD1_4*RVD1_3*RVD1_3
        IVD1_1 = 1
      ENDIF
      CALL E_BRANCH_CFG( (IBRCH+16),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+17),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+18),SS,IVD1_1,0,0,RVD1_5,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+19),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+20),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL E_BRANCH_CFG( (IBRCH+21),SS,IVD1_1,0,0,RVD1_6,0.0,0.0)
      CALL TSAT2_CFG(2, (IBRCH+22), (IBRCH+23), (IBRCH+24), (IBRCH+25), &
     &(IBRCH+26), (IBRCH+27),0,0,0,0,0,0,SS,RVD1_1,0.2,1.17,Fnom,0.0,2.0&
     &,0.0,0.1,0.0,0.0,0.0,0.0,0.0,RVD1_2,RVD1_3,0.0,0.0)

      RETURN
      END

!=======================================================================

      SUBROUTINE BESSOut_Begin(Ploc, Qloc, N, Sbase1, Fnom, Vrated_LV,  &
     &   Vdc_nom, Freq_PWM_GSC, L_GSC_pu, R_GSC_pu, C_GSC_pu, Sbase,    &
     &   Vrated_HV, Vrated_MV)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PPCOut_Begin  ! Power Plant Controller
!     SUBR    BatteryOut_Begin  ! 
!     SUBR    Harmonic_FilterOut_Begin  ! Harmonic Filter

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Ploc, Qloc, N
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vrated_LV, Vdc_nom
      REAL,    INTENT(IN)  :: Freq_PWM_GSC
      REAL,    INTENT(IN)  :: L_GSC_pu, R_GSC_pu
      REAL,    INTENT(IN)  :: C_GSC_pu, Sbase
      REAL,    INTENT(IN)  :: Vrated_HV
      REAL,    INTENT(IN)  :: Vrated_MV

! Electrical Node Indices
      INTEGER  NT_3(3), NT_4(3)

! Control Signals

! Internal Variables
      INTEGER  IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH, IXFMR             ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 27
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 55
      IXFMR     = NXFMR
      NXFMR     = NXFMR + 7
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_3(IT_0) = NODE(INODE + 9 + IT_0)
         NT_4(IT_0) = NODE(INODE + 12 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 250:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(Vrated_MV) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vrated_MV)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+3) = Fnom

! 260:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(Vrated_MV) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(Vrated_MV)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+3) = Fnom

! 270:[PPC] Power Plant Controller 
      CALL PPCOut_Begin(1.0, 0.0, 0.6, -0.6, 1.2, 0.8)


! 280:[Battery]  
      CALL BatteryOut_Begin(Fnom, Sbase1, Vrated_LV, Vdc_nom, L_GSC_pu, &
     &R_GSC_pu, C_GSC_pu, Freq_PWM_GSC)


! 350:[Harmonic_Filter] Harmonic Filter 
      CALL Harmonic_FilterOut_Begin(Fnom, Sbase, Vrated_MV, 900.0)


      RETURN
      END

