!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Calculations
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE CalculationsDyn(Igabc_pu, Vabc_pu, P_pu_, Vrms_pu_,    &
     &   Q_pu_, Vdq_pu_, Igdq_pu_, Theta, Itabc_pu, Itdq_pu_)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    RMS3          ! 'Instantaneous RMS Measurement'
!     SUBR    ABC_to_DQ0Dyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Igabc_pu(3)
      REAL,    INTENT(IN)  :: Vabc_pu(3), Theta
      REAL,    INTENT(IN)  :: Itabc_pu(3)
      REAL,    INTENT(OUT) :: P_pu_! Aliases: P_pu
      REAL,    INTENT(OUT) :: Vrms_pu_! Aliases: Vrms_pu
      REAL,    INTENT(OUT) :: Q_pu_! Aliases: Q_pu
      REAL,    INTENT(OUT) :: Vdq_pu_(2)! Aliases: Vdq_pu
      REAL,    INTENT(OUT) :: Igdq_pu_(2)! Aliases: Igdq_pu
      REAL,    INTENT(OUT) :: Itdq_pu_(2)! Aliases: Itdq_pu

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     Ita_pu, Itb_pu, Itc_pu, RT_7, RT_8
      REAL     RT_9, RT_10, RT_11(3), RT_12
      REAL     RT_13, RT_14, RT_15, RT_16, RT_17
      REAL     RT_18, RT_19(3), RT_20, RT_21
      REAL     RT_22, Vc_pu, RT_23, Vb_pu, RT_24
      REAL     Va_pu, Iga_pu, Igb_pu, Igc_pu

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 56
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      P_pu_    = STOF(ISTOF + 7)
      Vrms_pu_ = STOF(ISTOF + 8)
      Q_pu_    = STOF(ISTOF + 9)
      RT_1     = STOF(ISTOF + 20)
      RT_2     = STOF(ISTOF + 21)
      RT_3     = STOF(ISTOF + 22)
      RT_4     = STOF(ISTOF + 23)
      RT_5     = STOF(ISTOF + 24)
      RT_6     = STOF(ISTOF + 25)
      Ita_pu   = STOF(ISTOF + 26)
      Itb_pu   = STOF(ISTOF + 27)
      Itc_pu   = STOF(ISTOF + 28)
      RT_7     = STOF(ISTOF + 29)
      RT_8     = STOF(ISTOF + 30)
      RT_9     = STOF(ISTOF + 31)
      RT_10    = STOF(ISTOF + 32)
      RT_12    = STOF(ISTOF + 36)
      RT_13    = STOF(ISTOF + 37)
      RT_14    = STOF(ISTOF + 38)
      RT_15    = STOF(ISTOF + 39)
      RT_16    = STOF(ISTOF + 40)
      RT_17    = STOF(ISTOF + 41)
      RT_18    = STOF(ISTOF + 42)
      RT_20    = STOF(ISTOF + 46)
      RT_21    = STOF(ISTOF + 47)
      RT_22    = STOF(ISTOF + 48)
      Vc_pu    = STOF(ISTOF + 49)
      RT_23    = STOF(ISTOF + 50)
      Vb_pu    = STOF(ISTOF + 51)
      RT_24    = STOF(ISTOF + 52)
      Va_pu    = STOF(ISTOF + 53)
      Iga_pu   = STOF(ISTOF + 54)
      Igb_pu   = STOF(ISTOF + 55)
      Igc_pu   = STOF(ISTOF + 56)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         Vdq_pu_(IT_0) = STOF(ISTOF + 9 + IT_0)
         Igdq_pu_(IT_0) = STOF(ISTOF + 11 + IT_0)
         Itdq_pu_(IT_0) = STOF(ISTOF + 17 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_11(IT_0) = STOF(ISTOF + 32 + IT_0)
         RT_19(IT_0) = STOF(ISTOF + 42 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Calculations.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 
      Va_pu = Vabc_pu(1)

! 30:[datatap] Scalar/Array Tap 
      Vb_pu = Vabc_pu(2)

! 40:[datatap] Scalar/Array Tap 
      Vc_pu = Vabc_pu(3)

! 60:[datatap] Scalar/Array Tap 
      Iga_pu = Igabc_pu(1)

! 70:[datatap] Scalar/Array Tap 
      Igb_pu = Igabc_pu(2)

! 80:[datatap] Scalar/Array Tap 
      Igc_pu = Igabc_pu(3)

! 90:[sumjct] Summing/Differencing Junctions 
      RT_20 = + Vb_pu - Vc_pu

! 100:[mult] Multiplier 
      RT_16 = RT_20 * Iga_pu

! 120:[sumjct] Summing/Differencing Junctions 
      RT_21 = + Vc_pu - Va_pu

! 130:[mult] Multiplier 
      RT_17 = RT_21 * Igb_pu

! 140:[datatap] Scalar/Array Tap 
      Ita_pu = Itabc_pu(1)

! 150:[datatap] Scalar/Array Tap 
      Itb_pu = Itabc_pu(2)

! 160:[datatap] Scalar/Array Tap 
      Itc_pu = Itabc_pu(3)

! 170:[sumjct] Summing/Differencing Junctions 
      RT_13 = + Va_pu - Vb_pu

! 180:[mult] Multiplier 
      RT_18 = RT_13 * Igc_pu

! 200:[rms-inst] Single Phase RMS Meter 
      RT_10 = RMS3( Va_pu , 0.02 )

! 210:[gain] Gain Block 
!  Gain
      Vrms_pu_ = 1.414214 * RT_10

! 220:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Dyn(Va_pu, Vb_pu, Vc_pu, RT_1, RT_2, RT_3, Theta)


! 230:[datamerge] Merges data signals into an array 
      Vdq_pu_(1) = RT_1
      Vdq_pu_(2) = RT_2

! 240:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Dyn(Iga_pu, Igb_pu, Igc_pu, RT_4, RT_5, RT_6, Theta&
     &)


! 250:[datamerge] Merges data signals into an array 
      Igdq_pu_(1) = RT_4
      Igdq_pu_(2) = RT_5

! 260:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Dyn(Ita_pu, Itb_pu, Itc_pu, RT_7, RT_8, RT_9, Theta&
     &)


! 270:[datamerge] Merges data signals into an array 
      Itdq_pu_(1) = RT_7
      Itdq_pu_(2) = RT_8

! 280:[mult] Multiplier 
      RT_24 = Va_pu * Iga_pu

! 290:[mult] Multiplier 
      RT_23 = Vb_pu * Igb_pu

! 300:[mult] Multiplier 
      RT_22 = Vc_pu * Igc_pu

! 310:[datamerge] Merges data signals into an array 
      RT_19(1) = RT_16
      RT_19(2) = RT_17
      RT_19(3) = RT_18

! 320:[sum_array] Sum of all elements in an array 
      RT_15 = SUM(RT_19,1)

! 330:[gain] Gain Block 
!  Gain
      RT_14 = 0.57735027 * RT_15

! 340:[datamerge] Merges data signals into an array 
      RT_11(1) = RT_24
      RT_11(2) = RT_23
      RT_11(3) = RT_22

! 350:[sum_array] Sum of all elements in an array 
      RT_12 = SUM(RT_11,1)

! 360:[gain] Gain Block 
!  Gain
      Q_pu_ = 0.6666667 * RT_14

! 370:[gain] Gain Block 
!  Gain
      P_pu_ = 0.6666667 * RT_12

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 7) = P_pu_
      STOF(ISTOF + 8) = Vrms_pu_
      STOF(ISTOF + 9) = Q_pu_
      STOF(ISTOF + 14) = Theta
      STOF(ISTOF + 20) = RT_1
      STOF(ISTOF + 21) = RT_2
      STOF(ISTOF + 22) = RT_3
      STOF(ISTOF + 23) = RT_4
      STOF(ISTOF + 24) = RT_5
      STOF(ISTOF + 25) = RT_6
      STOF(ISTOF + 26) = Ita_pu
      STOF(ISTOF + 27) = Itb_pu
      STOF(ISTOF + 28) = Itc_pu
      STOF(ISTOF + 29) = RT_7
      STOF(ISTOF + 30) = RT_8
      STOF(ISTOF + 31) = RT_9
      STOF(ISTOF + 32) = RT_10
      STOF(ISTOF + 36) = RT_12
      STOF(ISTOF + 37) = RT_13
      STOF(ISTOF + 38) = RT_14
      STOF(ISTOF + 39) = RT_15
      STOF(ISTOF + 40) = RT_16
      STOF(ISTOF + 41) = RT_17
      STOF(ISTOF + 42) = RT_18
      STOF(ISTOF + 46) = RT_20
      STOF(ISTOF + 47) = RT_21
      STOF(ISTOF + 48) = RT_22
      STOF(ISTOF + 49) = Vc_pu
      STOF(ISTOF + 50) = RT_23
      STOF(ISTOF + 51) = Vb_pu
      STOF(ISTOF + 52) = RT_24
      STOF(ISTOF + 53) = Va_pu
      STOF(ISTOF + 54) = Iga_pu
      STOF(ISTOF + 55) = Igb_pu
      STOF(ISTOF + 56) = Igc_pu

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 9 + IT_0) = Vdq_pu_(IT_0)
         STOF(ISTOF + 11 + IT_0) = Igdq_pu_(IT_0)
         STOF(ISTOF + 17 + IT_0) = Itdq_pu_(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 0 + IT_0) = Igabc_pu(IT_0)
         STOF(ISTOF + 3 + IT_0) = Vabc_pu(IT_0)
         STOF(ISTOF + 14 + IT_0) = Itabc_pu(IT_0)
         STOF(ISTOF + 32 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 42 + IT_0) = RT_19(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !P_pu_    is output
      !Vrms_pu_ is output
      !Q_pu_    is output
      !Vdq_pu_  is output
      !Igdq_pu_ is output
      !Itdq_pu_ is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE CalculationsOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    ABC_to_DQ0Out  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------



!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Calculations.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 220:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Out()


! 240:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Out()


! 260:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Out()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------



!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE CalculationsDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    ABC_to_DQ0Dyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 

! 30:[datatap] Scalar/Array Tap 

! 40:[datatap] Scalar/Array Tap 

! 60:[datatap] Scalar/Array Tap 

! 70:[datatap] Scalar/Array Tap 

! 80:[datatap] Scalar/Array Tap 

! 90:[sumjct] Summing/Differencing Junctions 

! 100:[mult] Multiplier 

! 120:[sumjct] Summing/Differencing Junctions 

! 130:[mult] Multiplier 

! 140:[datatap] Scalar/Array Tap 

! 150:[datatap] Scalar/Array Tap 

! 160:[datatap] Scalar/Array Tap 

! 170:[sumjct] Summing/Differencing Junctions 

! 180:[mult] Multiplier 

! 200:[rms-inst] Single Phase RMS Meter 

! 210:[gain] Gain Block 

! 220:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Dyn_Begin()


! 230:[datamerge] Merges data signals into an array 

! 240:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Dyn_Begin()


! 250:[datamerge] Merges data signals into an array 

! 260:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Dyn_Begin()


! 270:[datamerge] Merges data signals into an array 

! 280:[mult] Multiplier 

! 290:[mult] Multiplier 

! 300:[mult] Multiplier 

! 310:[datamerge] Merges data signals into an array 

! 320:[sum_array] Sum of all elements in an array 

! 330:[gain] Gain Block 

! 340:[datamerge] Merges data signals into an array 

! 350:[sum_array] Sum of all elements in an array 

! 360:[gain] Gain Block 

! 370:[gain] Gain Block 

      RETURN
      END

!=======================================================================

      SUBROUTINE CalculationsOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    ABC_to_DQ0Out_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 220:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Out_Begin()


! 240:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Out_Begin()


! 260:[ABC_to_DQ0]  
      CALL ABC_to_DQ0Out_Begin()


      RETURN
      END

