!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : ConvBridge_IGBT
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE ConvBridge_IGBTDyn(Ref)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PWMDyn        ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Ref(5)

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1
      REAL     RT_1(4), RT_2(12), RT_3(3), RT_4
      REAL     RT_5, RT_6(2), RT_7(2), RT_8(2)
      REAL     RT_9(2), RT_10(2), RT_11(2), RT_12
      REAL     RT_13, RT_14, beta, RT_15, RT_16
      REAL     alpha, RT_17, M, Ph, Freq_PWM
      REAL     gt5(2), gt4(2), gt3(2), gt2(2)
      REAL     gt1(2), gt6(2), Igto1, Vgto1

! Internal Variables
      REAL     RVD12_1(12)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 1
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 63
      IPGB      = NPGB
      NPGB      = NPGB + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 8
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 26
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_4     = STOF(ISTOF + 25)
      RT_5     = STOF(ISTOF + 26)
      IT_1     = STOI(ISTOI + 1)
      RT_12    = STOF(ISTOF + 39)
      RT_13    = STOF(ISTOF + 40)
      RT_14    = STOF(ISTOF + 41)
      beta     = STOF(ISTOF + 42)
      RT_15    = STOF(ISTOF + 43)
      RT_16    = STOF(ISTOF + 44)
      alpha    = STOF(ISTOF + 45)
      RT_17    = STOF(ISTOF + 46)
      M        = STOF(ISTOF + 47)
      Ph       = STOF(ISTOF + 48)
      Freq_PWM = STOF(ISTOF + 49)
      Igto1    = STOF(ISTOF + 62)
      Vgto1    = STOF(ISTOF + 63)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         RT_6(IT_0) = STOF(ISTOF + 26 + IT_0)
         RT_7(IT_0) = STOF(ISTOF + 28 + IT_0)
         RT_8(IT_0) = STOF(ISTOF + 30 + IT_0)
         RT_9(IT_0) = STOF(ISTOF + 32 + IT_0)
         RT_10(IT_0) = STOF(ISTOF + 34 + IT_0)
         RT_11(IT_0) = STOF(ISTOF + 36 + IT_0)
         gt5(IT_0) = STOF(ISTOF + 49 + IT_0)
         gt4(IT_0) = STOF(ISTOF + 51 + IT_0)
         gt3(IT_0) = STOF(ISTOF + 53 + IT_0)
         gt2(IT_0) = STOF(ISTOF + 55 + IT_0)
         gt1(IT_0) = STOF(ISTOF + 57 + IT_0)
         gt6(IT_0) = STOF(ISTOF + 59 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         RT_3(IT_0) = STOF(ISTOF + 21 + IT_0)
      END DO

! Array (1:4) quantities...
      DO IT_0 = 1,4
         RT_1(IT_0) = STOF(ISTOF + 5 + IT_0)
      END DO

! Array (1:12) quantities...
      DO IT_0 = 1,12
         RT_2(IT_0) = STOF(ISTOF + 9 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'ConvBridge_IGBT.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 
      RT_3 = Ref(1 : 3)

! 30:[datatap] Scalar/Array Tap 
      RT_4 = Ref(5)

! 40:[datamerge] Merges data signals into an array 
      RT_1(1 : 3) = RT_3
      RT_1(4) = RT_4

! 50:[datatap] Scalar/Array Tap 
      Freq_PWM = Ref(4)

! 60:[datatap] Scalar/Array Tap 
      RT_12 = Ref(5)

! 70:[unity] Type/Shape conversion block 
! real -> nearest integer
      IT_1 = NINT(RT_12)

! 80:[datatap] Scalar/Array Tap 
      RT_13 = Ref(1)

! 90:[datatap] Scalar/Array Tap 
      RT_14 = Ref(2)

! 100:[datatap] Scalar/Array Tap 
      RT_15 = Ref(3)

! 110:[const] Real Constant 
      RT_17 = 0.0

! 120:[PWM]  
      CALL PWMDyn(RT_1, RT_2, 5000.0)


! 130:[abc_to_alphabeta0]  
!!!! abc to alphabeta0
!!!! Scripted by MHRavanji
!!!! moh.ravanji@gmail.com
!!!! Date Modified: 2022-05-31

        alpha = 0.666666666667*(RT_13+(-0.5)*RT_14+(-0.5)*RT_15)
        beta = 0.666666666667*((0.8660254)*RT_14+(-0.8660254)*RT_15)
        RT_16 = 0.666666666667*((0.5)*RT_13+(0.5)*RT_14+(0.5)*RT_15)

! 140:[polar_rec] Polar Rectangular coordinate converter 
      M = SQRT(alpha*alpha+beta*beta)
      IF ((ABS(alpha).GT.1.0E-20).OR.(ABS(beta).GT.1.0E-20)) THEN
        Ph = ATAN2(beta,alpha)
      ELSE
        Ph = 0.0
      ENDIF

! 150:[sumjct] Summing/Differencing Junctions 
      RT_5 = + Ph + RT_17

! 160:[svm] SVM Firing Pulse Generator 
      CALL SVM_EDGE1_EXE(1,IT_1,M,RT_5,RVD12_1)
      RT_6 = RVD12_1(1:2)
      RT_7 = RVD12_1(3:4)
      RT_8 = RVD12_1(5:6)
      RT_9 = RVD12_1(7:8)
      RT_10 = RVD12_1(9:10)
      RT_11 = RVD12_1(11:12)

! 170:[pgb] Output Channel 'Ph'

      PGB(IPGB+1) = Ph

! 180:[pgb] Output Channel 'M'

      PGB(IPGB+2) = M

! 190:[datatap] Scalar/Array Tap 
      gt6 = RT_2(11 : 12)

! 200:[datatap] Scalar/Array Tap 
      gt5 = RT_2(9 : 10)

! 210:[datatap] Scalar/Array Tap 
      gt4 = RT_2(7 : 8)

! 220:[datatap] Scalar/Array Tap 
      gt3 = RT_2(5 : 6)

! 230:[datatap] Scalar/Array Tap 
      gt2 = RT_2(3 : 4)

! 240:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1546532097)
      CALL PESWITCH1_EXE(SS, (IBRCH+7), NINT(gt2(1)), gt2(2))

! 250:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,977895874)
      CALL PESWITCH1_EXE(SS, (IBRCH+9), NINT(gt6(1)), gt6(2))

! 260:[datatap] Scalar/Array Tap 
      gt1 = RT_2(1 : 2)

! 270:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,993932798)
      CALL PESWITCH1_EXE(SS, (IBRCH+11), NINT(gt4(1)), gt4(2))

! 280:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1476360763)
      CALL PESWITCH1_EXE(SS, (IBRCH+5), NINT(gt5(1)), gt5(2))

! 290:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,846880554)
      CALL PESWITCH1_EXE(SS, (IBRCH+3), NINT(gt3(1)), gt3(2))

! 300:[peswitch] Power electronic switch 
! Power Electronic Switch Model: IGBT
      CALL COMPONENT_ID(ICALL_NO,1570938386)
      CALL PESWITCH1_EXE(SS, (IBRCH+1), NINT(gt1(1)), gt1(2))

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,130687301)
      CALL PESWITCH1_EXE(SS, (IBRCH+13), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,666164634)
      CALL PESWITCH1_EXE(SS, (IBRCH+15), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1257233589)
      CALL PESWITCH1_EXE(SS, (IBRCH+17), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1847551407)
      CALL PESWITCH1_EXE(SS, (IBRCH+23), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1059736473)
      CALL PESWITCH1_EXE(SS, (IBRCH+21), 1, 0.0)

! 1:[peswitch] Power electronic switch 
! Power Electronic Switch Model: Diode
      CALL COMPONENT_ID(ICALL_NO,1641252496)
      CALL PESWITCH1_EXE(SS, (IBRCH+19), 1, 0.0)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 25) = RT_4
      STOF(ISTOF + 26) = RT_5
      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 39) = RT_12
      STOF(ISTOF + 40) = RT_13
      STOF(ISTOF + 41) = RT_14
      STOF(ISTOF + 42) = beta
      STOF(ISTOF + 43) = RT_15
      STOF(ISTOF + 44) = RT_16
      STOF(ISTOF + 45) = alpha
      STOF(ISTOF + 46) = RT_17
      STOF(ISTOF + 47) = M
      STOF(ISTOF + 48) = Ph
      STOF(ISTOF + 49) = Freq_PWM
      STOF(ISTOF + 62) = Igto1
      STOF(ISTOF + 63) = Vgto1

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 26 + IT_0) = RT_6(IT_0)
         STOF(ISTOF + 28 + IT_0) = RT_7(IT_0)
         STOF(ISTOF + 30 + IT_0) = RT_8(IT_0)
         STOF(ISTOF + 32 + IT_0) = RT_9(IT_0)
         STOF(ISTOF + 34 + IT_0) = RT_10(IT_0)
         STOF(ISTOF + 36 + IT_0) = RT_11(IT_0)
         STOF(ISTOF + 49 + IT_0) = gt5(IT_0)
         STOF(ISTOF + 51 + IT_0) = gt4(IT_0)
         STOF(ISTOF + 53 + IT_0) = gt3(IT_0)
         STOF(ISTOF + 55 + IT_0) = gt2(IT_0)
         STOF(ISTOF + 57 + IT_0) = gt1(IT_0)
         STOF(ISTOF + 59 + IT_0) = gt6(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 21 + IT_0) = RT_3(IT_0)
      END DO

! Array (1:4) quantities...
      DO IT_0 = 1,4
         STOF(ISTOF + 5 + IT_0) = RT_1(IT_0)
      END DO

! Array (1:5) quantities...
      DO IT_0 = 1,5
         STOF(ISTOF + 0 + IT_0) = Ref(IT_0)
      END DO

! Array (1:12) quantities...
      DO IT_0 = 1,12
         STOF(ISTOF + 9 + IT_0) = RT_2(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE ConvBridge_IGBTOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PWMOut        ! 
      REAL    VBRANCH       ! Voltage across the branch

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_17, Igto1, Vgto1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 2
      INODE     = NNODE + 2
      NNODE     = NNODE + 8
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 26
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_17    = STOF(ISTOF + 46)
      Igto1    = STOF(ISTOF + 62)
      Vgto1    = STOF(ISTOF + 63)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'ConvBridge_IGBT.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 110:[const] Real Constant 

      RT_17 = 0.0

! 120:[PWM]  
      CALL PWMOut()


! 300:[peswitch] Power electronic switch 
      Igto1 = ( CBR((IBRCH+1), SS))
      Vgto1 = VBRANCH(SS, (IBRCH+1))

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 46) = RT_17
      STOF(ISTOF + 62) = Igto1
      STOF(ISTOF + 63) = Vgto1


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE ConvBridge_IGBTDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PWMDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_17

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 8
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 26
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[datatap] Scalar/Array Tap 

! 30:[datatap] Scalar/Array Tap 

! 40:[datamerge] Merges data signals into an array 

! 50:[datatap] Scalar/Array Tap 

! 60:[datatap] Scalar/Array Tap 

! 70:[unity] Type/Shape conversion block 

! 80:[datatap] Scalar/Array Tap 

! 90:[datatap] Scalar/Array Tap 

! 100:[datatap] Scalar/Array Tap 

! 110:[const] Real Constant 
      RT_17 = 0.0

! 120:[PWM]  
      CALL PWMDyn_Begin()


! 130:[abc_to_alphabeta0]  

! 140:[polar_rec] Polar Rectangular coordinate converter 

! 150:[sumjct] Summing/Differencing Junctions 

! 160:[svm] SVM Firing Pulse Generator 
      CALL COMPONENT_ID(ICALL_NO,532277097)
      CALL SVM_EDGE1_CFG(5000.0)

! 170:[pgb] Output Channel 'Ph'

! 180:[pgb] Output Channel 'M'

! 190:[datatap] Scalar/Array Tap 

! 200:[datatap] Scalar/Array Tap 

! 210:[datatap] Scalar/Array Tap 

! 220:[datatap] Scalar/Array Tap 

! 230:[datatap] Scalar/Array Tap 

! 240:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0005, 10000000000.0, 100000.0, 100000.0,&
     & 0.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+8),SS,1,0,1,5000.0,0.0,0.05)

! 250:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0005, 10000000000.0, 100000.0, 100000.0,&
     & 0.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+10),SS,1,0,1,5000.0,0.0,0.05)

! 260:[datatap] Scalar/Array Tap 

! 270:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0005, 10000000000.0, 100000.0, 100000.0,&
     & 0.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+12),SS,1,0,1,5000.0,0.0,0.05)

! 280:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0005, 10000000000.0, 100000.0, 100000.0,&
     & 0.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+6),SS,1,0,1,5000.0,0.0,0.05)

! 290:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0005, 10000000000.0, 100000.0, 100000.0,&
     & 0.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+4),SS,1,0,1,5000.0,0.0,0.05)

! 300:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(3, 0,0.0005, 10000000000.0, 100000.0, 100000.0,&
     & 0.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+2),SS,1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.0005, 100000000.0, 100000.0, 100000.0, 0&
     &.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+14),SS,1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.0005, 100000000.0, 100000.0, 100000.0, 0&
     &.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+16),SS,1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.0005, 100000000.0, 100000.0, 100000.0, 0&
     &.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+18),SS,1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.0005, 100000000.0, 100000.0, 100000.0, 0&
     &.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+24),SS,1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.0005, 100000000.0, 100000.0, 100000.0, 0&
     &.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+22),SS,1,0,1,5000.0,0.0,0.05)

! 1:[peswitch] Power electronic switch 
      CALL PESWITCH1_CFG(0, 0,0.0005, 100000000.0, 100000.0, 100000.0, 0&
     &.0, 0.0)
      CALL E_BRANCH_CFG( (IBRCH+20),SS,1,0,1,5000.0,0.0,0.05)

      RETURN
      END

!=======================================================================

      SUBROUTINE ConvBridge_IGBTOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PWMOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_17

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      INODE     = NNODE + 2
      NNODE     = NNODE + 8
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 26
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 110:[const] Real Constant 
      RT_17 = 0.0

! 120:[PWM]  
      CALL PWMOut_Begin()


      RETURN
      END

