!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : GSC_Voltage_Controller
! Description   : GSC Voltage Controller
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE GSC_Voltage_ControllerDyn(Idq_pu, Vdqref_pu,           &
     &   Idqref_pu_, Enable, Vdq_pu, VRT, Frz, Kp_GVC, Ki_GVC, Kff_GVC, &
     &   ChFreq_GVC, Kdc_GVC)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    CMPX2ORD      ! Second Order Complex Pole
!     SUBR    PI_AntiWindUpDyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, VRT, Frz(2)
      REAL,    INTENT(IN)  :: Idq_pu(2)
      REAL,    INTENT(IN)  :: Vdqref_pu(2)
      REAL,    INTENT(IN)  :: Vdq_pu(2), Kp_GVC
      REAL,    INTENT(IN)  :: Ki_GVC, Kff_GVC
      REAL,    INTENT(IN)  :: ChFreq_GVC, Kdc_GVC
      REAL,    INTENT(OUT) :: Idqref_pu_(2)! Aliases: Idqref_pu

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4, Frz_d
      INTEGER  IT_5, Frz_q, IT_6
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8, RT_9, RT_10, Ti_GVC
      REAL     RT_11, Idref_pu, Iqref_pu, Id_pu
      REAL     Iq_pu, Vd_pu, Vq_pu, Vdref_pu
      REAL     Vqref_pu

! Internal Variables
      REAL     RVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 12
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 33
      IPGB      = NPGB
      NPGB      = NPGB + 11
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 14)
      RT_2     = STOF(ISTOF + 15)
      IT_1     = STOI(ISTOI + 5)
      RT_3     = STOF(ISTOF + 16)
      RT_4     = STOF(ISTOF + 17)
      IT_2     = STOI(ISTOI + 6)
      RT_5     = STOF(ISTOF + 18)
      RT_6     = STOF(ISTOF + 19)
      RT_7     = STOF(ISTOF + 20)
      RT_8     = STOF(ISTOF + 21)
      RT_9     = STOF(ISTOF + 22)
      RT_10    = STOF(ISTOF + 23)
      IT_3     = STOI(ISTOI + 7)
      IT_4     = STOI(ISTOI + 8)
      Ti_GVC   = STOF(ISTOF + 24)
      RT_11    = STOF(ISTOF + 25)
      Idref_pu = STOF(ISTOF + 26)
      Iqref_pu = STOF(ISTOF + 27)
      Frz_d    = STOI(ISTOI + 9)
      IT_5     = STOI(ISTOI + 10)
      Frz_q    = STOI(ISTOI + 11)
      IT_6     = STOI(ISTOI + 12)
      Id_pu    = STOF(ISTOF + 28)
      Iq_pu    = STOF(ISTOF + 29)
      Vd_pu    = STOF(ISTOF + 30)
      Vq_pu    = STOF(ISTOF + 31)
      Vdref_pu = STOF(ISTOF + 32)
      Vqref_pu = STOF(ISTOF + 33)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         Idqref_pu_(IT_0) = STOF(ISTOF + 4 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'GSC_Voltage_Controller.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[consti] Integer Constant 
      IT_3 = 1

! 20:[inv] Interpolated Logic Inverter 
      IF (IT_3 .NE. 0) THEN
         IT_1 = 0
      ELSE
         IT_1 = 1
      ENDIF

! 30:[consti] Integer Constant 
      IT_4 = 1

! 40:[inv] Interpolated Logic Inverter 
      IF (IT_4 .NE. 0) THEN
         IT_2 = 0
      ELSE
         IT_2 = 1
      ENDIF

! 100:[const] Real Constant 
      RT_11 = 1.0

! 140:[pgb] Output Channel 'VRT'

      PGB(IPGB+1) = REAL(VRT)

! 180:[datatap] Scalar/Array Tap 
      IT_6 = Frz(2)

! 190:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (IT_6 .NE. 0) .OR. (VRT .NE. 0) ) THEN
        Frz_q = 1
      ELSE
        Frz_q = 0
      ENDIF

! 200:[pgb] Output Channel 'Frz_q'

      PGB(IPGB+2) = REAL(Frz_q)

! 210:[datatap] Scalar/Array Tap 
      Vd_pu = Vdq_pu(1)

! 220:[datatap] Scalar/Array Tap 
      Vq_pu = Vdq_pu(2)

! 230:[datatap] Scalar/Array Tap 
      Vdref_pu = Vdqref_pu(1)

! 240:[datatap] Scalar/Array Tap 
      Vqref_pu = Vdqref_pu(2)

! 250:[gain] Gain Block 
!  Gain
      RT_8 = Kdc_GVC * Vd_pu

! 260:[sumjct] Summing/Differencing Junctions 
      RT_10 = - Vq_pu + Vqref_pu

! 270:[gain] Gain Block 
!  Gain
      RT_3 = REAL(Enable) * RT_10

! 280:[datatap] Scalar/Array Tap 
      Id_pu = Idq_pu(1)

! 290:[datatap] Scalar/Array Tap 
      Iq_pu = Idq_pu(2)

! 300:[complex] Second Order Complex Pole 
! Second Order Complex Pole
      RVD1_1 = TWO_PI*ChFreq_GVC
      RT_9 = CMPX2ORD(1, Kff_GVC, 0.7, RVD1_1, Iq_pu)
!

! 310:[div] Divider 
      IF (ABS(Ki_GVC) .LT. 1.0E-100) THEN
         IF (Ki_GVC .LT. 0.0)  THEN
            Ti_GVC = -1.0E100 * RT_11
         ELSE
            Ti_GVC =  1.0E100 * RT_11
         ENDIF
      ELSE
         Ti_GVC = RT_11 / Ki_GVC
      ENDIF

! 320:[datatap] Scalar/Array Tap 
      IT_5 = Frz(1)

! 330:[gain] Gain Block 
!  Gain
      RT_6 = Kdc_GVC * Vq_pu

! 340:[sumjct] Summing/Differencing Junctions 
      RT_5 = - Vd_pu + Vdref_pu

! 350:[gain] Gain Block 
!  Gain
      RT_1 = REAL(Enable) * RT_5

! 360:[complex] Second Order Complex Pole 
! Second Order Complex Pole
      RVD1_1 = TWO_PI*ChFreq_GVC
      RT_7 = CMPX2ORD(1, Kff_GVC, 0.7, RVD1_1, Id_pu)
!

! 370:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn(RT_3, RT_4, Frz_q, IT_2, Kp_GVC, Ti_GVC, 1.0&
     &, 5.0, -5.0)


! 380:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (VRT .NE. 0) .OR. (IT_5 .NE. 0) ) THEN
        Frz_d = 1
      ELSE
        Frz_d = 0
      ENDIF

! 390:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn(RT_1, RT_2, Frz_d, IT_1, Kp_GVC, Ti_GVC, 1.0&
     &, 5.0, -5.0)


! 400:[sumjct] Summing/Differencing Junctions 
      Idref_pu = - RT_6 + RT_2 + RT_7

! 410:[sumjct] Summing/Differencing Junctions 
      Iqref_pu = + RT_8 + RT_4 + RT_9

! 420:[datamerge] Merges data signals into an array 
      Idqref_pu_(1) = Idref_pu
      Idqref_pu_(2) = Iqref_pu

! 440:[pgb] Output Channel 'Frz_d'

      PGB(IPGB+3) = REAL(Frz_d)

! 450:[pgb] Output Channel 'Iq_pu'

      PGB(IPGB+4) = Iq_pu

! 460:[pgb] Output Channel 'Iqref_pu'

      PGB(IPGB+5) = Iqref_pu

! 470:[pgb] Output Channel 'Vq_pu'

      PGB(IPGB+6) = Vq_pu

! 480:[pgb] Output Channel 'Id_pu'

      PGB(IPGB+7) = Id_pu

! 490:[pgb] Output Channel 'Vqref_pu'

      PGB(IPGB+8) = Vqref_pu

! 500:[pgb] Output Channel 'Vd_pu'

      PGB(IPGB+9) = Vd_pu

! 510:[pgb] Output Channel 'Idref_pu'

      PGB(IPGB+10) = Idref_pu

! 520:[pgb] Output Channel 'Vdref_pu'

      PGB(IPGB+11) = Vdref_pu

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = Enable
      STOI(ISTOI + 2) = VRT
      STOF(ISTOF + 9) = Kp_GVC
      STOF(ISTOF + 10) = Ki_GVC
      STOF(ISTOF + 11) = Kff_GVC
      STOF(ISTOF + 12) = ChFreq_GVC
      STOF(ISTOF + 13) = Kdc_GVC
      STOF(ISTOF + 14) = RT_1
      STOF(ISTOF + 15) = RT_2
      STOI(ISTOI + 5) = IT_1
      STOF(ISTOF + 16) = RT_3
      STOF(ISTOF + 17) = RT_4
      STOI(ISTOI + 6) = IT_2
      STOF(ISTOF + 18) = RT_5
      STOF(ISTOF + 19) = RT_6
      STOF(ISTOF + 20) = RT_7
      STOF(ISTOF + 21) = RT_8
      STOF(ISTOF + 22) = RT_9
      STOF(ISTOF + 23) = RT_10
      STOI(ISTOI + 7) = IT_3
      STOI(ISTOI + 8) = IT_4
      STOF(ISTOF + 24) = Ti_GVC
      STOF(ISTOF + 25) = RT_11
      STOF(ISTOF + 26) = Idref_pu
      STOF(ISTOF + 27) = Iqref_pu
      STOI(ISTOI + 9) = Frz_d
      STOI(ISTOI + 10) = IT_5
      STOI(ISTOI + 11) = Frz_q
      STOI(ISTOI + 12) = IT_6
      STOF(ISTOF + 28) = Id_pu
      STOF(ISTOF + 29) = Iq_pu
      STOF(ISTOF + 30) = Vd_pu
      STOF(ISTOF + 31) = Vq_pu
      STOF(ISTOF + 32) = Vdref_pu
      STOF(ISTOF + 33) = Vqref_pu

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 0 + IT_0) = Idq_pu(IT_0)
         STOF(ISTOF + 2 + IT_0) = Vdqref_pu(IT_0)
         STOF(ISTOF + 4 + IT_0) = Idqref_pu_(IT_0)
         STOF(ISTOF + 6 + IT_0) = Vdq_pu(IT_0)
         STOI(ISTOI + 2 + IT_0) = Frz(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Idqref_pu_ is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE GSC_Voltage_ControllerOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  IT_3, IT_4
      REAL     RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 11
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      IT_3     = STOI(ISTOI + 7)
      IT_4     = STOI(ISTOI + 8)
      RT_11    = STOF(ISTOF + 25)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'GSC_Voltage_Controller.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[consti] Integer Constant 

      IT_3 = 1

! 30:[consti] Integer Constant 

      IT_4 = 1

! 100:[const] Real Constant 

      RT_11 = 1.0

! 370:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut()


! 390:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 7) = IT_3
      STOI(ISTOI + 8) = IT_4
      STOF(ISTOF + 25) = RT_11


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE GSC_Voltage_ControllerDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_3, IT_4
      REAL     RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[consti] Integer Constant 
      IT_3 = 1

! 20:[inv] Interpolated Logic Inverter 

! 30:[consti] Integer Constant 
      IT_4 = 1

! 40:[inv] Interpolated Logic Inverter 

! 100:[const] Real Constant 
      RT_11 = 1.0

! 140:[pgb] Output Channel 'VRT'

! 180:[datatap] Scalar/Array Tap 

! 200:[pgb] Output Channel 'Frz_q'

! 210:[datatap] Scalar/Array Tap 

! 220:[datatap] Scalar/Array Tap 

! 230:[datatap] Scalar/Array Tap 

! 240:[datatap] Scalar/Array Tap 

! 250:[gain] Gain Block 

! 260:[sumjct] Summing/Differencing Junctions 

! 270:[gain] Gain Block 

! 280:[datatap] Scalar/Array Tap 

! 290:[datatap] Scalar/Array Tap 

! 300:[complex] Second Order Complex Pole 

! 310:[div] Divider 

! 320:[datatap] Scalar/Array Tap 

! 330:[gain] Gain Block 

! 340:[sumjct] Summing/Differencing Junctions 

! 350:[gain] Gain Block 

! 360:[complex] Second Order Complex Pole 

! 370:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn_Begin()


! 390:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn_Begin()


! 400:[sumjct] Summing/Differencing Junctions 

! 410:[sumjct] Summing/Differencing Junctions 

! 420:[datamerge] Merges data signals into an array 

! 440:[pgb] Output Channel 'Frz_d'

! 450:[pgb] Output Channel 'Iq_pu'

! 460:[pgb] Output Channel 'Iqref_pu'

! 470:[pgb] Output Channel 'Vq_pu'

! 480:[pgb] Output Channel 'Id_pu'

! 490:[pgb] Output Channel 'Vqref_pu'

! 500:[pgb] Output Channel 'Vd_pu'

! 510:[pgb] Output Channel 'Idref_pu'

! 520:[pgb] Output Channel 'Vdref_pu'

      RETURN
      END

!=======================================================================

      SUBROUTINE GSC_Voltage_ControllerOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_3, IT_4
      REAL     RT_11

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[consti] Integer Constant 
      IT_3 = 1

! 30:[consti] Integer Constant 
      IT_4 = 1

! 100:[const] Real Constant 
      RT_11 = 1.0

! 370:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut_Begin()


! 390:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut_Begin()


      RETURN
      END

