!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Main
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE MainDyn()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    EMTDC_X2COMP  ! 'Comparator with Interpolation'
!     SUBR    BESSDyn       ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1(3), NT_2(3), NT_7(3), NT_8(3)
      INTEGER  NT_9(3)

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4, IT_5, IT_6
      INTEGER  Fault, Fault_Type
      REAL     Vpoc(3), Ipoc(3), RT_1, RT_2, RT_3
      REAL     RT_4, Sbase, SCR, XR, Ll, Rl
      REAL     Vpoc_rms, Ppoc, Qpoc, Ipoc_rms
      REAL     Vsource, Pref_pu, Qref_pu, PFref
      REAL     Vref_pu, RT_5, RT_6, Fnom, RT_7
      REAL     Rl1, Rl2, Ll1, Ll2, RT_8, RT_9(34)

! Internal Variables
      LOGICAL  LVD1_1
      INTEGER  BR_S_, BR_MA_, BR_MB_, BR_EA_
      INTEGER  BR_ZA_, BR_CA_, BR_IA_, BR_EB_
      INTEGER  BR_ZB_, BR_CB_, BR_IB_, NA_, NB_
      INTEGER  NAM_, NBM_, NAI_, NBI_, NAIC_
      INTEGER  NBIC_, NS_, IVD1_1
      REAL     RVD1_1, RVD2_1(2), RVD1_2, RVD1_3
      REAL     RVD1_4, RVD1_5, RVD1_6, RVD1_7

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER ICX                                 ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 8
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 67
      NPGB      = NPGB + 10
      ICX       = NCX
      NCX       = NCX + 10
      INODE     = NNODE + 2
      NNODE     = NNODE + 29
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 33
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      IT_1     = STOI(ISTOI + 1)
      RT_1     = STOF(ISTOF + 7)
      RT_2     = STOF(ISTOF + 8)
      RT_3     = STOF(ISTOF + 9)
      RT_4     = STOF(ISTOF + 10)
      Sbase    = STOF(ISTOF + 11)
      SCR      = STOF(ISTOF + 12)
      XR       = STOF(ISTOF + 13)
      Ll       = STOF(ISTOF + 14)
      Rl       = STOF(ISTOF + 15)
      Vpoc_rms = STOF(ISTOF + 16)
      Ppoc     = STOF(ISTOF + 17)
      Qpoc     = STOF(ISTOF + 18)
      Ipoc_rms = STOF(ISTOF + 19)
      Vsource  = STOF(ISTOF + 20)
      Pref_pu  = STOF(ISTOF + 21)
      Qref_pu  = STOF(ISTOF + 22)
      PFref    = STOF(ISTOF + 23)
      Vref_pu  = STOF(ISTOF + 24)
      IT_2     = STOI(ISTOI + 2)
      IT_3     = STOI(ISTOI + 3)
      IT_4     = STOI(ISTOI + 4)
      IT_5     = STOI(ISTOI + 5)
      IT_6     = STOI(ISTOI + 6)
      Fault    = STOI(ISTOI + 7)
      Fault_Type = STOI(ISTOI + 8)
      RT_5     = STOF(ISTOF + 25)
      RT_6     = STOF(ISTOF + 26)
      Fnom     = STOF(ISTOF + 27)
      RT_7     = STOF(ISTOF + 28)
      Rl1      = STOF(ISTOF + 29)
      Rl2      = STOF(ISTOF + 30)
      Ll1      = STOF(ISTOF + 31)
      Ll2      = STOF(ISTOF + 32)
      RT_8     = STOF(ISTOF + 33)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vpoc(IT_0) = STOF(ISTOF + 0 + IT_0)
         Ipoc(IT_0) = STOF(ISTOF + 3 + IT_0)
      END DO

! Array (1:34) quantities...
      DO IT_0 = 1,34
         RT_9(IT_0) = STOF(ISTOF + 33 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_1(IT_0) = NODE(INODE + 0 + IT_0)
         NT_2(IT_0) = NODE(INODE + 3 + IT_0)
         NT_7(IT_0) = NODE(INODE + 18 + IT_0)
         NT_8(IT_0) = NODE(INODE + 21 + IT_0)
         NT_9(IT_0) = NODE(INODE + 24 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 'MVA'
      Sbase = 200.0

! 20:[const] Real Constant 'Hz'
      Fnom = 50.0

! 30:[const] Real Constant 'kV'
      Vsource = 500.0

! 40:[RZ] Rezonance module 





      NA_ = -1
      NB_ = -1
      NAM_ = -1
      NBM_ = -1
      NAI_ = -1
      NBI_ = -1
      NAIC_ = -1
      NBIC_ = -1
      NS_ = -1

      BR_S_ = -1
      BR_MA_ = -1
      BR_MB_ = -1

      BR_EA_ = -1
      BR_ZA_ = -1
      BR_CA_ = -1
      BR_IA_ = -1

      BR_ZB_ = -1
      BR_CB_ = -1
      BR_EB_ = -1
      BR_IB_ = -1

      NA_ = NT_1(1)
      NB_ = NT_7(1)
      NAM_ = NT_8(1)
      NBM_ = NT_9(1)

      BR_MA_ =  (IBRCH+25)
      BR_MB_ =  (IBRCH+28)



      BR_EA_ =  (IBRCH+31)



      CALL COMPONENT_ID(ICALL_NO,2101249384)
      CALL DYN_RZ(1, 0, 0, 0, 1, 1,1, 0.0, 5.0, SS, BR_S_, BR_MA_, BR_MB&
     &_,BR_EA_, BR_EB_, BR_CA_, BR_CB_, BR_IA_, BR_IB_, BR_ZA_, BR_ZB_,N&
     &A_, NB_, NS_, 500.0, 100.0, 100.0, 50.0,(0.02, 0.1), (0.02, 0.1), &
     &1.0e-06, 1.0e-12, 1.0e-20,1, 0, 0,0.0, 1.0, 10.0, 0.0,1.0, 10.0, 1&
     &.0,0.0, 0.0, 0.001,3.0, 1.0, 0.5,0, 0, 0, 0,1, 1.0, 1000.0, 1.0, 1&
     &001, 1001, 1,0.0, 0.0, 0.0, 0.0, 0.25,5, "_", "in_arr_f.txt", RT_9&
     &)

! 50:[var] Variable Input Slider 'V_source'
      RT_4 = CX(CXMAP(ICX+1))

! 60:[mult] Multiplier 
      RT_1 = RT_4 * Vsource

! 80:[var] Variable Input Slider 'Pref_pu'
      Pref_pu = CX(CXMAP(ICX+2))

! 90:[var] Variable Input Slider 'F_source'
      RT_6 = CX(CXMAP(ICX+3))

! 100:[mult] Multiplier 
      RT_2 = RT_6 * Fnom

! 110:[time-sig] Output of Simulation Time 
      RT_5 = TIME

! 120:[var] Variable Input Slider 'Ph0_source'
      RT_7 = CX(CXMAP(ICX+4))

! 130:[compare] Single Input Level Comparator 
!
!
      CALL EMTDC_X2COMP(0,0,0.1,RT_5,0.0,0.0,1.0,RVD2_1)
      IT_1 = NINT(RVD2_1(1))

! 140:[const] Real Constant 
      RT_8 = 90.0

! 150:[var] Variable Input Slider 'Qref_pu'
      Qref_pu = CX(CXMAP(ICX+5))

! 160:[var] Variable Input Slider 'Vref_pu'
      Vref_pu = CX(CXMAP(ICX+6))

! 170:[var] Variable Input Slider 'PFref'
      PFref = CX(CXMAP(ICX+7))

! 180:[var] Variable Input Slider 'SCR'
      SCR = CX(CXMAP(ICX+8))

! 190:[var] Variable Input Slider 'XR'
      XR = CX(CXMAP(ICX+9))

! 200:[var_pot] Rotary Switch 'Fault Type'
      Fault_Type = NINT(CX(CXMAP(ICX+10)))

! 220:[Sequencer_Start] Sequencer (Start of sequence of events) 
! Sequencer - Start
      IT_4 = 1
! Update PSCAD Graphics
      IF ( FIRSTSTEP ) THEN
         CALL PSCAD_AGI2(ICALL_NO,2069275658,STORI(NSTORI),"State")
      ENDIF
      IF ( STORI(NSTORI) .NE. IT_4 ) THEN
         CALL PSCAD_AGI2(ICALL_NO,2069275658,IT_4,"State")
      ENDIF
      STORI(NSTORI) = IT_4
      NSTORI = NSTORI + 1

! 230:[Sequencer_Wait] Sequencer (Wait for an event) 
! Sequencer - Wait for Fixed Delay
      IT_5 = 0
      IF ( IT_4 .EQ. 1 ) THEN
         IF ( STORI(NSTORI) .EQ. 0 ) THEN
            STORF(NSTORF) = TIME
            STORI(NSTORI) = 1
         ENDIF
         IF ( (TIME-STORF(NSTORF)).GT.2.0 ) THEN
            IT_5 = 1
         ENDIF
      ELSE
         STORI(NSTORI) = 0
      ENDIF
      NSTORF = NSTORF + 1
      NSTORI = NSTORI + 1
! Update PSCAD Graphics
      IF ( FIRSTSTEP ) THEN
         CALL PSCAD_AGI2(ICALL_NO,1526424488,STORI(NSTORI),"State")
      ENDIF
      IF ( STORI(NSTORI) .NE. IT_5 ) THEN
         CALL PSCAD_AGI2(ICALL_NO,1526424488,IT_5,"State")
      ENDIF
      STORI(NSTORI) = IT_5
      NSTORI = NSTORI + 1

! 240:[Sequencer_Fault] Sequencer (Apply/Clear Fault) 
! Sequencer - Apply Fault
      IT_6 = 0
      IF ( IT_5 .EQ. 1 ) THEN
         Fault  = 1
         IT_6 = 1
      ENDIF
! Update PSCAD Graphics
      IF ( FIRSTSTEP ) THEN
         CALL PSCAD_AGI2(ICALL_NO,2026814490,STORI(NSTORI),"State")
      ENDIF
      IF ( STORI(NSTORI) .NE. IT_6 ) THEN
         CALL PSCAD_AGI2(ICALL_NO,2026814490,IT_6,"State")
      ENDIF
      STORI(NSTORI) = IT_6
      NSTORI = NSTORI + 1
      Fault = Fault

! 250:[Sequencer_Wait] Sequencer (Wait for an event) 
! Sequencer - Wait for Fixed Delay
      IT_2 = 0
      IF ( IT_6 .EQ. 1 ) THEN
         IF ( STORI(NSTORI) .EQ. 0 ) THEN
            STORF(NSTORF) = TIME
            STORI(NSTORI) = 1
         ENDIF
         IF ( (TIME-STORF(NSTORF)).GT.0.2 ) THEN
            IT_2 = 1
         ENDIF
      ELSE
         STORI(NSTORI) = 0
      ENDIF
      NSTORF = NSTORF + 1
      NSTORI = NSTORI + 1
! Update PSCAD Graphics
      IF ( FIRSTSTEP ) THEN
         CALL PSCAD_AGI2(ICALL_NO,1700549886,STORI(NSTORI),"State")
      ENDIF
      IF ( STORI(NSTORI) .NE. IT_2 ) THEN
         CALL PSCAD_AGI2(ICALL_NO,1700549886,IT_2,"State")
      ENDIF
      STORI(NSTORI) = IT_2
      NSTORI = NSTORI + 1

! 270:[Sequencer_Fault] Sequencer (Apply/Clear Fault) 
! Sequencer - Remove Fault
      IT_3 = 0
      IF ( IT_2 .EQ. 1 ) THEN
         Fault  = 0
         IT_3 = 1
      ENDIF
! Update PSCAD Graphics
      IF ( FIRSTSTEP ) THEN
         CALL PSCAD_AGI2(ICALL_NO,918990990,STORI(NSTORI),"State")
      ENDIF
      IF ( STORI(NSTORI) .NE. IT_3 ) THEN
         CALL PSCAD_AGI2(ICALL_NO,918990990,IT_3,"State")
      ENDIF
      STORI(NSTORI) = IT_3
      NSTORI = NSTORI + 1
      Fault = Fault

! 320:[Grid_RL_Calc] Grid RL Calc 
!!!! Grid_RL_Calc
!!!! Scripted by MHRavanji
!!!! moh.ravanji@gmail.com
!!!! Date Modified: 2022-04-28


        Rl = 1/SCR/sqrt(1+(XR*XR))*Vsource*Vsource/Sbase
        Ll = 1/SCR/sqrt(1+1/(XR*XR))*Vsource*Vsource/Sbase/(2*3.14159265&
     &3589793*Fnom)

! 330:[gain] Gain Block 
!  Gain
      Ll2 = 0.2 * Ll

! 340:[gain] Gain Block 
!  Gain
      Ll1 = 0.8 * Ll

! 350:[gain] Gain Block 
!  Gain
      Rl2 = 0.2 * Rl

! 360:[gain] Gain Block 
!  Gain
      Rl1 = 0.8 * Rl

! 370:[sumjct] Summing/Differencing Junctions 
      RT_3 = + RT_8 + RT_7

! 380:[BESS]  
      CALL BESSDyn(IT_1, Pref_pu, Qref_pu, Vref_pu, PFref, 0.5, 0.05, 10&
     &0.0, 2.0, Fnom, 0.69, 1.2, 5000.0, 0.1, 0.002, 0.04, 0.01, Sbase, &
     &Vsource, 33.0, 10.0)


! 390:[tpflt] Three Phase Fault 
      CALL E3PHFLT1_EXE(SS, (IBRCH+13), (IBRCH+14), (IBRCH+15), (IBRCH+1&
     &6), (IBRCH+17), (IBRCH+18),0,Fault,Fault_Type,0.0004)
      LVD1_1 = (OPENBR( (IBRCH+13),SS).AND.OPENBR( (IBRCH+14),SS).AND.OP&
     &ENBR( (IBRCH+15),SS).AND.OPENBR( (IBRCH+16),SS).AND.OPENBR( (IBRCH&
     &+17),SS).AND.OPENBR( (IBRCH+18),SS))
      IVD1_1 = E_BtoI(LVD1_1)
      IF(FIRSTSTEP .OR. (IVD1_1 .NE. STORI(NSTORI))) THEN
         CALL PSCAD_AGI2(ICALL_NO,531090414,1-IVD1_1,"AG1")
         STORI(NSTORI) = IVD1_1
      ENDIF
      NSTORI = NSTORI + 1

! 400:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,1329056424)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+22), 0, Rl1, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+23), 0, Rl1, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+24), 0, Rl1, 0.0)

! 410:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,1022206475)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+19), 0, Ll1, 0.0)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+20), 0, Ll1, 0.0)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+21), 0, Ll1, 0.0)

! 420:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,865855499)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+10), 0, Rl2, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+11), 0, Rl2, 0.0)
      CALL E_VARRLC1_EXE(0 ,SS ,  (IBRCH+12), 0, Rl2, 0.0)

! 430:[varrlc] Variable R, L or C  
      CALL COMPONENT_ID(ICALL_NO,1944686776)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+7), 0, Ll2, 0.0)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+8), 0, Ll2, 0.0)
      CALL E_VARRLC1_EXE(1 ,SS ,  (IBRCH+9), 0, Ll2, 0.0)

! 440:[source3] Three Phase Voltage Source Model 1 'Source1'
!  3-Phase source: Source1
      RVD1_1 = RT_1
      RVD1_2 = RT_2
      RVD1_3 = RT_3 *PI_BY180
      CALL ESYS651_EXE(SS, (IBRCH+4), (IBRCH+5), (IBRCH+6),0,0,0, SS, NT&
     &_2(1),NT_2(2),NT_2(3), 0, RVD1_2, RVD1_1, 0.001, 1.0, 1.0, 1.0,RVD&
     &1_3, 1.0,0.02,0.05, 1.0,0.02,0.05, RVD1_4, RVD1_5, RVD1_6, RVD1_7)

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOI(ISTOI + 1) = IT_1
      STOF(ISTOF + 7) = RT_1
      STOF(ISTOF + 8) = RT_2
      STOF(ISTOF + 9) = RT_3
      STOF(ISTOF + 10) = RT_4
      STOF(ISTOF + 11) = Sbase
      STOF(ISTOF + 12) = SCR
      STOF(ISTOF + 13) = XR
      STOF(ISTOF + 14) = Ll
      STOF(ISTOF + 15) = Rl
      STOF(ISTOF + 16) = Vpoc_rms
      STOF(ISTOF + 17) = Ppoc
      STOF(ISTOF + 18) = Qpoc
      STOF(ISTOF + 19) = Ipoc_rms
      STOF(ISTOF + 20) = Vsource
      STOF(ISTOF + 21) = Pref_pu
      STOF(ISTOF + 22) = Qref_pu
      STOF(ISTOF + 23) = PFref
      STOF(ISTOF + 24) = Vref_pu
      STOI(ISTOI + 2) = IT_2
      STOI(ISTOI + 3) = IT_3
      STOI(ISTOI + 4) = IT_4
      STOI(ISTOI + 5) = IT_5
      STOI(ISTOI + 6) = IT_6
      STOI(ISTOI + 7) = Fault
      STOI(ISTOI + 8) = Fault_Type
      STOF(ISTOF + 25) = RT_5
      STOF(ISTOF + 26) = RT_6
      STOF(ISTOF + 27) = Fnom
      STOF(ISTOF + 28) = RT_7
      STOF(ISTOF + 29) = Rl1
      STOF(ISTOF + 30) = Rl2
      STOF(ISTOF + 31) = Ll1
      STOF(ISTOF + 32) = Ll2
      STOF(ISTOF + 33) = RT_8

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 0 + IT_0) = Vpoc(IT_0)
         STOF(ISTOF + 3 + IT_0) = Ipoc(IT_0)
      END DO

! Array (1:34) quantities...
      DO IT_0 = 1,34
         STOF(ISTOF + 33 + IT_0) = RT_9(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    EMTDC_VVDC    ! 
      REAL    P3PH3         ! 
      REAL    Q3PH3         ! 
!     SUBR    DGTL_RMS3     ! '3 Phase Digital RMS Meter'
!     SUBR    DGTL_RMS3A    ! '3 Phase Digital RMS Meter'
!     SUBR    BESSOut       ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices
      INTEGER  NT_1(3), NT_7(3), NT_8(3), NT_9(3)

! Control Signals
      REAL     Vpoc(3), Ipoc(3), Sbase, Vpoc_rms
      REAL     Ppoc, Qpoc, Ipoc_rms, Vsource
      REAL     Fnom, RT_8

! Internal Variables
      INTEGER  BR_S_, BR_MA_, BR_MB_, BR_EA_
      INTEGER  BR_ZA_, BR_CA_, BR_IA_, BR_EB_
      INTEGER  BR_ZB_, BR_CB_, BR_IB_, NA_, NB_
      INTEGER  NAM_, NBM_, NAI_, NBI_, NAIC_
      INTEGER  NBIC_, NS_, IVD1_1
      REAL     RVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC, IT_0    ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      IPGB      = NPGB
      NPGB      = NPGB + 10
      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 29
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 33
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Sbase    = STOF(ISTOF + 11)
      Vpoc_rms = STOF(ISTOF + 16)
      Ppoc     = STOF(ISTOF + 17)
      Qpoc     = STOF(ISTOF + 18)
      Ipoc_rms = STOF(ISTOF + 19)
      Vsource  = STOF(ISTOF + 20)
      Fnom     = STOF(ISTOF + 27)
      RT_8     = STOF(ISTOF + 33)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vpoc(IT_0) = STOF(ISTOF + 0 + IT_0)
         Ipoc(IT_0) = STOF(ISTOF + 3 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_1(IT_0) = NODE(INODE + 0 + IT_0)
         NT_7(IT_0) = NODE(INODE + 18 + IT_0)
         NT_8(IT_0) = NODE(INODE + 21 + IT_0)
         NT_9(IT_0) = NODE(INODE + 24 + IT_0)
      END DO

!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Main.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 'MVA'

      Sbase = 200.0

! 20:[const] Real Constant 'Hz'

      Fnom = 50.0

! 30:[const] Real Constant 'kV'

      Vsource = 500.0

! 40:[RZ] Rezonance module 





      NA_ = -1
      NB_ = -1
      NAM_ = -1
      NBM_ = -1
      NAI_ = -1
      NBI_ = -1
      NAIC_ = -1
      NBIC_ = -1
      NS_ = -1

      BR_S_ = -1
      BR_MA_ = -1
      BR_MB_ = -1

      BR_EA_ = -1
      BR_ZA_ = -1
      BR_CA_ = -1
      BR_IA_ = -1

      BR_ZB_ = -1
      BR_CB_ = -1
      BR_EB_ = -1
      BR_IB_ = -1

      NA_ = NT_1(1)
      NB_ = NT_7(1)
      NAM_ = NT_8(1)
      NBM_ = NT_9(1)

      BR_MA_ =  (IBRCH+25)
      BR_MB_ =  (IBRCH+28)



      BR_EA_ =  (IBRCH+31)


      CALL COMPONENT_ID(ICALL_NO,2101249384)
      CALL OUT_RZ(1, 0, 0, 0, 1, 1,1, 0.0, 5.0, SS, BR_S_, BR_MA_, BR_MB&
     &_,BR_EA_, BR_EB_, BR_CA_, BR_CB_, BR_IA_, BR_IB_, BR_ZA_, BR_ZB_,N&
     &A_, NB_, NS_, 500.0, 100.0, 100.0, 50.0,(0.02, 0.1), (0.02, 0.1), &
     &1.0e-06, 1.0e-12, 1.0e-20,1, 0, 0,0.0, 1.0, 10.0, 0.0,1.0, 10.0, 1&
     &.0,0.0, 0.0, 0.001,3.0, 1.0, 0.5,0, 0, 0, 0,1, 1.0, 1000.0, 1.0, 1&
     &001, 1001, 1,0.0, 0.0, 0.0, 0.0, 0.25,5, "_", "in_arr_f.txt")

! 70:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      Ipoc(1) = ( CBR((IBRCH+1), SS))
      Ipoc(2) = ( CBR((IBRCH+2), SS))
      Ipoc(3) = ( CBR((IBRCH+3), SS))
      Vpoc(1) = EMTDC_VVDC(SS, NT_7(1), 0)
      Vpoc(2) = EMTDC_VVDC(SS, NT_7(2), 0)
      Vpoc(3) = EMTDC_VVDC(SS, NT_7(3), 0)
      RVD1_1 = RTCF(IVD1_1) * P3PH3(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,448234021,RVD1_1,"Pd")
      Ppoc = RVD1_1
      RVD1_1 = RTCF(IVD1_1) * Q3PH3(SS, (IBRCH+1), (IBRCH+2), (IBRCH+3),&
     &RTCF(IVD1_1+2),0)
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,448234021,RVD1_1,"Qd")
      Qpoc = RVD1_1
      CALL DGTL_RMS3(256,SS,NT_7(1),NT_7(2),NT_7(3),RTCF(IVD1_1+3),1.0,0&
     &.0,RVD1_1)
      RVD1_1 = RTCF(IVD1_1+1)*RVD1_1
      IF (UPDATE_AG) CALL PSCAD_AGR2(ICALL_NO,448234021,RVD1_1,"Vd")
      Vpoc_rms = RVD1_1
      CALL DGTL_RMS3A(256,( CBR((IBRCH+1), SS)),( CBR((IBRCH+2), SS)),( &
     &CBR((IBRCH+3), SS)),RTCF(IVD1_1+3),RTCF(IVD1_1+4),0.0,RVD1_1)
      Ipoc_rms = RVD1_1
      IF (FIRSTSTEP) THEN
        CALL PSCAD_AGI2(ICALL_NO,448234021,1,"hide1")
        CALL PSCAD_AGI2(ICALL_NO,448234021,1,"hide2")
      ENDIF

! 140:[const] Real Constant 

      RT_8 = 90.0

! 210:[pgb] Output Channel 'Ppoc'

      PGB(IPGB+1) = Ppoc

! 260:[pgb] Output Channel 'Qpoc'

      PGB(IPGB+2) = Qpoc

! 280:[pgb] Output Channel 'Vpoc'

      DO IVD1_1 = 1, 3
         PGB(IPGB+3+IVD1_1-1) = Vpoc(IVD1_1)
      ENDDO

! 290:[pgb] Output Channel 'Ipoc'

      DO IVD1_1 = 1, 3
         PGB(IPGB+6+IVD1_1-1) = Ipoc(IVD1_1)
      ENDDO

! 300:[pgb] Output Channel 'Vpoc_rms'

      PGB(IPGB+9) = Vpoc_rms

! 310:[pgb] Output Channel 'Ipoc_rms'

      PGB(IPGB+10) = Ipoc_rms

! 380:[BESS]  
      CALL BESSOut()


! 390:[tpflt] Three Phase Fault 
!
! Multi-phase Fault Currents
!

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 11) = Sbase
      STOF(ISTOF + 16) = Vpoc_rms
      STOF(ISTOF + 17) = Ppoc
      STOF(ISTOF + 18) = Qpoc
      STOF(ISTOF + 19) = Ipoc_rms
      STOF(ISTOF + 20) = Vsource
      STOF(ISTOF + 27) = Fnom
      STOF(ISTOF + 33) = RT_8

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 0 + IT_0) = Vpoc(IT_0)
         STOF(ISTOF + 3 + IT_0) = Ipoc(IT_0)
      END DO


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE MainDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    BESSDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1(3), NT_7(3), NT_8(3), NT_9(3)

! Control Signals
      REAL     Sbase, Vsource, Fnom, RT_8

! Internal Variables
      INTEGER  BR_S_, BR_MA_, BR_MB_, BR_EA_
      INTEGER  BR_ZA_, BR_CA_, BR_IA_, BR_EB_
      INTEGER  BR_ZB_, BR_CB_, BR_IB_, NA_, NB_
      INTEGER  NAM_, NBM_, NAI_, NBI_, NAIC_
      INTEGER  NBIC_, NS_
      REAL     RVD1_1, RVD1_2

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER ICX                                 ! Control/Monitoring
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ICX       = NCX
      NCX       = NCX + 10
      INODE     = NNODE + 2
      NNODE     = NNODE + 29
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 33
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_1(IT_0) = NODE(INODE + 0 + IT_0)
         NT_7(IT_0) = NODE(INODE + 18 + IT_0)
         NT_8(IT_0) = NODE(INODE + 21 + IT_0)
         NT_9(IT_0) = NODE(INODE + 24 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 'MVA'
      Sbase = 200.0

! 20:[const] Real Constant 'Hz'
      Fnom = 50.0

! 30:[const] Real Constant 'kV'
      Vsource = 500.0

! 40:[RZ] Rezonance module 




      NA_ = -1
      NB_ = -1
      NAM_ = -1
      NBM_ = -1
      NAI_ = -1
      NBI_ = -1
      NAIC_ = -1
      NBIC_ = -1
      NS_ = -1

      BR_S_ = -1
      BR_MA_ = -1
      BR_MB_ = -1

      BR_EA_ = -1
      BR_ZA_ = -1
      BR_CA_ = -1
      BR_IA_ = -1

      BR_ZB_ = -1
      BR_CB_ = -1
      BR_EB_ = -1
      BR_IB_ = -1

      NA_ = NT_1(1)
      NB_ = NT_7(1)
      NAM_ = NT_8(1)
      NBM_ = NT_9(1)

      BR_MA_ =  (IBRCH+25)
      BR_MB_ =  (IBRCH+28)



      BR_EA_ =  (IBRCH+31)



      CALL COMPONENT_ID(ICALL_NO,2101249384)
      CALL BGN_D_RZ(1, 0, 0, 0, 1, 1,1, 0.0, 5.0, SS, BR_S_, BR_MA_, BR_&
     &MB_,BR_EA_, BR_EB_, BR_CA_, BR_CB_, BR_IA_, BR_IB_, BR_ZA_, BR_ZB_&
     &,NA_, NB_, NS_, 500.0, 100.0, 100.0, 50.0,(0.02, 0.1), (0.02, 0.1)&
     &, 1.0e-06, 1.0e-12, 1.0e-20,1, 0, 0,0.0, 1.0, 10.0, 0.0,1.0, 10.0,&
     & 1.0,0.0, 0.0, 0.001,3.0, 1.0, 0.5,0, 0, 0, 0,1, 1.0, 1000.0, 1.0,&
     & 1001, 1001, 1,0.0, 0.0, 0.0, 0.0, 0.25,5, "_", "in_arr_f.txt")



! 50:[var] Variable Input Slider 'V_source'

! 60:[mult] Multiplier 

! 80:[var] Variable Input Slider 'Pref_pu'

! 90:[var] Variable Input Slider 'F_source'

! 100:[mult] Multiplier 

! 110:[time-sig] Output of Simulation Time 

! 120:[var] Variable Input Slider 'Ph0_source'

! 130:[compare] Single Input Level Comparator 

! 140:[const] Real Constant 
      RT_8 = 90.0

! 150:[var] Variable Input Slider 'Qref_pu'

! 160:[var] Variable Input Slider 'Vref_pu'

! 170:[var] Variable Input Slider 'PFref'

! 180:[var] Variable Input Slider 'SCR'

! 190:[var] Variable Input Slider 'XR'

! 200:[var_pot] Rotary Switch 'Fault Type'

! 320:[Grid_RL_Calc] Grid RL Calc 

! 330:[gain] Gain Block 

! 340:[gain] Gain Block 

! 350:[gain] Gain Block 

! 360:[gain] Gain Block 

! 370:[sumjct] Summing/Differencing Junctions 

! 380:[BESS]  
      CALL BESSDyn_Begin(0.5, 0.05, 100.0, 2.0, Fnom, 0.69, 1.2, 5000.0,&
     & 0.1, 0.002, 0.04, Sbase, Vsource, 33.0)


! 390:[tpflt] Three Phase Fault 
      CALL E3PHFLT1_CFG(10000000000.0,0.0)

! 400:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+22), 0)
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+23), 0)
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+24), 0)

! 410:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+19), 0)
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+20), 0)
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+21), 0)

! 420:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+10), 0)
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+11), 0)
      CALL E_VARRLC1_CFG(0 ,SS ,  (IBRCH+12), 0)

! 430:[varrlc] Variable R, L or C  
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+7), 0)
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+8), 0)
      CALL E_VARRLC1_CFG(1 ,SS ,  (IBRCH+9), 0)

! 440:[source3] Three Phase Voltage Source Model 1 'Source1'
      CALL COMPONENT_ID(ICALL_NO,633943515)
      RVD1_1 = 1.0
      RVD1_2 = 0.1
      CALL ESYS651_CFG(3,1,1,0,0,SS, (IBRCH+4), (IBRCH+5), (IBRCH+6),0,0&
     &,0, Fnom,Fnom,0.0,Vsource,0.0,0.0,Sbase,Vsource, Vsource, 0.001, 0&
     &.0, 2.0, 1.0,1.0,0.1, 1.0,80.0,1.0,0.1)

      RETURN
      END

!=======================================================================

      SUBROUTINE MainOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    BESSOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices
      INTEGER  NT_1(3), NT_7(3), NT_8(3), NT_9(3)

! Control Signals
      REAL     Sbase, Vsource, Fnom, RT_8

! Internal Variables
      INTEGER  BR_S_, BR_MA_, BR_MB_, BR_EA_
      INTEGER  BR_ZA_, BR_CA_, BR_IA_, BR_EB_
      INTEGER  BR_ZB_, BR_CB_, BR_IB_, NA_, NB_
      INTEGER  NAM_, NBM_, NAI_, NBI_, NAIC_
      INTEGER  NBIC_, NS_, IVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER IT_0                                ! Storage Indices
      INTEGER SS, INODE, IBRCH                    ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NCX       = NCX + 0
      INODE     = NNODE + 2
      NNODE     = NNODE + 29
      IBRCH     = NBRCH(SS)
      NBRCH(SS) = NBRCH(SS) + 33
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


! Array (1:3) quantities...
      DO IT_0 = 1,3
         NT_1(IT_0) = NODE(INODE + 0 + IT_0)
         NT_7(IT_0) = NODE(INODE + 18 + IT_0)
         NT_8(IT_0) = NODE(INODE + 21 + IT_0)
         NT_9(IT_0) = NODE(INODE + 24 + IT_0)
      END DO

!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 'MVA'
      Sbase = 200.0

! 20:[const] Real Constant 'Hz'
      Fnom = 50.0

! 30:[const] Real Constant 'kV'
      Vsource = 500.0

! 40:[RZ] Rezonance module 




      NA_ = -1
      NB_ = -1
      NAM_ = -1
      NBM_ = -1
      NAI_ = -1
      NBI_ = -1
      NAIC_ = -1
      NBIC_ = -1
      NS_ = -1

      BR_S_ = -1
      BR_MA_ = -1
      BR_MB_ = -1

      BR_EA_ = -1
      BR_ZA_ = -1
      BR_CA_ = -1
      BR_IA_ = -1

      BR_ZB_ = -1
      BR_CB_ = -1
      BR_EB_ = -1
      BR_IB_ = -1

      NA_ = NT_1(1)
      NB_ = NT_7(1)
      NAM_ = NT_8(1)
      NBM_ = NT_9(1)

      BR_MA_ =  (IBRCH+25)
      BR_MB_ =  (IBRCH+28)



      BR_EA_ =  (IBRCH+31)


      CALL COMPONENT_ID(ICALL_NO,2101249384)
      CALL BGN_O_RZ(1, 0, 0, 0, 1, 1,1, 0.0, 5.0, SS, BR_S_, BR_MA_, BR_&
     &MB_,BR_EA_, BR_EB_, BR_CA_, BR_CB_, BR_IA_, BR_IB_, BR_ZA_, BR_ZB_&
     &,NA_, NB_, NS_, 500.0, 100.0, 100.0, 50.0,(0.02, 0.1), (0.02, 0.1)&
     &, 1.0e-06, 1.0e-12, 1.0e-20,1, 0, 0,0.0, 1.0, 10.0, 0.0,1.0, 10.0,&
     & 1.0,0.0, 0.0, 0.001,3.0, 1.0, 0.5,0, 0, 0, 0,1, 1.0, 1000.0, 1.0,&
     & 1001, 1001, 1,0.0, 0.0, 0.0, 0.0, 0.25,5, "_", "in_arr_f.txt")


! 70:[multimeter] Multimeter 
      IVD1_1 = NRTCF
      NRTCF  = NRTCF + 5
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1) = 1.0
      ENDIF
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+1) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+1) = 1.0
      ENDIF
      RTCF(IVD1_1+2) = 0.02
      RTCF(IVD1_1+3) = Fnom
      IF (ABS(1.0) .GT. 1.0E-20) THEN
        RTCF(IVD1_1+4) = 1.0/ABS(1.0)
      ELSE
        RTCF(IVD1_1+4) = 1.0
      ENDIF

! 140:[const] Real Constant 
      RT_8 = 90.0

! 210:[pgb] Output Channel 'Ppoc'

! 260:[pgb] Output Channel 'Qpoc'

! 280:[pgb] Output Channel 'Vpoc'

! 290:[pgb] Output Channel 'Ipoc'

! 300:[pgb] Output Channel 'Vpoc_rms'

! 310:[pgb] Output Channel 'Ipoc_rms'

! 380:[BESS]  
      CALL BESSOut_Begin(0.5, 0.05, 100.0, 2.0, Fnom, 0.69, 1.2, 5000.0,&
     & 0.1, 0.002, 0.04, Sbase, Vsource, 33.0)


      RETURN
      END

