!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Measurement_Filter
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Measurement_FilterDyn(Vgabc, Igabc, Vdclink, Vg_abc_,  &
     &   Ig_abc_, V_dclink_, Itabc, It_abc_, Freq_ACCurCutOff,          &
     &   Freq_ACVolCutOff, Freq_DCVolCutOff, zeta)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    CMPX2ORD      ! Second Order Complex Pole

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Vgabc(3), Igabc(3)
      REAL,    INTENT(IN)  :: Vdclink, Itabc(3)
      REAL,    INTENT(IN)  :: Freq_ACCurCutOff
      REAL,    INTENT(IN)  :: Freq_ACVolCutOff
      REAL,    INTENT(IN)  :: Freq_DCVolCutOff
      REAL,    INTENT(IN)  :: zeta
      REAL,    INTENT(OUT) :: Vg_abc_(3)! Aliases: Vg_abc
      REAL,    INTENT(OUT) :: Ig_abc_(3)! Aliases: Ig_abc
      REAL,    INTENT(OUT) :: V_dclink_! Aliases: V_dclink
      REAL,    INTENT(OUT) :: It_abc_(3)! Aliases: It_abc

! Electrical Node Indices

! Control Signals

! Internal Variables
      INTEGER  IVD1_1
      REAL     RVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF, IT_0                         ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 24
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      V_dclink_ = STOF(ISTOF + 14)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vg_abc_(IT_0) = STOF(ISTOF + 7 + IT_0)
         Ig_abc_(IT_0) = STOF(ISTOF + 10 + IT_0)
         It_abc_(IT_0) = STOF(ISTOF + 17 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Measurement_Filter.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 90:[complex] Second Order Complex Pole 
! Second Order Complex Pole
      RVD1_1 = TWO_PI*Freq_ACCurCutOff
      DO IVD1_1 = 1,3
        It_abc_(IVD1_1) = CMPX2ORD(4, 1.0, zeta, RVD1_1, Itabc(IVD1_1))
      ENDDO
!

! 100:[complex] Second Order Complex Pole 
! Second Order Complex Pole
      RVD1_1 = TWO_PI*Freq_DCVolCutOff
      V_dclink_ = CMPX2ORD(4, 1.0, zeta, RVD1_1, Vdclink)
!

! 110:[complex] Second Order Complex Pole 
! Second Order Complex Pole
      RVD1_1 = TWO_PI*Freq_ACCurCutOff
      DO IVD1_1 = 1,3
        Ig_abc_(IVD1_1) = CMPX2ORD(4, 1.0, zeta, RVD1_1, Igabc(IVD1_1))
      ENDDO
!

! 140:[complex] Second Order Complex Pole 
! Second Order Complex Pole
      RVD1_1 = TWO_PI*Freq_ACVolCutOff
      DO IVD1_1 = 1,3
        Vg_abc_(IVD1_1) = CMPX2ORD(4, 1.0, zeta, RVD1_1, Vgabc(IVD1_1))
      ENDDO
!

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 7) = Vdclink
      STOF(ISTOF + 14) = V_dclink_
      STOF(ISTOF + 21) = Freq_ACCurCutOff
      STOF(ISTOF + 22) = Freq_ACVolCutOff
      STOF(ISTOF + 23) = Freq_DCVolCutOff
      STOF(ISTOF + 24) = zeta

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 0 + IT_0) = Vgabc(IT_0)
         STOF(ISTOF + 3 + IT_0) = Igabc(IT_0)
         STOF(ISTOF + 7 + IT_0) = Vg_abc_(IT_0)
         STOF(ISTOF + 10 + IT_0) = Ig_abc_(IT_0)
         STOF(ISTOF + 14 + IT_0) = Itabc(IT_0)
         STOF(ISTOF + 17 + IT_0) = It_abc_(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Vg_abc_  is output
      !Ig_abc_  is output
      !V_dclink_ is output
      !It_abc_  is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Measurement_FilterOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------



!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Measurement_Filter.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------



!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Measurement_FilterDyn_Begin(zeta)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: zeta

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 90:[complex] Second Order Complex Pole 

! 100:[complex] Second Order Complex Pole 

! 110:[complex] Second Order Complex Pole 

! 140:[complex] Second Order Complex Pole 

      RETURN
      END

!=======================================================================

      SUBROUTINE Measurement_FilterOut_Begin(zeta)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: zeta

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


      RETURN
      END

