!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Parameters_Bases
! Description   : 
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Parameters_BasesDyn(Sbase1, Fnom, Vac_nom, Vdc_nom,    &
     &   iVb_, iIb_, iVdc_)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(OUT) :: iVb_! Aliases: iVb
      REAL,    INTENT(OUT) :: iIb_! Aliases: iIb
      REAL,    INTENT(OUT) :: iVdc_! Aliases: iVdc

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_2, RT_3, RT_4, RT_5, RT_6
      REAL     RT_7, RT_8

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOF                               ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOF     = NSTOF
      NSTOF     = NSTOF + 15
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      iVb_     = STOF(ISTOF + 5)
      iIb_     = STOF(ISTOF + 6)
      iVdc_    = STOF(ISTOF + 7)
      RT_1     = STOF(ISTOF + 8)
      RT_2     = STOF(ISTOF + 9)
      RT_3     = STOF(ISTOF + 10)
      RT_4     = STOF(ISTOF + 11)
      RT_5     = STOF(ISTOF + 12)
      RT_6     = STOF(ISTOF + 13)
      RT_7     = STOF(ISTOF + 14)
      RT_8     = STOF(ISTOF + 15)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Parameters_Bases.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[const] Real Constant 
      RT_1 = 1.0

! 50:[const] Real Constant 
      RT_7 = 1.0

! 70:[const] Real Constant 
      RT_8 = 1.0

! 80:[div] Divider 
      IF (ABS(Vdc_nom) .LT. 1.0E-100) THEN
         IF (Vdc_nom .LT. 0.0)  THEN
            iVdc_ = -1.0E100 * RT_8
         ELSE
            iVdc_ =  1.0E100 * RT_8
         ENDIF
      ELSE
         iVdc_ = RT_8 / Vdc_nom
      ENDIF

! 90:[div] Divider 
      IF (ABS(Vac_nom) .LT. 1.0E-100) THEN
         IF (Vac_nom .LT. 0.0)  THEN
            RT_4 = -1.0E100 * Sbase1
         ELSE
            RT_4 =  1.0E100 * Sbase1
         ENDIF
      ELSE
         RT_4 = Sbase1 / Vac_nom
      ENDIF

! 100:[const] Real Constant 
      RT_3 = 0.81649658

! 110:[const] Real Constant 
      RT_6 = 0.81649658

! 120:[mult] Multiplier 
      RT_5 = RT_4 * RT_6

! 130:[mult] Multiplier 
      RT_2 = Vac_nom * RT_3

! 140:[div] Divider 
      IF (ABS(RT_5) .LT. 1.0E-100) THEN
         IF (RT_5 .LT. 0.0)  THEN
            iIb_ = -1.0E100 * RT_7
         ELSE
            iIb_ =  1.0E100 * RT_7
         ENDIF
      ELSE
         iIb_ = RT_7 / RT_5
      ENDIF

! 170:[div] Divider 
      IF (ABS(RT_2) .LT. 1.0E-100) THEN
         IF (RT_2 .LT. 0.0)  THEN
            iVb_ = -1.0E100 * RT_1
         ELSE
            iVb_ =  1.0E100 * RT_1
         ENDIF
      ELSE
         iVb_ = RT_1 / RT_2
      ENDIF

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Sbase1
      STOF(ISTOF + 2) = Fnom
      STOF(ISTOF + 3) = Vac_nom
      STOF(ISTOF + 4) = Vdc_nom
      STOF(ISTOF + 5) = iVb_
      STOF(ISTOF + 6) = iIb_
      STOF(ISTOF + 7) = iVdc_
      STOF(ISTOF + 8) = RT_1
      STOF(ISTOF + 9) = RT_2
      STOF(ISTOF + 10) = RT_3
      STOF(ISTOF + 11) = RT_4
      STOF(ISTOF + 12) = RT_5
      STOF(ISTOF + 13) = RT_6
      STOF(ISTOF + 14) = RT_7
      STOF(ISTOF + 15) = RT_8


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !iVb_     is output
      !iIb_     is output
      !iVdc_    is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Parameters_BasesOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_3, RT_6, RT_7, RT_8

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 8)
      RT_3     = STOF(ISTOF + 10)
      RT_6     = STOF(ISTOF + 13)
      RT_7     = STOF(ISTOF + 14)
      RT_8     = STOF(ISTOF + 15)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Parameters_Bases.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[const] Real Constant 

      RT_1 = 1.0

! 50:[const] Real Constant 

      RT_7 = 1.0

! 70:[const] Real Constant 

      RT_8 = 1.0

! 100:[const] Real Constant 

      RT_3 = 0.81649658

! 110:[const] Real Constant 

      RT_6 = 0.81649658

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 8) = RT_1
      STOF(ISTOF + 10) = RT_3
      STOF(ISTOF + 13) = RT_6
      STOF(ISTOF + 14) = RT_7
      STOF(ISTOF + 15) = RT_8


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Parameters_BasesDyn_Begin(Sbase1, Fnom, Vac_nom,       &
     &   Vdc_nom)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_3, RT_6, RT_7, RT_8

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[const] Real Constant 
      RT_1 = 1.0

! 50:[const] Real Constant 
      RT_7 = 1.0

! 70:[const] Real Constant 
      RT_8 = 1.0

! 80:[div] Divider 

! 90:[div] Divider 

! 100:[const] Real Constant 
      RT_3 = 0.81649658

! 110:[const] Real Constant 
      RT_6 = 0.81649658

! 120:[mult] Multiplier 

! 130:[mult] Multiplier 

! 140:[div] Divider 

! 170:[div] Divider 

      RETURN
      END

!=======================================================================

      SUBROUTINE Parameters_BasesOut_Begin(Sbase1, Fnom, Vac_nom,       &
     &   Vdc_nom)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_3, RT_6, RT_7, RT_8

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 30:[const] Real Constant 
      RT_1 = 1.0

! 50:[const] Real Constant 
      RT_7 = 1.0

! 70:[const] Real Constant 
      RT_8 = 1.0

! 100:[const] Real Constant 
      RT_3 = 0.81649658

! 110:[const] Real Constant 
      RT_6 = 0.81649658

      RETURN
      END

