!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : RPC_PI
! Description   : RPC (PI)
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE RPC_PIDyn(Q_pu, Qref_pu, dVref_pu_, Enable, Freeze,    &
     &   Ki_rpc, Kp_rpc)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    LIMIT         ! Hard Limiter
!     SUBR    PI_AntiWindUpDyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, Freeze
      REAL,    INTENT(IN)  :: Q_pu, Qref_pu
      REAL,    INTENT(IN)  :: Ki_rpc, Kp_rpc
      REAL,    INTENT(OUT) :: dVref_pu_! Aliases: dVref_pu

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4
      REAL     RT_1, RT_2, RT_3, Trpc, RT_4, RT_5

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF                        ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 6
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 11
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      dVref_pu_ = STOF(ISTOF + 3)
      RT_1     = STOF(ISTOF + 6)
      RT_2     = STOF(ISTOF + 7)
      IT_1     = STOI(ISTOI + 3)
      IT_2     = STOI(ISTOI + 4)
      RT_3     = STOF(ISTOF + 8)
      Trpc     = STOF(ISTOF + 9)
      RT_4     = STOF(ISTOF + 10)
      IT_3     = STOI(ISTOI + 5)
      RT_5     = STOF(ISTOF + 11)
      IT_4     = STOI(ISTOI + 6)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'RPC_PI.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[consti] Integer Constant 
      IT_3 = 1

! 30:[inv] Interpolated Logic Inverter 
      IF (IT_3 .NE. 0) THEN
         IT_2 = 0
      ELSE
         IT_2 = 1
      ENDIF

! 50:[sumjct] Summing/Differencing Junctions 
      RT_3 = + Qref_pu - Q_pu

! 70:[const] Real Constant 
      RT_4 = 1.0

! 110:[gain] Gain Block 
!  Gain
      RT_1 = REAL(Enable) * RT_3

! 120:[div] Divider 
      IF (ABS(Ki_rpc) .LT. 1.0E-100) THEN
         IF (Ki_rpc .LT. 0.0)  THEN
            Trpc = -1.0E100 * RT_4
         ELSE
            Trpc =  1.0E100 * RT_4
         ENDIF
      ELSE
         Trpc = RT_4 / Ki_rpc
      ENDIF

! 130:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (-0.25 .LE. 0.25) THEN
        dVref_pu_ = LIMIT(-0.25, 0.25, RT_2)
      ELSE
        dVref_pu_ = RT_2
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,907359494,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 140:[logic_mult] Multiple Input Logic Gate 
!
! Multi input OR gate
!
      IF ( (Freeze .NE. 0) .OR. (IT_4 .NE. 0) ) THEN
        IT_1 = 1
      ELSE
        IT_1 = 0
      ENDIF

! 150:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn(RT_1, RT_2, IT_1, IT_2, Kp_rpc, Trpc, 1.0, 1&
     &.0, -1.0)


! 160:[sumjct] Summing/Differencing Junctions 
      RT_5 = + RT_2 - dVref_pu_

! 170:[range] Range Comparator 
!  Band_Compare
      IF (RT_5 .LT. 0.0) THEN
         IT_4 = NINT(1.0)
      ELSE IF (RT_5 .LE. 0.0) THEN
         IT_4 = NINT(0.0)
      ELSE
         IT_4 = NINT(1.0)
      ENDIF
!

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 1) = Q_pu
      STOF(ISTOF + 2) = Qref_pu
      STOF(ISTOF + 3) = dVref_pu_
      STOI(ISTOI + 1) = Enable
      STOI(ISTOI + 2) = Freeze
      STOF(ISTOF + 4) = Ki_rpc
      STOF(ISTOF + 5) = Kp_rpc
      STOF(ISTOF + 6) = RT_1
      STOF(ISTOF + 7) = RT_2
      STOI(ISTOI + 3) = IT_1
      STOI(ISTOI + 4) = IT_2
      STOF(ISTOF + 8) = RT_3
      STOF(ISTOF + 9) = Trpc
      STOF(ISTOF + 10) = RT_4
      STOI(ISTOI + 5) = IT_3
      STOF(ISTOF + 11) = RT_5
      STOI(ISTOI + 6) = IT_4


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !dVref_pu_ is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE RPC_PIOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      INTEGER  IT_3
      REAL     RT_4

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_4     = STOF(ISTOF + 10)
      IT_3     = STOI(ISTOI + 5)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'RPC_PI.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[consti] Integer Constant 

      IT_3 = 1

! 70:[const] Real Constant 

      RT_4 = 1.0

! 150:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 10) = RT_4
      STOI(ISTOI + 5) = IT_3


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE RPC_PIDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_3
      REAL     RT_4

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[consti] Integer Constant 
      IT_3 = 1

! 30:[inv] Interpolated Logic Inverter 

! 50:[sumjct] Summing/Differencing Junctions 

! 70:[const] Real Constant 
      RT_4 = 1.0

! 110:[gain] Gain Block 

! 120:[div] Divider 

! 130:[hardlimit] Hard Limiter 

! 150:[PI_AntiWindUp]  
      CALL PI_AntiWindUpDyn_Begin()


! 160:[sumjct] Summing/Differencing Junctions 

! 170:[range] Range Comparator 

      RETURN
      END

!=======================================================================

      SUBROUTINE RPC_PIOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    PI_AntiWindUpOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      INTEGER  IT_3
      REAL     RT_4

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 20:[consti] Integer Constant 
      IT_3 = 1

! 70:[const] Real Constant 
      RT_4 = 1.0

! 150:[PI_AntiWindUp]  
      CALL PI_AntiWindUpOut_Begin()


      RETURN
      END

