!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Startup
! Description   : Startup
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE StartupDyn(VBRKin_pu, VBRKout_pu, Pblst_pu_, DBlk,     &
     &   Voutrms_pu, APC, Vinrms_pu, Enable_, DBlk_OCL_, BRK_, GTB_,    &
     &   Pblstref_d, Pblstref_n, dAngTh, dVTh)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    PHAS3P        ! Three Phase Relative Phase Difference
!     SUBR    EMTDC_XONDLAY  ! 'Delay Function with Interpolation'
      REAL    CMPX2ORD      ! Second Order Complex Pole

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: DBlk, APC
      REAL,    INTENT(IN)  :: VBRKin_pu(3)
      REAL,    INTENT(IN)  :: VBRKout_pu(3)
      REAL,    INTENT(IN)  :: Voutrms_pu
      REAL,    INTENT(IN)  :: Vinrms_pu
      REAL,    INTENT(IN)  :: Pblstref_d
      REAL,    INTENT(IN)  :: Pblstref_n, dAngTh
      REAL,    INTENT(IN)  :: dVTh
      INTEGER, INTENT(OUT) :: Enable_! Aliases: Enable
      INTEGER, INTENT(OUT) :: DBlk_OCL_! Aliases: DBlk_OCL
      INTEGER, INTENT(OUT) :: BRK_! Aliases: BRK
      INTEGER, INTENT(OUT) :: GTB_! Aliases: GTB
      REAL,    INTENT(OUT) :: Pblst_pu_! Aliases: Pblst_pu

! Electrical Node Indices

! Control Signals
      INTEGER  IT_1, IT_2, IT_3, IT_4, IT_5
      REAL     RT_1, RT_2, RT_3, RT_4, dAngThn
      REAL     dVThn, dVBRK_pu, dAng

! Internal Variables
      REAL     RVD1_1, RVD1_2, RVD2_1(2)
      REAL     RVD2_2(2)

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 11
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 21
      IPGB      = NPGB
      NPGB      = NPGB + 3
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      Pblst_pu_ = STOF(ISTOF + 7)
      Enable_  = STOI(ISTOI + 3)
      DBlk_OCL_ = STOI(ISTOI + 4)
      BRK_     = STOI(ISTOI + 5)
      GTB_     = STOI(ISTOI + 6)
      RT_1     = STOF(ISTOF + 14)
      RT_2     = STOF(ISTOF + 15)
      RT_3     = STOF(ISTOF + 16)
      RT_4     = STOF(ISTOF + 17)
      IT_1     = STOI(ISTOI + 7)
      IT_2     = STOI(ISTOI + 8)
      IT_3     = STOI(ISTOI + 9)
      IT_4     = STOI(ISTOI + 10)
      IT_5     = STOI(ISTOI + 11)
      dAngThn  = STOF(ISTOF + 18)
      dVThn    = STOF(ISTOF + 19)
      dVBRK_pu = STOF(ISTOF + 20)
      dAng     = STOF(ISTOF + 21)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Startup.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[inv] Interpolated Logic Inverter 
      IF (DBlk .NE. 0) THEN
         GTB_ = 0
      ELSE
         GTB_ = 1
      ENDIF

! 60:[phasediff] Phase Difference 
!  3 Phase Relative Phase Difference
      RT_3 = PHAS3P(VBRKout_pu(1),VBRKout_pu(2),VBRKout_pu(3),VBRKin_pu(&
     &1),VBRKin_pu(2),VBRKin_pu(3), RVD1_1, RVD1_2)
!

! 80:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(DBlk)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0,RVD2_1,RVD2_2)
      Enable_ = NINT(RVD2_2(1))

! 100:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(Enable_)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.01,RVD2_1,RVD2_2)
      IT_3 = NINT(RVD2_2(1))

! 130:[sumjct] Summing/Differencing Junctions 
      dVBRK_pu = + Voutrms_pu - Vinrms_pu

! 140:[const] Real Constant 
      RT_1 = 0.0

! 160:[gain] Gain Block 
!  Gain
      dAngThn = -1.0 * dAngTh

! 180:[gain] Gain Block 
!  Gain
      dVThn = -1.0 * dVTh

! 190:[select] Two Input Selector 
      IF (APC .EQ. RTCI(NRTCI)) THEN
         RT_2 = Pblstref_d
      ELSE
         RT_2 = Pblstref_n
      ENDIF
      NRTCI = NRTCI + 1
!

! 220:[pgb] Output Channel 'dVBRK_pu'

      PGB(IPGB+1) = dVBRK_pu

! 230:[mod] MOD Function 
!  MOD Function
      RT_4 = MOD(RT_3,3.14159265359)

! 240:[range] Range Comparator 
!  Band_Compare
      IF (dVBRK_pu .LT. dVThn) THEN
         IT_2 = NINT(0.0)
      ELSE IF (dVBRK_pu .LE. dVTh) THEN
         IT_2 = NINT(1.0)
      ELSE
         IT_2 = NINT(0.0)
      ENDIF
!

! 250:[complex] Second Order Complex Pole 
! Second Order Complex Pole
      RVD1_1 = TWO_PI*300.0
      dAng = CMPX2ORD(4, 1.0, 0.707, RVD1_1, RT_4)
!

! 260:[range] Range Comparator 
!  Band_Compare
      IF (dAng .LT. dAngThn) THEN
         IT_4 = NINT(0.0)
      ELSE IF (dAng .LE. dAngTh) THEN
         IT_4 = NINT(1.0)
      ELSE
         IT_4 = NINT(0.0)
      ENDIF
!

! 270:[logic_mult] Multiple Input Logic Gate 
!
! Multi input AND gate
!
      IF ( (IT_4 .NE. 0) .AND. (IT_3 .NE. 0) .AND. (IT_2 .NE. 0) ) THEN
        IT_1 = 1
      ELSE
        IT_1 = 0
      ENDIF

! 280:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(IT_1)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0,RVD2_1,RVD2_2)
      IT_5 = NINT(RVD2_2(1))

! 290:[delay] Binary ON Delay with Interpolation 
!
      RVD2_1(1) = FLOAT(IT_5)
      RVD2_1(2) = 0.0
      CALL EMTDC_XONDLAY(0,0.0,RVD2_1,RVD2_2)
      DBlk_OCL_ = NINT(RVD2_2(1))

! 300:[select] Two Input Selector 
      IF (DBlk_OCL_ .EQ. RTCI(NRTCI)) THEN
         Pblst_pu_ = RT_1
      ELSE
         Pblst_pu_ = RT_2
      ENDIF
      NRTCI = NRTCI + 1
!

! 310:[inv] Interpolated Logic Inverter 
      IF (IT_5 .NE. 0) THEN
         BRK_ = 0
      ELSE
         BRK_ = 1
      ENDIF

! 320:[pgb] Output Channel 'Pblst_pu_'

      PGB(IPGB+2) = Pblst_pu_

! 330:[pgb] Output Channel 'dAng'

      PGB(IPGB+3) = dAng

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 7) = Pblst_pu_
      STOI(ISTOI + 1) = DBlk
      STOF(ISTOF + 8) = Voutrms_pu
      STOI(ISTOI + 2) = APC
      STOF(ISTOF + 9) = Vinrms_pu
      STOI(ISTOI + 3) = Enable_
      STOI(ISTOI + 4) = DBlk_OCL_
      STOI(ISTOI + 5) = BRK_
      STOI(ISTOI + 6) = GTB_
      STOF(ISTOF + 10) = Pblstref_d
      STOF(ISTOF + 11) = Pblstref_n
      STOF(ISTOF + 12) = dAngTh
      STOF(ISTOF + 13) = dVTh
      STOF(ISTOF + 14) = RT_1
      STOF(ISTOF + 15) = RT_2
      STOF(ISTOF + 16) = RT_3
      STOF(ISTOF + 17) = RT_4
      STOI(ISTOI + 7) = IT_1
      STOI(ISTOI + 8) = IT_2
      STOI(ISTOI + 9) = IT_3
      STOI(ISTOI + 10) = IT_4
      STOI(ISTOI + 11) = IT_5
      STOF(ISTOF + 18) = dAngThn
      STOF(ISTOF + 19) = dVThn
      STOF(ISTOF + 20) = dVBRK_pu
      STOF(ISTOF + 21) = dAng

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 0 + IT_0) = VBRKin_pu(IT_0)
         STOF(ISTOF + 3 + IT_0) = VBRKout_pu(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Pblst_pu_ is output
      !Enable_  is output
      !DBlk_OCL_ is output
      !BRK_     is output
      !GTB_     is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE StartupOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 3
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 14)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Startup.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 140:[const] Real Constant 

      RT_1 = 0.0

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 14) = RT_1


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE StartupDyn_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 40:[inv] Interpolated Logic Inverter 

! 60:[phasediff] Phase Difference 

! 80:[delay] Binary ON Delay with Interpolation 

! 100:[delay] Binary ON Delay with Interpolation 

! 130:[sumjct] Summing/Differencing Junctions 

! 140:[const] Real Constant 
      RT_1 = 0.0

! 160:[gain] Gain Block 

! 180:[gain] Gain Block 

! 190:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 220:[pgb] Output Channel 'dVBRK_pu'

! 230:[mod] MOD Function 

! 240:[range] Range Comparator 

! 250:[complex] Second Order Complex Pole 

! 260:[range] Range Comparator 

! 280:[delay] Binary ON Delay with Interpolation 

! 290:[delay] Binary ON Delay with Interpolation 

! 300:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 310:[inv] Interpolated Logic Inverter 

! 320:[pgb] Output Channel 'Pblst_pu_'

! 330:[pgb] Output Channel 'dAng'

      RETURN
      END

!=======================================================================

      SUBROUTINE StartupOut_Begin()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------


!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments

! Electrical Node Indices

! Control Signals
      REAL     RT_1

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 140:[const] Real Constant 
      RT_1 = 0.0

      RETURN
      END

