!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : UC
! Description   : Unit Controller
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE UCDyn(Igabc_kA, Vdc_kV, Vgabc_kV, Qpcc_pu, Vpcc_pu,    &
     &   Ppcc_pu, Sig_GSC_, Pcmd_pu, Qcmd_pu, Enable, APC, RPC, VRT,    &
     &   Itabc_kA, Sbase1, Fnom, Vac_nom, Vdc_nom, L_GSC_pu, R_GSC_pu,  &
     &   C_GSC_pu, Freq_PWM_GSC, SCRmax, Pblst_pu, Vgabcpu_, Igabcpu_)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    Parameters_BasesDyn  ! 
!     SUBR    Measurement_FilterDyn  ! 
!     SUBR    GSCDyn        ! Grid Side Converter Controller

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, APC, RPC
      INTEGER, INTENT(IN)  :: VRT
      REAL,    INTENT(IN)  :: Igabc_kA(3), Vdc_kV
      REAL,    INTENT(IN)  :: Vgabc_kV(3)
      REAL,    INTENT(IN)  :: Qpcc_pu, Vpcc_pu
      REAL,    INTENT(IN)  :: Ppcc_pu, Pcmd_pu
      REAL,    INTENT(IN)  :: Qcmd_pu
      REAL,    INTENT(IN)  :: Itabc_kA(3), Sbase1
      REAL,    INTENT(IN)  :: Fnom, Vac_nom
      REAL,    INTENT(IN)  :: Vdc_nom, L_GSC_pu
      REAL,    INTENT(IN)  :: R_GSC_pu, C_GSC_pu
      REAL,    INTENT(IN)  :: Freq_PWM_GSC
      REAL,    INTENT(IN)  :: SCRmax, Pblst_pu
      REAL,    INTENT(OUT) :: Sig_GSC_(5)! Aliases: Sig_GSC
      REAL,    INTENT(OUT) :: Vgabcpu_(3)! Aliases: Vgabcpu
      REAL,    INTENT(OUT) :: Igabcpu_(3)! Aliases: Igabcpu

! Electrical Node Indices

! Control Signals
      REAL     iVb, iIb, iVdc, RT_1, Itabcpu(3)
      REAL     Vgabc_pu(3), Igabc_pu(3), Vdc_pu
      REAL     Itabc_pu(3), hGPWM, dGPWM

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 4
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 55
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      iVb      = STOF(ISTOF + 37)
      iIb      = STOF(ISTOF + 38)
      iVdc     = STOF(ISTOF + 39)
      RT_1     = STOF(ISTOF + 40)
      Vdc_pu   = STOF(ISTOF + 50)
      hGPWM    = STOF(ISTOF + 54)
      dGPWM    = STOF(ISTOF + 55)

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Vgabcpu_(IT_0) = STOF(ISTOF + 30 + IT_0)
         Igabcpu_(IT_0) = STOF(ISTOF + 33 + IT_0)
         Itabcpu(IT_0) = STOF(ISTOF + 40 + IT_0)
         Vgabc_pu(IT_0) = STOF(ISTOF + 43 + IT_0)
         Igabc_pu(IT_0) = STOF(ISTOF + 46 + IT_0)
         Itabc_pu(IT_0) = STOF(ISTOF + 50 + IT_0)
      END DO

! Array (1:5) quantities...
      DO IT_0 = 1,5
         Sig_GSC_(IT_0) = STOF(ISTOF + 10 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'UC.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 190:[gain] Gain Block 
!  Gain
      dGPWM = 2.0 * Freq_PWM_GSC

! 250:[gain] Gain Block 
!  Gain
      hGPWM = 0.5 * Freq_PWM_GSC

! 260:[Parameters_Bases]  'Parameters_1_1'
      CALL Parameters_BasesDyn(Sbase1, Fnom, Vac_nom, Vdc_nom, iVb, iIb,&
     & iVdc)


! 270:[gain] Gain Block 
!  Gain
      Igabcpu_ = iIb * Igabc_kA

! 280:[gain] Gain Block 
!  Gain
      Vgabcpu_ = iVb * Vgabc_kV

! 290:[gain] Gain Block 
!  Gain
      RT_1 = iVdc * Vdc_kV

! 300:[gain] Gain Block 
!  Gain
      Itabcpu = iIb * Itabc_kA

! 310:[Measurement_Filter]  
      CALL Measurement_FilterDyn(Vgabcpu_, Igabcpu_, RT_1, Vgabc_pu, Iga&
     &bc_pu, Vdc_pu, Itabcpu, Itabc_pu, dGPWM, hGPWM, hGPWM, 0.707)


! 320:[GSC] Grid Side Converter Controller 
      CALL GSCDyn(Vgabc_pu, Igabc_pu, Qcmd_pu, Vdc_pu, Sig_GSC_, Enable,&
     & Ppcc_pu, Qpcc_pu, Pcmd_pu, APC, RPC, VRT, Itabc_pu, Sbase1, Fnom,&
     & Vac_nom, Vdc_nom, L_GSC_pu, R_GSC_pu, C_GSC_pu, Freq_PWM_GSC, SCR&
     &max, Pblst_pu)


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 4) = Vdc_kV
      STOF(ISTOF + 8) = Qpcc_pu
      STOF(ISTOF + 9) = Vpcc_pu
      STOF(ISTOF + 10) = Ppcc_pu
      STOF(ISTOF + 16) = Pcmd_pu
      STOF(ISTOF + 17) = Qcmd_pu
      STOI(ISTOI + 1) = Enable
      STOI(ISTOI + 2) = APC
      STOI(ISTOI + 3) = RPC
      STOI(ISTOI + 4) = VRT
      STOF(ISTOF + 21) = Sbase1
      STOF(ISTOF + 22) = Fnom
      STOF(ISTOF + 23) = Vac_nom
      STOF(ISTOF + 24) = Vdc_nom
      STOF(ISTOF + 25) = L_GSC_pu
      STOF(ISTOF + 26) = R_GSC_pu
      STOF(ISTOF + 27) = C_GSC_pu
      STOF(ISTOF + 28) = Freq_PWM_GSC
      STOF(ISTOF + 29) = SCRmax
      STOF(ISTOF + 30) = Pblst_pu
      STOF(ISTOF + 37) = iVb
      STOF(ISTOF + 38) = iIb
      STOF(ISTOF + 39) = iVdc
      STOF(ISTOF + 40) = RT_1
      STOF(ISTOF + 50) = Vdc_pu
      STOF(ISTOF + 54) = hGPWM
      STOF(ISTOF + 55) = dGPWM

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 0 + IT_0) = Igabc_kA(IT_0)
         STOF(ISTOF + 4 + IT_0) = Vgabc_kV(IT_0)
         STOF(ISTOF + 17 + IT_0) = Itabc_kA(IT_0)
         STOF(ISTOF + 30 + IT_0) = Vgabcpu_(IT_0)
         STOF(ISTOF + 33 + IT_0) = Igabcpu_(IT_0)
         STOF(ISTOF + 40 + IT_0) = Itabcpu(IT_0)
         STOF(ISTOF + 43 + IT_0) = Vgabc_pu(IT_0)
         STOF(ISTOF + 46 + IT_0) = Igabc_pu(IT_0)
         STOF(ISTOF + 50 + IT_0) = Itabc_pu(IT_0)
      END DO

! Array (1:5) quantities...
      DO IT_0 = 1,5
         STOF(ISTOF + 10 + IT_0) = Sig_GSC_(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Sig_GSC_ is output
      !Vgabcpu_ is output
      !Igabcpu_ is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE UCOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    Parameters_BasesOut  ! 
!     SUBR    Measurement_FilterOut  ! 
!     SUBR    GSCOut        ! Grid Side Converter Controller

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------



!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'UC.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 260:[Parameters_Bases]  'Parameters_1_1'
      CALL Parameters_BasesOut()


! 310:[Measurement_Filter]  
      CALL Measurement_FilterOut()


! 320:[GSC] Grid Side Converter Controller 
      CALL GSCOut()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------



!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE UCDyn_Begin(Sbase1, Fnom, Vac_nom, Vdc_nom,            &
     &   Freq_PWM_GSC)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    Parameters_BasesDyn_Begin  ! 
!     SUBR    Measurement_FilterDyn_Begin  ! 
!     SUBR    GSCDyn_Begin  ! Grid Side Converter Controller

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(IN)  :: Freq_PWM_GSC

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 190:[gain] Gain Block 

! 250:[gain] Gain Block 

! 260:[Parameters_Bases]  'Parameters_1_1'
      CALL Parameters_BasesDyn_Begin(Sbase1, Fnom, Vac_nom, Vdc_nom)


! 270:[gain] Gain Block 

! 280:[gain] Gain Block 

! 290:[gain] Gain Block 

! 300:[gain] Gain Block 

! 310:[Measurement_Filter]  
      CALL Measurement_FilterDyn_Begin(0.707)


! 320:[GSC] Grid Side Converter Controller 
      CALL GSCDyn_Begin(Sbase1, Fnom, Vac_nom, Vdc_nom, Freq_PWM_GSC)


      RETURN
      END

!=======================================================================

      SUBROUTINE UCOut_Begin(Sbase1, Fnom, Vac_nom, Vdc_nom,            &
     &   Freq_PWM_GSC)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    Parameters_BasesOut_Begin  ! 
!     SUBR    Measurement_FilterOut_Begin  ! 
!     SUBR    GSCOut_Begin  ! Grid Side Converter Controller

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Sbase1, Fnom
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(IN)  :: Freq_PWM_GSC

! Electrical Node Indices

! Control Signals

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 260:[Parameters_Bases]  'Parameters_1_1'
      CALL Parameters_BasesOut_Begin(Sbase1, Fnom, Vac_nom, Vdc_nom)


! 310:[Measurement_Filter]  
      CALL Measurement_FilterOut_Begin(0.707)


! 320:[GSC] Grid Side Converter Controller 
      CALL GSCOut_Begin(Sbase1, Fnom, Vac_nom, Vdc_nom, Freq_PWM_GSC)


      RETURN
      END

