!=======================================================================
! Generated by: PSCAD v5.0.1.0
! Warning:  The content of this file is automatically generated.
!           Do not modify, as any changes made here will be lost!
!-----------------------------------------------------------------------
! Component     : Uref_Generator
! Description   : Uref Generator Std
!-----------------------------------------------------------------------


!=======================================================================

      SUBROUTINE Uref_GeneratorDyn(Vtdqref_pu, Theta, Vdc_pu, Uref_pu_, &
     &   Enable, Vac_nom, Vdc_nom, mdq_max, Priority, VtdqLim_)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

      REAL    LIMIT         ! Hard Limiter
!     SUBR    DQ0_to_ABCDyn  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      INTEGER, INTENT(IN)  :: Enable, Priority
      REAL,    INTENT(IN)  :: Vtdqref_pu(2)
      REAL,    INTENT(IN)  :: Theta, Vdc_pu
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(IN)  :: mdq_max
      INTEGER, INTENT(OUT) :: VtdqLim_(2)! Aliases: VtdqLim
      REAL,    INTENT(OUT) :: Uref_pu_(3)! Aliases: Uref_pu

! Electrical Node Indices

! Control Signals
      INTEGER  VtdLim, VtqLim
      REAL     md_, mq_, RT_1, RT_2, RT_3, RT_4
      REAL     RT_5, RT_6, RT_7, RT_8, md, RT_9
      REAL     mq, RT_10, RT_11, RT_12, RT_13
      REAL     RT_14, RT_15, RT_16, RT_17, RT_18
      REAL     RT_19, RT_20, RT_21, mq_min
      REAL     mq_max, RT_22, RT_23, RT_24, RT_25
      REAL     md_min, md_max, RT_26, RT_27
      REAL     RT_28(2), RT_29(2), RT_30(2), mdl
      REAL     mql, RT_31, RT_32

! Internal Variables
      LOGICAL  LVD1_1

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOI, ISTOF, IT_0                  ! Storage Indices
      INTEGER IPGB                                ! Control/Monitoring
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      TXFR(NTXFR,1) = NSTOL
      TXFR(NTXFR,2) = NSTOI
      TXFR(NTXFR,3) = NSTOF
      TXFR(NTXFR,4) = NSTOC

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      ISTOI     = NSTOI
      NSTOI     = NSTOI + 6
      ISTOF     = NSTOF
      NSTOF     = NSTOF + 55
      IPGB      = NPGB
      NPGB      = NPGB + 6
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      md_      = STOF(ISTOF + 11)
      mq_      = STOF(ISTOF + 12)
      RT_1     = STOF(ISTOF + 13)
      RT_2     = STOF(ISTOF + 14)
      RT_3     = STOF(ISTOF + 15)
      RT_4     = STOF(ISTOF + 16)
      RT_5     = STOF(ISTOF + 17)
      RT_6     = STOF(ISTOF + 18)
      RT_7     = STOF(ISTOF + 19)
      RT_8     = STOF(ISTOF + 20)
      md       = STOF(ISTOF + 21)
      RT_9     = STOF(ISTOF + 22)
      mq       = STOF(ISTOF + 23)
      RT_10    = STOF(ISTOF + 24)
      RT_11    = STOF(ISTOF + 25)
      RT_12    = STOF(ISTOF + 26)
      RT_13    = STOF(ISTOF + 27)
      RT_14    = STOF(ISTOF + 28)
      RT_15    = STOF(ISTOF + 29)
      RT_16    = STOF(ISTOF + 30)
      RT_17    = STOF(ISTOF + 31)
      RT_18    = STOF(ISTOF + 32)
      RT_19    = STOF(ISTOF + 33)
      RT_20    = STOF(ISTOF + 34)
      RT_21    = STOF(ISTOF + 35)
      mq_min   = STOF(ISTOF + 36)
      mq_max   = STOF(ISTOF + 37)
      RT_22    = STOF(ISTOF + 38)
      RT_23    = STOF(ISTOF + 39)
      RT_24    = STOF(ISTOF + 40)
      RT_25    = STOF(ISTOF + 41)
      md_min   = STOF(ISTOF + 42)
      md_max   = STOF(ISTOF + 43)
      RT_26    = STOF(ISTOF + 44)
      RT_27    = STOF(ISTOF + 45)
      VtdLim   = STOI(ISTOI + 5)
      VtqLim   = STOI(ISTOI + 6)
      mdl      = STOF(ISTOF + 52)
      mql      = STOF(ISTOF + 53)
      RT_31    = STOF(ISTOF + 54)
      RT_32    = STOF(ISTOF + 55)

! Array (1:2) quantities...
      DO IT_0 = 1,2
         VtdqLim_(IT_0) = STOI(ISTOI + 2 + IT_0)
         RT_28(IT_0) = STOF(ISTOF + 45 + IT_0)
         RT_29(IT_0) = STOF(ISTOF + 47 + IT_0)
         RT_30(IT_0) = STOF(ISTOF + 49 + IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         Uref_pu_(IT_0) = STOF(ISTOF + 4 + IT_0)
      END DO


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Uref_Generator.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSD:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 
      RT_32 = 0.1

! 20:[const] Real Constant 
      RT_31 = 0.9

! 30:[const] Real Constant 
      RT_1 = 0.0

! 120:[gain] Gain Block 
!  Gain
      RT_16 = Vdc_nom * Vdc_pu

! 130:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (0.001 .LE. 10000000000.0) THEN
        RT_13 = LIMIT(0.001, 10000000000.0, RT_16)
      ELSE
        RT_13 = RT_16
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,815070130,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 140:[gain] Gain Block 
!  Gain
      RT_11 = 0.816497 * Vac_nom

! 150:[gain] Gain Block 
!  Gain
      RT_12 = 0.5 * RT_13

! 160:[datatap] Scalar/Array Tap 
      RT_7 = Vtdqref_pu(1)

! 170:[datatap] Scalar/Array Tap 
      RT_8 = Vtdqref_pu(2)

! 180:[datamerge] Merges data signals into an array 
      RT_29(1) = RT_31
      RT_29(2) = RT_32

! 190:[square] Square 
      RT_17 = mdq_max * mdq_max

! 200:[polar_rec] Polar Rectangular coordinate converter 
      RT_6 = SQRT(RT_7*RT_7+RT_8*RT_8)
      IF ((ABS(RT_7).GT.1.0E-20).OR.(ABS(RT_8).GT.1.0E-20)) THEN
        RT_5 = ATAN2(RT_8,RT_7)
      ELSE
        RT_5 = 0.0
      ENDIF

! 210:[mult] Multiplier 
      RT_10 = RT_6 * RT_11

! 220:[div] Divider 
      IF (ABS(RT_12) .LT. 1.0E-100) THEN
         IF (RT_12 .LT. 0.0)  THEN
            RT_14 = -1.0E100 * RT_10
         ELSE
            RT_14 =  1.0E100 * RT_10
         ENDIF
      ELSE
         RT_14 = RT_10 / RT_12
      ENDIF

! 230:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (0.0 .LE. mdq_max) THEN
        RT_15 = LIMIT(0.0, mdq_max, RT_14)
      ELSE
        RT_15 = RT_14
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,622540109,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 240:[select] Two Input Selector 
      IF (Priority .EQ. RTCI(NRTCI)) THEN
         RT_9 = RT_15
      ELSE
         RT_9 = RT_14
      ENDIF
      NRTCI = NRTCI + 1
!

! 250:[polar_rec] Polar Rectangular coordinate converter 
      md = RT_9*COS(RT_5)
      mq = RT_9*SIN(RT_5)

! 260:[square] Square 
      RT_18 = md * md

! 270:[sumjct] Summing/Differencing Junctions 
      RT_19 = + RT_17 - RT_18

! 280:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (0.0 .LE. 1.0e+308) THEN
        RT_21 = LIMIT(0.0, 1.0e+308, RT_19)
      ELSE
        RT_21 = RT_19
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,1184531759,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 290:[sqrt] Square Root 
      LVD1_1 = STORL(NSTORL)
      IF (RT_21 .LT. 0.0) THEN
        RT_20 = 0.0
        IF (.NOT. LVD1_1) THEN
          CALL EMTDC_MESSAGE(ICALL_NO,2003907830,1,2,"A negative value i&
     &s detected as an input to the Square Root function. ")
          CALL EMTDC_MESSAGE(ICALL_NO,2003907830,1,-1,"Input is treated &
     &as 0.0.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ELSE
         RT_20 = SQRT(RT_21)
      ENDIF
      NSTORL = NSTORL + 1

! 300:[select] Two Input Selector 
      IF (Priority .EQ. RTCI(NRTCI)) THEN
         mq_max = RT_20
      ELSE
         mq_max = mdq_max
      ENDIF
      NRTCI = NRTCI + 1
!

! 310:[gain] Gain Block 
!  Gain
      mq_min = -1.0 * mq_max

! 320:[square] Square 
      RT_22 = mq * mq

! 330:[sumjct] Summing/Differencing Junctions 
      RT_23 = + RT_17 - RT_22

! 340:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (0.0 .LE. 1.0e+308) THEN
        RT_25 = LIMIT(0.0, 1.0e+308, RT_23)
      ELSE
        RT_25 = RT_23
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,732531548,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 350:[sqrt] Square Root 
      LVD1_1 = STORL(NSTORL)
      IF (RT_25 .LT. 0.0) THEN
        RT_24 = 0.0
        IF (.NOT. LVD1_1) THEN
          CALL EMTDC_MESSAGE(ICALL_NO,2057485866,1,2,"A negative value i&
     &s detected as an input to the Square Root function. ")
          CALL EMTDC_MESSAGE(ICALL_NO,2057485866,1,-1,"Input is treated &
     &as 0.0.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ELSE
         RT_24 = SQRT(RT_25)
      ENDIF
      NSTORL = NSTORL + 1

! 360:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (mq_min .LE. mq_max) THEN
        mql = LIMIT(mq_min, mq_max, mq)
      ELSE
        mql = mq
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,1256414004,1,"Lower limit is more tha&
     &n the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 370:[select] Two Input Selector 
      IF (Priority .EQ. RTCI(NRTCI)) THEN
         md_max = RT_24
      ELSE
         md_max = mdq_max
      ENDIF
      NRTCI = NRTCI + 1
!

! 380:[gain] Gain Block 
!  Gain
      md_min = -1.0 * md_max

! 390:[hardlimit] Hard Limiter 
!  Hard_Limit
      IF (md_min .LE. md_max) THEN
        mdl = LIMIT(md_min, md_max, md)
      ELSE
        mdl = md
        IF (STORL(NSTORL) .EQV. .FALSE.) THEN
          CALL EMTDC_WARN(ICALL_NO,476712179,1,"Lower limit is more than&
     & the upper limit, limits not enforced.")
          STORL(NSTORL) = .TRUE.
        ENDIF
      ENDIF
      NSTORL = NSTORL + 1
!

! 400:[datamerge] Merges data signals into an array 
      RT_28(1) = mdl
      RT_28(2) = mql

! 410:[select] Two Input Selector 
      IF (Enable .EQ. RTCI(NRTCI)) THEN
         RT_30 = RT_28
      ELSE
         RT_30 = RT_29
      ENDIF
      NRTCI = NRTCI + 1
!

! 420:[sumjct] Summing/Differencing Junctions 
      RT_26 = - mdl + md

! 430:[datatap] Scalar/Array Tap 
      mq_ = RT_30(2)

! 440:[datatap] Scalar/Array Tap 
      md_ = RT_30(1)

! 450:[sumjct] Summing/Differencing Junctions 
      RT_27 = - mql + mq

! 460:[range] Range Comparator 
!  Band_Compare
      IF (RT_26 .LT. 0.0) THEN
         VtdLim = NINT(1.0)
      ELSE IF (RT_26 .LE. 0.0) THEN
         VtdLim = NINT(0.0)
      ELSE
         VtdLim = NINT(1.0)
      ENDIF
!

! 470:[DQ0_to_ABC]  
      CALL DQ0_to_ABCDyn(md_, mq_, RT_1, RT_2, RT_3, RT_4, Theta)


! 480:[range] Range Comparator 
!  Band_Compare
      IF (RT_27 .LT. 0.0) THEN
         VtqLim = NINT(1.0)
      ELSE IF (RT_27 .LE. 0.0) THEN
         VtqLim = NINT(0.0)
      ELSE
         VtqLim = NINT(1.0)
      ENDIF
!

! 490:[datamerge] Merges data signals into an array 
      VtdqLim_(1) = VtdLim
      VtdqLim_(2) = VtqLim

! 500:[datamerge] Merges data signals into an array 
      Uref_pu_(1) = RT_2
      Uref_pu_(2) = RT_3
      Uref_pu_(3) = RT_4

! 530:[pgb] Output Channel 'VtqLim'

      PGB(IPGB+1) = REAL(VtqLim)

! 540:[pgb] Output Channel 'VtdLim'

      PGB(IPGB+2) = REAL(VtdLim)

! 550:[pgb] Output Channel 'md_max'

      PGB(IPGB+3) = md_max

! 560:[pgb] Output Channel 'mq_'

      PGB(IPGB+4) = mq_

! 570:[pgb] Output Channel 'md_'

      PGB(IPGB+5) = md_

! 580:[pgb] Output Channel 'mq_max'

      PGB(IPGB+6) = mq_max

!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 3) = Theta
      STOF(ISTOF + 4) = Vdc_pu
      STOI(ISTOI + 1) = Enable
      STOF(ISTOF + 8) = Vac_nom
      STOF(ISTOF + 9) = Vdc_nom
      STOF(ISTOF + 10) = mdq_max
      STOI(ISTOI + 2) = Priority
      STOF(ISTOF + 11) = md_
      STOF(ISTOF + 12) = mq_
      STOF(ISTOF + 13) = RT_1
      STOF(ISTOF + 14) = RT_2
      STOF(ISTOF + 15) = RT_3
      STOF(ISTOF + 16) = RT_4
      STOF(ISTOF + 17) = RT_5
      STOF(ISTOF + 18) = RT_6
      STOF(ISTOF + 19) = RT_7
      STOF(ISTOF + 20) = RT_8
      STOF(ISTOF + 21) = md
      STOF(ISTOF + 22) = RT_9
      STOF(ISTOF + 23) = mq
      STOF(ISTOF + 24) = RT_10
      STOF(ISTOF + 25) = RT_11
      STOF(ISTOF + 26) = RT_12
      STOF(ISTOF + 27) = RT_13
      STOF(ISTOF + 28) = RT_14
      STOF(ISTOF + 29) = RT_15
      STOF(ISTOF + 30) = RT_16
      STOF(ISTOF + 31) = RT_17
      STOF(ISTOF + 32) = RT_18
      STOF(ISTOF + 33) = RT_19
      STOF(ISTOF + 34) = RT_20
      STOF(ISTOF + 35) = RT_21
      STOF(ISTOF + 36) = mq_min
      STOF(ISTOF + 37) = mq_max
      STOF(ISTOF + 38) = RT_22
      STOF(ISTOF + 39) = RT_23
      STOF(ISTOF + 40) = RT_24
      STOF(ISTOF + 41) = RT_25
      STOF(ISTOF + 42) = md_min
      STOF(ISTOF + 43) = md_max
      STOF(ISTOF + 44) = RT_26
      STOF(ISTOF + 45) = RT_27
      STOI(ISTOI + 5) = VtdLim
      STOI(ISTOI + 6) = VtqLim
      STOF(ISTOF + 52) = mdl
      STOF(ISTOF + 53) = mql
      STOF(ISTOF + 54) = RT_31
      STOF(ISTOF + 55) = RT_32

! Array (1:2) quantities...
      DO IT_0 = 1,2
         STOF(ISTOF + 0 + IT_0) = Vtdqref_pu(IT_0)
         STOI(ISTOI + 2 + IT_0) = VtdqLim_(IT_0)
         STOF(ISTOF + 45 + IT_0) = RT_28(IT_0)
         STOF(ISTOF + 47 + IT_0) = RT_29(IT_0)
         STOF(ISTOF + 49 + IT_0) = RT_30(IT_0)
      END DO

! Array (1:3) quantities...
      DO IT_0 = 1,3
         STOF(ISTOF + 4 + IT_0) = Uref_pu_(IT_0)
      END DO


!---------------------------------------
! Transfer to Exports
!---------------------------------------
      !Uref_pu_ is output
      !VtdqLim_ is output

!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Uref_GeneratorOut()

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 'emtstor.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's2.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'fnames.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'matlab.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    DQ0_to_ABCOut  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_31, RT_32

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER ISTOL, ISTOI, ISTOF, ISTOC          ! Storage Indices
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------

! Dsdyn <-> Dsout transfer index storage

      NTXFR = NTXFR + 1

      ISTOL = TXFR(NTXFR,1)
      ISTOI = TXFR(NTXFR,2)
      ISTOF = TXFR(NTXFR,3)
      ISTOC = TXFR(NTXFR,4)

! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NPGB      = NPGB + 6
      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Transfers from storage arrays 
!---------------------------------------

      RT_1     = STOF(ISTOF + 13)
      RT_31    = STOF(ISTOF + 54)
      RT_32    = STOF(ISTOF + 55)


!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Configuration of Models 
!---------------------------------------

      IF ( TIMEZERO ) THEN
         FILENAME = 'Uref_Generator.dta'
         CALL EMTDC_OPENFILE
         SECTION = 'DATADSO:'
         CALL EMTDC_GOTOSECTION
      ENDIF
!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 

      RT_32 = 0.1

! 20:[const] Real Constant 

      RT_31 = 0.9

! 30:[const] Real Constant 

      RT_1 = 0.0

! 470:[DQ0_to_ABC]  
      CALL DQ0_to_ABCOut()


!---------------------------------------
! Feedbacks and transfers to storage 
!---------------------------------------

      STOF(ISTOF + 13) = RT_1
      STOF(ISTOF + 54) = RT_31
      STOF(ISTOF + 55) = RT_32


!---------------------------------------
! Close Model Data read 
!---------------------------------------

      IF ( TIMEZERO ) CALL EMTDC_CLOSEFILE
      RETURN
      END

!=======================================================================

      SUBROUTINE Uref_GeneratorDyn_Begin(Vac_nom, Vdc_nom, mdq_max)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    DQ0_to_ABCDyn_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(IN)  :: mdq_max

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_31, RT_32

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 
      RT_32 = 0.1

! 20:[const] Real Constant 
      RT_31 = 0.9

! 30:[const] Real Constant 
      RT_1 = 0.0

! 120:[gain] Gain Block 

! 130:[hardlimit] Hard Limiter 

! 140:[gain] Gain Block 

! 150:[gain] Gain Block 

! 160:[datatap] Scalar/Array Tap 

! 170:[datatap] Scalar/Array Tap 

! 180:[datamerge] Merges data signals into an array 

! 190:[square] Square 

! 200:[polar_rec] Polar Rectangular coordinate converter 

! 210:[mult] Multiplier 

! 220:[div] Divider 

! 230:[hardlimit] Hard Limiter 

! 240:[select] Two Input Selector 
      RTCI(NRTCI) = 2
      NRTCI = NRTCI + 1

! 250:[polar_rec] Polar Rectangular coordinate converter 

! 260:[square] Square 

! 270:[sumjct] Summing/Differencing Junctions 

! 280:[hardlimit] Hard Limiter 

! 290:[sqrt] Square Root 

! 300:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 310:[gain] Gain Block 

! 320:[square] Square 

! 330:[sumjct] Summing/Differencing Junctions 

! 340:[hardlimit] Hard Limiter 

! 350:[sqrt] Square Root 

! 360:[hardlimit] Hard Limiter 

! 370:[select] Two Input Selector 
      RTCI(NRTCI) = 0
      NRTCI = NRTCI + 1

! 380:[gain] Gain Block 

! 390:[hardlimit] Hard Limiter 

! 400:[datamerge] Merges data signals into an array 

! 410:[select] Two Input Selector 
      RTCI(NRTCI) = 1
      NRTCI = NRTCI + 1

! 420:[sumjct] Summing/Differencing Junctions 

! 430:[datatap] Scalar/Array Tap 

! 440:[datatap] Scalar/Array Tap 

! 450:[sumjct] Summing/Differencing Junctions 

! 460:[range] Range Comparator 

! 470:[DQ0_to_ABC]  
      CALL DQ0_to_ABCDyn_Begin()


! 480:[range] Range Comparator 

! 490:[datamerge] Merges data signals into an array 

! 500:[datamerge] Merges data signals into an array 

! 530:[pgb] Output Channel 'VtqLim'

! 540:[pgb] Output Channel 'VtdLim'

! 550:[pgb] Output Channel 'md_max'

! 560:[pgb] Output Channel 'mq_'

! 570:[pgb] Output Channel 'md_'

! 580:[pgb] Output Channel 'mq_max'

      RETURN
      END

!=======================================================================

      SUBROUTINE Uref_GeneratorOut_Begin(Vac_nom, Vdc_nom, mdq_max)

!---------------------------------------
! Standard includes 
!---------------------------------------

      INCLUDE 'nd.h'
      INCLUDE 'emtconst.h'
      INCLUDE 's0.h'
      INCLUDE 's1.h'
      INCLUDE 's4.h'
      INCLUDE 'branches.h'
      INCLUDE 'pscadv3.h'
      INCLUDE 'radiolinks.h'
      INCLUDE 'rtconfig.h'

!---------------------------------------
! Function/Subroutine Declarations 
!---------------------------------------

!     SUBR    DQ0_to_ABCOut_Begin  ! 

!---------------------------------------
! Variable Declarations 
!---------------------------------------


! Subroutine Arguments
      REAL,    INTENT(IN)  :: Vac_nom, Vdc_nom
      REAL,    INTENT(IN)  :: mdq_max

! Electrical Node Indices

! Control Signals
      REAL     RT_1, RT_31, RT_32

! Internal Variables

! Indexing variables
      INTEGER ICALL_NO                            ! Module call num
      INTEGER SS                                  ! SS/Node/Branch/Xfmr


!---------------------------------------
! Local Indices 
!---------------------------------------


! Define electric network subsystem number

      SS        = NODE(NNODE+1)

! Increment and assign runtime configuration call indices

      ICALL_NO  = NCALL_NO
      NCALL_NO  = NCALL_NO + 1

! Increment global storage indices

      NNODE     = NNODE + 2
      NCSCS     = NCSCS + 0
      NCSCR     = NCSCR + 0

!---------------------------------------
! Electrical Node Lookup 
!---------------------------------------


!---------------------------------------
! Generated code from module definition 
!---------------------------------------


! 10:[const] Real Constant 
      RT_32 = 0.1

! 20:[const] Real Constant 
      RT_31 = 0.9

! 30:[const] Real Constant 
      RT_1 = 0.0

! 470:[DQ0_to_ABC]  
      CALL DQ0_to_ABCOut_Begin()


      RETURN
      END

